### ISSUE TITLE
Can't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by jimjam-slam** [dankelley/oce#1739] opened 2020-10-13 05:08 UTC
### Short summary of problem

I'm having trouble installing `oce` on a Ubuntu 20.04 distro running under WSL2:

```
E> ** testing if installed package can be loaded from temporary location
E> Error: package or namespace load failed for ‘oce’ in dyn.load(file, DLLpath = DLLpath, ...):
E>  unable to load shared object '/tmp/Rtmpmq4E1W/Rinst22ce77d36039/00LOCK-oce/00new/oce/libs/oce.so':
E>   libgfortran.so.3: cannot open shared object file: No such file or directory
```

### What you did

I've tried both the `develop` and `master` branches, as well as installing from CRAN:

```
devtools::install('dankelley/oce')
```

```
devtools::install('dankelley/oce@develop')
```

```
install.packages('oce')
```

Searching around, I found `libgfortran3` was recommended for `libgfortran.so.3`, but it wasn't available on Ubuntu 20.04. Instead, I installed  `libgfortran5`, but this didn't fix the problem.

### What you expected to happen

A successful installation of `oce`.

### Output from sessionInfo()

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] here_0.1        lubridate_1.7.9 forcats_0.5.0   stringr_1.4.0  
 [5] dplyr_1.0.2     purrr_0.3.4     readr_1.3.1     tidyr_1.1.2    
 [9] tibble_3.0.3    ggplot2_3.3.2   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.0  remotes_2.2.0     haven_2.3.1       testthat_2.3.2   
 [5] colorspace_1.4-1  vctrs_0.3.4       generics_0.0.2    usethis_1.6.3    
 [9] blob_1.2.1        rlang_0.4.8       pkgbuild_1.1.0    pillar_1.4.6     
[13] glue_1.4.2        withr_2.3.0       DBI_1.1.0         dbplyr_1.4.4     
[17] sessioninfo_1.1.1 modelr_0.1.8      readxl_1.3.1      lifecycle_0.2.0  
[21] munsell_0.5.0     gtable_0.3.0      cellranger_1.1.0  rvest_0.3.6      
[25] devtools_2.3.2    memoise_1.1.0     callr_3.5.0       ps_1.4.0         
[29] curl_4.3          fansi_0.4.1       broom_0.7.0       Rcpp_1.0.5       
[33] scales_1.1.1      backports_1.1.10  desc_1.2.0        pkgload_1.1.0    
[37] jsonlite_1.7.1    fs_1.5.0          hms_0.5.3         digest_0.6.25    
[41] stringi_1.5.3     processx_3.4.4    grid_4.0.2        rprojroot_1.3-2  
[45] cli_2.1.0         tools_4.0.2       magrittr_1.5      crayon_1.3.4     
[49] pkgconfig_2.0.3   ellipsis_0.3.1    xml2_1.3.2        prettyunits_1.1.1
[53] reprex_0.3.0      assertthat_0.2.1  httr_1.4.2        rstudioapi_0.11  
[57] R6_2.4.1          compiler_4.0.2 
```

**Comment by dankelley** [comment] 2020-10-13 09:41
Thanks for the report.  I am not sure what to advise.  Since nothing in the oce package setup dictates what version of fortran to use, it looks to me as though your system is not set up to compile any R package that contains fortran source.  So, perhaps this is a broader question for the R community.

I do not use linux anymore, having transitioned to macos many years ago, so I am not sure on which R community discussion board to ask this.  Perhaps stack exchange?

I wonder if @richardsc has any thoughts on this, since I think he has access to some form of linux.

I'm sorry I cannot offer any more helpful advice.

**Comment by richardsc** [comment] 2020-10-13 10:27
As @dankelley pointed out, setting up a linux system to be able to build oce from source is a bit involved. I'm a bit confused, as it looks like you are already set up to build packages, but it may in fact be the Fortran set that is causing problems here. I could be wrong but I thought that gcc took care of the required fortran ...

I suspect that the problem is having the required system libraries installed to be able to build/install oce, but the last time I did this successfully (on a WSL Ubuntu 18.04) I didn't do a good job of documenting the required steps and installs. I'll take a look around and report back.

(there are some instructions [here](https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source) but as you can see they are hopelessly outdated and incomplete).

**Comment by rensa** [comment] 2020-10-13 22:23
Ahh, that makes sense. I should clarify that I installed `libgfortran5` because [apparently `libgfortran3` isn't supported on Ubuntu 20.04](https://stackoverflow.com/a/63283185/3246758). It seems like the solution for me might be installing an older version of gcc, so I'm gearing up to try that 😊

**Comment by richardsc** [comment] 2020-11-02 04:15
Hi @rensa -- did you have any luck getting things running on 20.04? I have been swamped and between computers (sadly, neither of them running linux) so haven't had time to try firing up a 20.04 VM to document the setup procedure (even the last time I set up a system that can build from source it was 18.04).

**Comment by rensa** [comment] 2020-11-02 04:16
Not yet, but if I get some breathing room in the next few days I'll give it a go! (For my immediate problem I installed on Windows instead.)

**Comment by richardsc** [comment] 2020-11-13 14:39
I can't figure out how to reopen this issue using the (newly installed) GitHub app for iOS, but just a note that yesterday I had to install Linux mint 20 on an old machine and so will use it as a test case for documenting all the steps required to setup up an Ubuntu (similar) system to be able to build oce. 

@dankelley will you please reopen and remove the stale label?

**Comment by richardsc** [comment] 2020-11-14 18:51
@rensa I'm not sure if this is going to solve your original problem (which appears to be an issue with gfortran), but I just wrote up a guide for install R/oce and dependencies on a fresh install of Linux Mint 20 (equivalent to Ubuntu 20.04). It's a bit involved but it worked for me without issues.

https://github.com/dankelley/oce/wiki/Configuring-a-Linux-Mint-20-system-to-be-able-to-build-oce-from-source

**Comment by erika-r** [comment] 2022-04-16 11:08
Has anyone been able to solve this issue yet?

**Comment by dankelley** [comment] 2022-04-16 11:15
I'm reopening this, in case @richardsc (who I think has some form of linux machine) might wish to comment.

**Comment by richardsc** [comment] 2022-04-17 18:30
I'll take a look. I can potentially install Ubuntu 20.04 as a WSL (but it's on a restricted computer so isn't a great general test), and I have been looking into how to run Ubuntu VMs on my M1 Mac (virtualBox is intel only, and of course trying to install intel-based distros won't work easily on the M1 ARM architecture).

@erika-r : A few questions:

1. The original issue was about Ubuntu 20.04 on Windows (WSL). Is that still an issue for you, or is your issue general enough that it applies to *all* Ubuntu 20.04 installations?

2. Have you tried the steps outlined [here](https://github.com/dankelley/oce/wiki/Configuring-a-Linux-Mint-20-system-to-be-able-to-build-oce-from-source)?

**Comment by erika-r** [comment] 2022-04-17 21:58
I actually solved the issue although I'm not entirely sure on the fix. I was using a virtual environment and when I disabled it, the issue went away.

**Comment by richardsc** [comment] 2022-04-18 00:48
Ok, good to know. When you say "virtual environment" do you mean a python venv? It's possible, if you were using conda, that you may have installed an alternate R toolchain that didn't have the required dependecies and compilers for building packages.

For the record, I installed a version of ARM Ubuntu 21.10 as a VM through UTM on MacOS (had to use 21.10 because it includes R 4.0 by default, whereas Ubuntu 20.04 has R 3.6, and the ubuntu R4.0 repositories are not compatible with ARM64), and other than skipping adding the keyserver and repository for `cran40` I was able to install oce and all it's dependecies without issue (after installing the noted system dependencies).

**Comment by dankelley** [comment] 2022-05-09 09:59
I wonder whether this issue has been addressed.  (I am trying to clear up existing issues, for the upcoming CRAN release, as described at #1942.)

**Comment by dankelley** [comment] 2022-07-28 15:57
This issue was closed by the developer who solved the problem, because the following conditions were met:
1. the solution is simple
2. new tests were added to ensure that the solution works
3. the reporter is in frequent contact with the developer

Of course, if the reporter wants to reopen the issue, that's perfectly fine! The point here is just to avoid having issues in the developers' "to do" list, when they are probably done.

**Closed by dankelley** 2022-07-28 15:57 UTC
