### ISSUE TITLE
Plotting data density with oce?

### ISSUE THREAD

**Issue by AnneMTreasure** [dankelley/oce#1000] opened 2016-06-27 13:40 UTC
Hi there,

I have a query about functionality and whether something is / will be possible in oce. I need to plot a distribution of data density (point intensity / density of lat/long points), such as this (from http://www.meop.net/):

![density_global-2_med](https://cloud.githubusercontent.com/assets/7634887/16381189/8df16602-3c7b-11e6-94ff-f68db0f04c88.png)

onto this oce produced map projected for Antarctica:

![r_oce_antarcticamap](https://cloud.githubusercontent.com/assets/7634887/16380941/2c2adb3e-3c7a-11e6-8595-7351fca71dc3.png)

There are packages and functions in R that calculate data density, such as the [spatstat](https://cran.r-project.org/web/packages/spatstat/index.html) package. But I've been struggling to combine this with the projected map that I would like to use.

Is this possible with oce?

Thank you so much,
Anne Treasure

**Comment by richardsc** [comment] 2016-06-27 15:14
Hi @AnneMTreasure 

I'm not too familiar with other data density packages (definitely going to check them out, though, thanks!), but I think there are a couple of ways of doing what you want within oce.

To make projected map plots of such fields, the function you want is `mapImage()`. Below is an example that uses data from a WOA 2013 netcdf file, showing the logarithm of the number of data points within each 1x1 degree box:
```r
library(oce)
library(ncdf4)
data(coastlineWorld)

set.seed(123)

nc <- nc_open('/data/archive/woa/2013/nc/01/woa13_decav_s00_01v2.nc')
lon <- ncvar_get(nc, 'lon')
lat <- ncvar_get(nc, 'lat')
N <- ncvar_get(nc, 's_dd')
N <- apply(N, c(1, 2), sum, na.rm=TRUE) # flatten the 3d array to 2d
logN <- log10(N)
logN[is.infinite(logN)] <- NA  # remove any -Inf values which cause problems with plotting

par(mar=c(2, 2, 1, 1))
cm <- colormap(logN, col=oceColorsViridis, missingColor = NA)
drawPalette(colormap=cm)
mapPlot(coastlineWorld, projection='+proj=stere +lat_0=-90', col='grey',
        latitudelim=c(-30, -90),
        longitudelim=c(-180, 180))
mapImage(lon, lat, logN, colormap=cm)
mapPolygon(coastlineWorld, col='grey')
```
![screen shot 2016-06-27 at 11 09 21](https://cloud.githubusercontent.com/assets/233584/16384622/a2f2a008-3c57-11e6-88ee-a4c6772ac4ca.png)
You'll need the `woa13_decav_s00_01v2.nc` file to make that work.

To illustrate how you could create something yourself (e.g. from a data source like MEOP), using the `binCount2D()` function from oce, check out the example below. Probably a good idea to read the help page for `binCount2D()` to see what the arguments and return values are, but the below should get you started:
```r
## Create a gaussian "ring" around antarctica
rlon <- runif(1e6)*360 - 180
rlat <- rnorm(1e6, -60, 5)
rlat[rlat < -90] <- NA # remove unphysical values

## do a "2D histogram" of the lon/lat points
## for 1x1 degree boxes
b <- binCount2D(rlon, rlat, seq(-180, 180, 1), seq(-90, 90, 1))

par(mar=c(2, 2, 1, 1))
cm <- colormap(b$number, col=oceColorsViridis, missingColor = NA)
drawPalette(colormap=cm)
mapPlot(coastlineWorld, projection='+proj=stere +lat_0=-90', col='grey',
        latitudelim=c(-30, -90),
        longitudelim=c(-180, 180))
mapImage(b$xmids, b$ymids, b$number, colormap=cm) # note xmids/ymids for plotting
mapPolygon(coastlineWorld, col='grey')
```
![screen shot 2016-06-27 at 11 12 12](https://cloud.githubusercontent.com/assets/233584/16384716/0da6c1f4-3c58-11e6-92b4-828790b73bc3.png)

**Comment by richardsc** [comment] 2016-06-27 19:56
Just as an addendum, because I don't like the look of that "purple" plot above, here's how you could modify the colormap to use white when there are *no* values within a box:
```r
cm <- colormap(b$number, col=colorRampPalette(c('white', oceColorsViridis(11))),
               zlim=c(0, max(b$number)), missingColor=NA)
drawPalette(colormap=cm)
mapPlot(coastlineWorld, projection='+proj=stere +lat_0=-90', col='grey',
        latitudelim=c(-30, -90),
        longitudelim=c(-180, 180))
mapImage(b$xmids, b$ymids, b$number, colormap=cm) # note xmids/ymids for plotting
mapPolygon(coastlineWorld, col='grey')
```
![screen shot 2016-06-27 at 15 56 18](https://cloud.githubusercontent.com/assets/233584/16393690/b2ca7654-3c7f-11e6-823c-28fbdcf994c9.png)

**Comment by dankelley** [comment] 2016-06-27 22:40
There's a 'converging meridian' aspect to gridding in lon/lat space, and perhaps `spatstat` handles that, e.g. by computing areal averages that take into account the variation of box size with latitude. It's not that I think computing averages in lon/lat space is wrong (if explained) but the graphs are hard to interpret visually. (This is a problem I have with some atlases, as well.)  Since `oce` has code to go from lon/lat space to x/y space, this can all be taken into account.

PS. of course, things are a bit easier in the S hemi; with that land in the way, we only get about a factor of 2 variation in the area of a lon-lat box, over the rough display region. Things are much worse in the N hemi, where e.g. Levitus-type atlases are quite problematic.

**Comment by AnneMTreasure** [comment] 2016-06-28 10:25
Hi @richardsc ,

Thanks so much for your comments and in-depth explanations! 

You mention you are interested in packages in R that calculate density - there is also a package I heard about the other day called [hdrcde](https://cran.r-project.org/web/packages/hdrcde/hdrcde.pdf), which uses a function `hrd.boxplot.2d()` to do a 2d boxplot. I played around with this one as well, but couldn't get it to work properly for what I wanted.

I downloaded the `woa13_decav_s00_01v2.nc` file and have gone through your code and managed to recreate the plot. Thanks; this is an excellent method to know about if I have a count of number of observations per grid cell!

I applied the second method to a subset of my data. Using your code as given, I get the following:

![datadensity_oce_plot1](https://cloud.githubusercontent.com/assets/7634887/16412217/4df96382-3d2b-11e6-9b5f-5849e5d2c27d.jpeg)


Its difficult to see much with the colour ramping. I changed the palette a bit in the call for `colormap()` by increasing the number of colours to use in `oceColorsViridis()`. This plot uses `oceColorsViridis(100)`:

![datadensity_oce_plot2](https://cloud.githubusercontent.com/assets/7634887/16411992/38433140-3d2a-11e6-9839-f5439c798ff0.jpeg)

Its easier to see, but do you think I might be losing some of the finer detail? The scale is quite big, with many grid squares with few points and just a few squares with a much larger number of points. Would a log scale for this work better?

Thanks so much for your help,
Warm regards,
Anne

**Comment by dankelley** [comment] 2016-06-28 10:47
Yes, I think you want a log10() scale, from the looks of it. There is still the converging-meridian issue, though: if you are plotting counts, then you expect smaller numbers as you approach the pole. You'd want to divide counts by the area of each lon-lat box, to get colours that will "seem right" to the eye.

**Comment by AnneMTreasure** [comment] 2016-06-28 13:37
Hi there,

Do you perhaps have any pointers of the best way to do that? 

Cheers,
Anne

**Comment by dankelley** [comment] 2016-06-28 13:44
I'd need to see your code. I normally make a new matrix that has the area, and just divide the matrices. You can also get fancy with `lapply` and so forth, but I prefer to work with matrices because then I can use `imagep` to ensure I got the matrix correct first, etc. This kind of thing comes up with coriolis, also, of course. I'm about to go in a meeting for a couple of hours ...

**Comment by AnneMTreasure** [comment] 2016-06-28 14:07
Hi Dan,

I've been looking into ways of doing this and had tried lapply. I've pasted all of the code below:

```
setwd("/Users/AnneTreasure/Documents/SealCTD")

classes = c("factor", "integer", "factor", "numeric", "numeric", "numeric", "numeric", "numeric")
datain <- read.table("cloc.csv", sep = ",", header = TRUE, colClasses = classes)

# Assign new column names to the data frame
names(datain)<-c('ref', 'Station', 'ODate', 'Long', 'Lat', 'Depth', 'Temp', 'Salinity')

# deal with dates:
Date <- strptime(datain$ODate, "%Y-%m-%d %H:%M:%S")
MonthYear <- strftime(Date, "%b/%Y")
sealCTD <- cbind.data.frame(Date, MonthYear, datain)

# rename variables for easier typing
Date <- sealCTD$Date
MonthYear <- sealCTD$MonthYear
Station <- sealCTD$Station
ref <- sealCTD$ref
Long = sealCTD$Long
Lat = sealCTD$Lat
Salinity <- sealCTD$Salinity
Temp <- sealCTD$Temp
Depth <- sealCTD$Depth

#############################

# plot data density with oce 

subsetSeal = subset(sealCTD, Depth < 7, select = c("Long", "Lat", "Depth"))  # subset for 'surface' for no. of profiles

library(oce)
data(coastlineWorld)

rlon = subsetSeal$Long
rlat = subsetSeal$Lat

## do a "2D histogram" of the lon/lat points
## for 1x1 degree boxes
b <- binCount2D(rlon, rlat, seq(-180, 180, 1), seq(-90, 90, 1))

par(mar=c(2, 2, 1, 1))

cm <- colormap(b$number, col=colorRampPalette(c('white', oceColorsViridis(11))), zlim=c(0, max(b$number)), missingColor=NA) 

par(mar=c(2, 2, 1, 1))
drawPalette(colormap=cm)

mapPlot(coastlineWorld, projection="+proj=stere +lat_0=-90", longitudelim=c(-180,180), latitudelim=c(-90,-35),col="lightgray")

mapImage(b$xmids, b$ymids, b$number, colormap=cm) # note xmids/ymids for plotting
mapPolygon(coastlineWorld, col='grey')

mapPoints(-90, -15, pch=20, cex=7, col='white')
mapText(-90, -15, "15S")

mapPoints(-90, -30, pch=20, cex=7, col='white')
mapText(-90, -30, "30S")

mapPoints(-90, -45, pch=20, cex=7, col='white')
mapText(-90, -45, "45S")
```

I also tweaked the `colorRampPalette()` in `colormap()`. This code: 
`cm <- colormap(b$number, col=colorRampPalette(c("blue", "yellow", "red"), space = "Lab"), zlim=c(0, max(b$number)), missingColor=NA)`

produced the following map:

![datadensity_oce_plot3](https://cloud.githubusercontent.com/assets/7634887/16418130/de0fcc00-3d48-11e6-90f8-b43e7f90b2bc.jpeg)

While the original color palette (`oceColorsViridis`) is visually appealing, the areas with fewer data were mostly lost with the pale colours. I will work on trying to log10 the scale. However, the list produced by `binCount2D()` is proving difficult to log, but I will persevere! 

I also created a subset of the data using only surface depths to give a number of profiles. I was originally using data from the full depth profiles, thus there were many data points per profile. This has made the scale significantly smaller as you will notice in the above image compared to the original in my previous post.

**Comment by richardsc** [comment] 2016-06-28 14:22
Hi @AnneMTreasure ,

Here's an example of how to estimate area adapted to my "ring" example above. Basically everything is the same except I calculate the area of each 1x1 degree box and then divide the number the matrices as @dankelley suggested. I also showed how you could log the normalized counts before plotting. I'm pretty sure I got the formulas from [this webpage](http://mathforum.org/library/drmath/view/63767.html)
```r
library(oce)
library(ncdf4)
data(coastlineWorld)

set.seed(123)

## Create a gaussian "ring" around antarctica
rlon <- runif(1e6)*360 - 180
rlat <- rnorm(1e6, -60, 5)
rlat[rlat < -90] <- NA # remove unphysical values

## do a "2D histogram" of the lon/lat points
## for 1x1 degree boxes
b <- binCount2D(rlon, rlat, seq(-180, 180, 1), seq(-90, 90, 1))

## Normalize counts by the area of each box, by dividing the total number of counts by area
dims <- dim(b$number)
llon <- b$xmids
llat <- b$ymids
R <- 6371
deg2rad <- pi/180
dlon <- diff(llon)[1]
dlat <- diff(llat)[1]
LON <- array(expand.grid(llon, llat)[,1], dim=dims)
LON1 <- LON - dlon/2
LON2 <- LON + dlon/2
LAT <- array(expand.grid(llon, llat)[,2], dim=dims)
LAT1 <- LAT - dlat/2
LAT2 <- LAT + dlat/2
A <- 2*pi*R^2 * abs( sin(LAT1*deg2rad) - sin(LAT2*deg2rad) ) * abs(LON1 - LON2)/360

normalizedCounts <- b$number/A*1000^2 # in counts/km^2

par(mar=c(2, 2, 1, 1))
cm <- colormap(normalizedCounts, col=colorRampPalette(c('white', oceColorsViridis(11))),
               zlim=c(0, max(normalizedCounts)), missingColor=NA)
drawPalette(colormap=cm)
mapPlot(coastlineWorld, projection='+proj=stere +lat_0=-90', col='grey',
        latitudelim=c(-30, -90),
        longitudelim=c(-180, 180))
mapImage(b$xmids, b$ymids, normalizedCounts, colormap=cm) # note xmids/ymids for plotting
mapPolygon(coastlineWorld, col='grey')
mtext('log10(Counts per square km)', adj=1)
```
![screen shot 2016-06-28 at 10 21 35](https://cloud.githubusercontent.com/assets/233584/16419004/1eca95e2-3d1a-11e6-89d4-49ee51b69452.png)

**Comment by AnneMTreasure** [comment] 2016-06-29 08:24
Hi @richardsc  and @dankelley ,

Many thanks for this code and your help. I have been banging my head against the wall for a few weeks trying to get the data density plot that I've wanted and this is really great, so thanks again!

Using your code above for the same subset of my data, I get the following plot:

![datadensity_oce_plot6](https://cloud.githubusercontent.com/assets/7634887/16445430/f3f54488-3de2-11e6-8693-a05700324a82.jpeg)

The only change I made to your code above was the `log10` bit that was missing. I changed:

`normalizedCounts <- b$number/A*1000^2 # in counts/km^2`

to

`normalizedCounts <- log10(b$number/A*1000^2) # in counts/km^2`

Thanks again! I will now use this to plot the entire data set, which is pretty big, so I can't wait to see what I get! 

Cheers,
Anne

**Comment by dankelley** [comment] 2016-06-29 09:16
Is the `/1000^2` correct? It looks to me as though the area is already in km^2, in Clark's code.  Then again, I have *very* seldom seen Clark be wrong!! In any case, I'm sure you'll be doing a "reality check" on the diagram, Anne. It's looking very nice, indeed! I assume you're using this broad scale for some other reason (e.g. other datasets) ... as of now, though, there is a lot of whitespace that might squeeze the data into a tiny portion of the "page" area, depending on the journal layout. Making the plot area be more square would be a simple step, since the white space is on left and right.  (I'm famous for hating whitespace -- a result of having poor eyes, I think.)

**Comment by AnneMTreasure** [comment] 2016-06-29 09:49
Hi Dan,

The area could already be in km^2 - @richardsc ?

There is quite a bit of white space. I'll probably also draw the map for a smaller area, say from 40 deg South, which should help a bit. I'm initially going to compare the data coverage to Argo for specific time periods. I think subtracting and comparing the `normalizedCounts` matrices produced by the above code would be a good first step for this?

**Comment by richardsc** [comment] 2016-06-29 12:11
Haha, whoops. Dan's wrong, I *often* make mistakes like that. Pretty easy to see that it's in km^2 because that's how the radius is specified.

That made me panic to look back from where I copied that code from, but luckily there I was only calculating an area-*weighted* average of a surface flux, so the units didn't matter ... Whew!

> I'm initially going to compare the data coverage to Argo for specific time periods. I think subtracting and comparing the normalizedCounts matrices produced by the above code for different data sets would be a good first step for this?

Hard to say for sure, because they represent very different modes of sampling, but it's definitely worth a try! I assume you know that it's easy to read Argo netcdf files into `argo` objects with oce?

If you think we've addressed your question, feel free to close the issue. I might blog the MEOP example (at clarkrichards.org) because it's a pretty fun dataset and a nice demonstration of `binCount2D()`.

**Comment by AnneMTreasure** [comment] 2016-06-29 12:29
Hi there,

So just to be absolutely sure, I still `*1000^2` in
`normalizedCounts <- log10(b$number/A*1000^2)` ?

I have read Argo netcdf files with `oce` and loved how easy it was! I find these files can be a pain, but `oce` made it simple!

You are welcome to blog the MEOP example.

Thanks so much for your help, I will close the issue (assuming I leave the code as is!).

Cheers,
Anne

**Comment by dankelley** [comment] 2016-06-29 12:31
I looked up the meop dataset so I could see if there was anything good in a region under study here (east of NFLD).  So I downloaded the meop dataset and looked. Oh, very very neat data. I plotted up some sections and they are so interesting I think I'll blog about them.  (Some of the data are presented as argo-type netcdf files, so `read.oce()` reads them directly.)

**Comment by AnneMTreasure** [comment] 2016-06-29 12:33
yes, MEOP is very cool! Its being added to all the time - Dr Fabien Roquet maintains and develops the database.

**Comment by richardsc** [comment] 2016-06-29 12:34
> So just to be absolutely sure, I still *1000^2 in
`normalizedCounts <- log10(b$number/A*1000^2)` ?

Nope, that should just be:
```r
normalizedCounts <- log10(b$number/A) ?
```
You might need to replace any `Inf`s created by the `log10()` with NA to get the plot to work.

Actually, this is a question for @dankelley -- what should `colormap()`/`imagep()` do if it finds `Inf` values? Spit a sensible error? Right now you'll get something like:
```
Error in image.default(x = 1, y = palette, z = matrix(palette, nrow = 1),  : 
  increasing 'x' and 'y' values expected
```

**Comment by AnneMTreasure** [comment] 2016-06-29 12:35
sorry, just reread your previous post properly. See that now!

**Comment by richardsc** [comment] 2016-06-29 12:35
I met Fabien last fall at an Argo/GO-SHIP meeting. Great guy and we talked a lot about the dataset and the work/challenges of keeping such a great database (calibration is particularly hard, given the nature of the "observation platform" 😛 )

**Comment by dankelley** [comment] 2016-06-29 12:37
Re colormap: I think it should spit a sensible error. Looks like an issue report would help ... I'd like to do the fix, given test code, because I am "in" some of this code right now, as it turns out. (I'm about to make an issue on plot(section) for some meop data ... the meop data have NAs for pressure sometimes).

**Comment by dankelley** [comment] 2016-06-29 12:40
@AnneMTreasure -- please post a comment about why reopened, so we can know what to do. Thanks!

**Comment by AnneMTreasure** [comment] 2016-06-29 12:42
sorry - I will re-close. I thought that as discussions were continuing, I would reopen. But I see the new issue you've opened, I will follow that.

Thanks again!

**Comment by dankelley** [comment] 2016-06-29 12:58
Anne, no worries. We just try to close issues when they (as described by the title or the first comment) have been addressed.  (Generally we go by the title alone, but in this case the title is very open-ended.) Discussion quite often carries on after issues are closed -- the point of closing is that other users do not need to see the issue in the list anymore.

**Comment by richardsc** [comment] 2016-06-29 13:23
> Re colormap: I think it should spit a sensible error. Looks like an issue report would help ... 
@dankelley -- ignore my comment about the `Inf` error. I think it was actually something that I was doing in trying to manually set the limits of the colormap.

**Comment by AnneMTreasure** [comment] 2016-06-30 08:40
Hi there,

After running the code without the `1000^2`, I do get the error message:

```
Error in image.default(x = 1, y = palette, z = matrix(palette, nrow = 1),  : 
  increasing 'x' and 'y' values expected
```

because of the `Inf`s created by the `log10()`. How would I tell `colormap()` to replace these with NAs?

Thanks!

**Comment by dankelley** [comment] 2016-06-30 09:59
Clark may have in idea because he has been following this closely, but I would need to see the code and data to make any progress in this.  I don't see how a scale factor will lead to an `Inf` from `log10`. I do see how you can get a `-Inf` from `log10(x)` if `x==0`, but a scale factor won't make a zero from a nonzero number.

On a related note, count data typically need to be zero-shifted (use e.g. `log10(1+count)` if `count` could be zero), but I'm sure you did that from the start.

Thanks for pointing this out, Anne, because we definitely don't want error messages under any conditions, and this is a low-level message that can be confusing to the user, so we want to "catch" the condition within `oce` and give a more useful error message that relates to the user's data. (The error is likely coming from a failure to autoscale the `z` values, or something.)

**Comment by richardsc** [comment] 2016-06-30 14:26
Hi @AnneMTreasure 

It would be helpful to see the code you're using. I ran into a [similar issue](https://github.com/dankelley/oce/issues/1000#issuecomment-229354155), but decided that it was user error rather than a bug with colormap. In one of my earlier examples, I fixed it by doing something like:
```r
logN <- log10(N)
logN[is.infinite(logN)] <- NA  # remove any -Inf values which cause problems with plotting
```
but again seeing your code would be best.

@dankelley I wonder if the creation of `Inf` after multiplication by a scale factor is somehow a floating point thing?

**Comment by dankelley** [comment] 2016-06-30 14:34
I'm reopening this because we have new items to consider, although (as usual) I think it will be up to Anne to close it, when/if we come up with a solution to this latest problem. Also, I think `develop` commit 55b523eb63fb97767091cde1686a45d619d0d531 has a chance of fixing this (I added `na.rm=TRUE` arguments to some of the `range()` calls).

**Comment by dankelley** [comment] 2016-06-30 14:35
@richardsc I don't quite see how the `Inf` can be a floating point thing because a factor of a million is not much (on a many-byte computer), but the only way to know is to see code and drill down to find where this is happening.

**Comment by richardsc** [comment] 2016-06-30 14:42
I think the problem here is indeed coming from the fact that some cells have a "count" of zero, and then taking `log10(count)` produces `-Inf` which causes `colormap()` to barf like:
```r
> colormap(log10(0:10))
Error in seq.default(min(zlim, na.rm = TRUE), max(zlim, na.rm = TRUE),  : 
  'from' cannot be NA, NaN or infinite
```

So, is that a problem with colormap, or should it simply try and catch such cases (Infs) and spit an error that is more helpful?

**Comment by dankelley** [comment] 2016-06-30 14:55
I think it should do `range` just of the finite values. I'll fix it.

**Comment by dankelley** [comment] 2016-06-30 14:57
I just tweaked `develop` in commit 8fb5ca72896a9ac0ec5f45c3703802335b73b580 to look only at finite `z` values. Seem okay, Clark?

**Comment by AnneMTreasure** [comment] 2016-06-30 18:44
Hi there,

I've run code with zero-shifting the data: 

```
library(oce)
data(coastlineWorld)

rlon = subsetSeal$Long
rlat = subsetSeal$Lat

## do a "2D histogram" of the lon/lat points for 1x1 degree boxes
b <- binCount2D(rlon, rlat, seq(-180, 180, 1), seq(-90, 90, 1))

## Normalize counts by the area of each box, by dividing the total number of counts by area
dims <- dim(b$number)
llon <- b$xmids
llat <- b$ymids
R <- 6371  # radius of the earth in km
deg2rad <- pi/180
dlon <- diff(llon)[1]
dlat <- diff(llat)[1]
LON <- array(expand.grid(llon, llat)[,1], dim=dims)
LON1 <- LON - dlon/2
LON2 <- LON + dlon/2
LAT <- array(expand.grid(llon, llat)[,2], dim=dims)
LAT1 <- LAT - dlat/2
LAT2 <- LAT + dlat/2
A <- 2*pi*R^2 * abs( sin(LAT1*deg2rad) - sin(LAT2*deg2rad) ) * abs(LON1 - LON2)/360

normalizedCounts <- log10(1+(b$number/A)) 

par(mar=c(2, 2, 1, 1))

cm <- colormap(normalizedCounts, col=colorRampPalette(c('white', oceColorsViridis(11))), zlim=c(0, max(normalizedCounts)), missingColor=NA)

drawPalette(colormap=cm)

mapPlot(coastlineWorld, projection="+proj=stere +lat_0=-90", longitudelim=c(-180,180), latitudelim=c(-90,-40),col="lightgray")

mapImage(b$xmids, b$ymids, normalizedCounts, colormap=cm) # note xmids/ymids for plotting
mapPolygon(coastlineWorld, col='grey')
mtext('log10(Counts per square km)', adj=1)
```

It draws the plot; however, I end up with the same plot I had above, with the colour ramping making it difficult to see and most of the data is 'lost':


![zero shift data](https://cloud.githubusercontent.com/assets/7634887/16499858/668b332a-3f02-11e6-8ceb-681a25a0e0e6.png)

Using the method that @richardsc suggests above:
Instead of:
`normalizedCounts <- log10(1+(b$number/A))`
I tried:
`normalizedCounts <- log10(b$number/A)`
`normalizedCounts[is.infinite(normalizedCounts)] <- NA`


After the call for `drawPalette(colormap=cm)`, I get the error message:
```
Error in seq.default(zlim[1], zlim[2], length.out = PLEN) : 
  'to' cannot be NA, NaN or infinite
```

**Comment by richardsc** [comment] 2016-07-01 03:43
Hi @AnneMTreasure . Did you try building oce from source to use the fix that @dankelley just added in commit 8fb5ca7 to see if it fixes the problem?

**Comment by AnneMTreasure** [comment] 2016-07-01 09:24
Hi @richardsc 

I've just tried that, and reran all the code, but got exactly the same outcome. For building `oce` from source - I downloaded the `oce` .tar.gz file from cran (does this include the latest fix?), and ran the following code:
`install.packages("/Users/anne/Desktop/oce_0.9-18.tar.gz", repos = NULL, type="source")`

Is this correct?

Thanks so much,

**Comment by dankelley** [comment] 2016-07-01 10:27
Below is how to rebuild from the 'develop' source. CRAN only gets updated once a year or so. The steps given below yield the latest version, which might be only seconds old.
```R
library(devtools)
install_github("dankelley/oce", ref="develop")
```

**Comment by AnneMTreasure** [comment] 2016-07-01 18:33
Hi @dankelley 

Thanks for that. I wondered! Sorry to take so long to get back to you; our internet has been down today.

I ran the code you provided:

```
library(devtools)
install_github("dankelley/oce", ref="develop")
```

which worked, but when I reran the plotting code, I get the same error message as before when running 

```
> normalizedCounts <- log10(b$number/A)
> normalizedCounts[is.infinite(normalizedCounts)] <- NA
```

i.e.:

```
> drawPalette(colormap=cm)
Error in seq.default(zlim[1], zlim[2], length.out = PLEN) : 
  'to' cannot be NA, NaN or infinite
```

**Comment by dankelley** [comment] 2016-07-01 18:47
Hi Anne. First, Happy Canada Day!!!

Second, can you email me your data? An easy way is to do e.g.
```R
save(subsetSeal, file="subsetSeal.rda")
```
and then email me the resultant file `subsetSeal.rda` to dan.kelley@dal.ca and I'll have a look. It will be a lot easier and faster if I can reproduce your error locally. You should send the exact `.R` file you are using, in the same email, so we can be sure we are in-synch. 

I don't imagine it will be hard for me to fix the problem, once I can see it happening here.  I will be offline for 2 hours starting now.

Thanks!

**Comment by AnneMTreasure** [comment] 2016-07-01 19:16
Hi @dankelley 

I've sent you an email with the data.

Thanks!
Anne

**Comment by dankelley** [comment] 2016-07-01 21:19
Anne, thanks for sending the data.  I think the problem is that you're doing
```R
cm <- colormap(normalizedCounts, col=colorRampPalette(c('white', oceColorsViridis(11))),
    zlim=c(0, max(normalizedCounts, na.rm=TRUE)), missingColor=NA)
```
but these are logged values we are talking about here, and the max is in fact less than zero. So your `zlim` is reversed. I'll make oce handle that, but I really think you want to use
```R
cm <- colormap(normalizedCounts, col=colorRampPalette(c('white', oceColorsViridis(11))),
               missingColor=NA)
```
or at least something in which you've set up your `zlim` to be in order. By the way, with the code as immediately above, I get as follows:
<img width="680" alt="screen shot 2016-07-01 at 6 19 32 pm" src="https://cloud.githubusercontent.com/assets/99469/16534719/65311f24-3fb8-11e6-95ab-017396facbbd.png">

**Comment by AnneMTreasure** [comment] 2016-07-02 06:23
Hi Dan,

Thanks so much. I've run the code and produced the same plot:

![inf values removed](https://cloud.githubusercontent.com/assets/7634887/16538669/997de0d2-402b-11e6-8cd4-29788ddc8215.png)

which is looking much better than the previous ones.

Thanks so much for your help!

**Closed** 2016-07-02 09:28 UTC
Labels: advice:programming, graphics
