### ISSUE TITLE
Selecting velocity magnitude and direction and average echo amplitude from ADCP data

### ISSUE THREAD

**Issue by shaalboom** [dankelley/oce#1308] opened 2017-10-11 13:23 UTC
### Short summary of problem
*I'm currently working on my ADCP data, but I don't seem to be able to plot the velocity magnitude, the velocity direction and echo amplitude average.*

### Details (optional)

* In winADCP these are listed as data types as well, and I can also export them. But when opening my original datafile in R using the read.adp.rdi command (we are using rdi instruments) I can't find the magnitude and direction any longer. The coordinates are in enu, so I can find the east, north and up velocity, but I would like to have the magnitude and direction as plotted in winADCP. The same accounts for the echo amplitude, which I can plot for all individual beams, but not for the average. I hope you can help me with this.* 
![winadcp](https://user-images.githubusercontent.com/32707237/31442345-6755fb00-ae96-11e7-800d-dc9f01c6ce93.png)

### What you did

*require(oce)

ST2 <- read.adp.rdi("ADCP_2.000")

t <- ST2[['time']]
d <- ST2[['distance']]

eastward <- ST2[['v']][,,1]
northward <- ST2[['v']][,,2]
upward <- ST2[['v']][,,3]
error <- ST2[['v']][,,4]

par(mfrow = c(4,1))
imagep(t, d, eastward, missingColor = 'gray', flipy = TRUE, zlab = "eastward")
imagep(t, d, northward, missingColor = 'gray', flipy = TRUE, zlab = "northward")
imagep(t, d, upward, missingColor = 'gray', flipy = TRUE, zlab = "upward")
imagep(t, d, error, missingColor = 'gray', flipy = TRUE, zlab = "error")

EAA_beam1 <- ST2[['a', 'numeric']][,,1]    
EAA_beam2 <- ST2[['a', 'numeric']][,,2]    
EAA_beam3 <- ST2[['a', 'numeric']][,,3]
EAA_beam4 <- ST2[['a', 'numeric']][,,4]

par(mfrow = c(4,1))
imagep(t, d, EAA_beam1, missingColor = 'gray', flipy = TRUE, decimate = FALSE, zlab = "beam1")
imagep(t, d, EAA_beam2, missingColor = 'gray', flipy = TRUE, decimate = FALSE, zlab = "beam2")
imagep(t, d, EAA_beam3, missingColor = 'gray', flipy = TRUE, decimate = FALSE, zlab = "beam3")
imagep(t, d, EAA_beam4, missingColor = 'gray', flipy = TRUE, decimate = FALSE, zlab = "beam4")*

![enuvelocity](https://user-images.githubusercontent.com/32707237/31442675-6cf1482a-ae97-11e7-9aac-cf4390950f58.png)
![enueea](https://user-images.githubusercontent.com/32707237/31442682-711be838-ae97-11e7-869d-a994e65cbd96.png)

### How urgent is this?

*It can wait for a couple of days*

### Output from sessionInfo()

*Replace this line with the output from sessionInfo().*

**Comment by richardsc** [comment] 2017-10-11 16:19
Hi @shaalboom. That's a nice set of plots -- it looks like you're gaining some good skills with oce!

I haven't yet looked at your data (though @dankelley did send a copy to me as well), but the issue that you are reporting is simply due to the fact that the options in WinADCP for magnitude, direction, and averaged backscatter are *derived* fields that are not contained in the raw data file. In other words, to plot (and allow export) of those fields in WinADCP, it is doing the necessary calculations in the background.

Therefore, the solution to be able to plot those fields, or to add them to your own `adp` objects, is similarly to calculate them yourself in R. I think it would be of most benefit to you if I leave it as an exercise, but I will give you a couple of hints:

1. Converting from east/north velocities (e.g. u/v) to magnitude/direction is a trigonometric conversion. Pythagoras for the magnitude and `atan2()` (arctan) for the direction (note that `atan2()` returns *radians*).

2. The most efficient way to apply a function across a dimension of a matrix in R is to use the aptly named `apply()` function. See `?apply` for the arguments, etc. For example to find the column means (the 2nd dimension) of a 2D matrix you would do
    ```r     
    column_mean <- apply(mat, 2, mean)  # the "2" indicates the direction to apply
    ```
    For a 3D matrix, you can apply across the 3rd dimension by doing
    ```r
    mean <- apply(mat, c(1, 2), mean)
    ```

Hope that helps, and please post your results back here!

**Comment by shaalboom** [comment] 2017-10-12 06:36
Thanks a lot for your quick response and for the hints. I will have a look at it and I will post my results back here.

**Comment by shaalboom** [comment] 2017-10-12 09:40
I've got some results, however, I didn't get the apply command working (as I will show below)
This is the code I used together with the figures I got.


```
require(oce)
ST2 <- read.adp.rdi("ADCP_2.000")
t <- ST2[['time']]
d <- ST2[['distance']]

eastward <- ST2[['v']][,,1]          
northward <- ST2[['v']][,,2]         

EAA_beam1 <- ST2[['a', 'numeric']][,,1]   
EAA_beam2 <- ST2[['a', 'numeric']][,,2]   
EAA_beam3 <- ST2[['a', 'numeric']][,,3]
EAA_beam4 <- ST2[['a', 'numeric']][,,4]

# Direction (degrees from north) 
rad2deg <- function(rad) {(rad * 180) / (pi)}

dirr <- atan2(eastward, northward)
dir <- rad2deg(dirr)
par(mfrow = c(1,1))
imagep(t, d, dir, missingColor = 'gray', flipy = TRUE, zlab = "Direction", decimate = FALSE) 
```

![rplot](https://user-images.githubusercontent.com/32707237/31489440-eebdf7a0-af40-11e7-8e58-4dedfbb9ab77.png)


```
par(mfrow = c(2,1))
plot(t, dir[,01], type = "l", xlab = "Date", ylim = c(-180, 180), 
     ylab = "current direction [degrees from north]", main = 'Bin 1')          # select 1st bin
plot(t, dir[,69], type = "l", xlab = "Date", ylim = c(-180, 180), 
     ylab = "current direction [degrees from north]", main = 'Bin 69')         # select 69th bin
```
![dir_bin1_69](https://user-images.githubusercontent.com/32707237/31489542-44ffdac0-af41-11e7-80bf-edfd2b569c6c.png)

I also tried to use the apply command, but when I ran the second line I got the notion: "Error in apply(ST2, 2, dirf): dim(X) must have a positive length

```
dirf <- function() {(atan2(eastward, northward))}
dirr <- apply(ST2, 2, dirf)       #Error in apply(ST2, 2, dirf) : dim(X) must have a positive length
dir <- rad2deg(dirr)
```

```
# Magnitude 
mag <- sqrt(eastward^2 + northward^2)
par(mfrow = c(1,1))
imagep(t, d, mag, missingColor = 'gray', flipy = TRUE, zlab = "Magnitude", decimate = FALSE, 
       zlim = c(0, 1))
```

![magnitude](https://user-images.githubusercontent.com/32707237/31489636-983e6a3a-af41-11e7-9f8d-2f0002f03e02.png)

```
par(mfrow = c(2,1))
plot(t, mag[,01], type = "l", ylim = c(0, 0.6),
     xlab = "Date", ylab = "current speed [m/s]", main = 'Bin 1')          # select 1st bin
plot(t, mag[,69], type = "l", ylim = c(0, 0.6),
     xlab = "Date", ylab = "current speed [m/s]", main = 'Bin 69')         # select 69th bin
```

![magnitude_bin1_69](https://user-images.githubusercontent.com/32707237/31489648-9f9e581c-af41-11e7-921f-fbac7662687e.png)

```
# Echo amplitude average
EAA <- (EAA_beam1 + EAA_beam2 + EAA_beam3 + EAA_beam4)/4
par(mfrow = c(1,1))
imagep(t, d, EAA, missingColor = 'gray', flipy = TRUE, decimate = FALSE, zlab = "Echo amplitude")
```
![eaa](https://user-images.githubusercontent.com/32707237/31489657-ae631d2e-af41-11e7-8ddf-9bd63f968740.png)

**Comment by dankelley** [comment] 2017-10-12 11:26
I've not read your code in detail but I wonder if you might want to do
```r
E <- apply(eastward, 1, mean, na.rm=TRUE)
N <- apply(northward, 1, mean, na.rm=TRUE)
amp <- sqrt(E^2+N^2)
dir <- atan2(N, E) * 180 / pi
oce.plot.ts(ST2[['time']], amp)
oce.plot.ts(ST2[['time']], dir)
```
note the use of `na.rm` here, which gets passed to `mean`. 

It's not clear to me that depth-averaging the data makes a lot of sense, though; you might want to trim to just the portion that is not messed up by noise or artifacts. And, even when you do that, you may want to consider other options in addition to a simple mean ... what makes sense depends very much on your purpose, of course, so I won't make suggestions.

Looking at the data, I'd guess that you will want also to trim in time. But at least now, you've got the tools to look at the data, and can make choices based on scientific considerations.

**Comment by dankelley** [comment] 2017-10-12 11:28
PS. the angle I computed above is not in the geographical convention (usually, degrees clockwise of North) but you'll know immediately how to fix that, I'm sure.

**Comment by shaalboom** [comment] 2017-10-12 12:17
Depth-averaging the data doesn't make sense indeed, that's not what I'm trying to do, but thanks, it helps in understanding the code better. Trimming the data is indeed something that hasn't been applied to the above data yet. I just finished doing that. 


```
t <- ST2[['time']]
ts <- ST2[['time']][175 : 12895]      # setting time from 12.00 (14-05) to 08.00 (23-05)
d <- ST2[['distance']]
ds <- ST2[['distance']][1:69]         # selecting bin 1 to 69
imagep(ts, ds, dir[175:12895, 1:69], missingColor = 'gray', flipy = TRUE, zlab = "Direction", decimate = FALSE)

plot(ts, dir[175:12895 , 01], type = "l", xlab = "Date", ylim = c(-180, 180), 
     ylab = "current direction [degrees from north]", main = 'Bin 1')          # select 1st bin
plot(ts, dir[175:12895 , 69], type = "l", xlab = "Date", ylim = c(-180, 180), 
     ylab = "current direction [degrees from north]", main = 'Bin 69')         # select 69th bin
```
Above code removed the time during which the mooring was deployed and when it got back up and the interactions with the seabed have been removed by selecting the upper bins.

**Comment by richardsc** [comment] 2017-10-12 13:33
Yeah, the issue isn't about averaging in depth, but rather averaging the backscatter across all four beams. Below I'll discuss a few points from your code and then give you some pointers to do what you want.

1. Nice attempt to use `apply()` for the direction calculation! I took me a long time to really become comfortable with `apply()` especially coming from the more "matlab" way of doing things, and it can be tricky to master. A couple points
    * the first argument has to be a matrix, rather than an oce object. So if you want to use apply on, say, the velocity you have to specify that in the argument, like:
    ```r
    d <- apply(ST2[['v']], ...)
    ```
    * because apply works on a single array, I'm not sure how to use it with a function like your `dirf()` which needs **two** arguments. I'm going to think on that one some more, because I hadn't even thought of doing direction like that ...

2. To trim the object, you should take advantage of the `adp` methods for the generic `subset()` function, E.g.:
    ```r
    ST2 <- read.adp.rdi("ADCP_2.000")
    ## subset the data in time and depth
    focus <- as.POSIXct(c('2017-05-14 12:00:00', '2017-05-23 08:00:00'), tz='UTC')
    dmax <- 364
    ST2 <- subset(ST2, distance < dmax)
    ST2 <- subset(ST2, focus[1] <= time & time <= focus[2])
    ```
    I find that's a lot nicer than manually specifying indices, and you'll notice that it trims the *entire* object (not just the fields you've extracted).

3. You can easily use the `apply()` function to get the averaged backscatter (though your manual method works just fine!). I would do it like this:
    ```r
    bavg <- apply(ST2[['a', 'numeric']], c(1, 2), mean, na.rm=TRUE)
    imagep(t, d, bavg)
    ```
    ![image](https://user-images.githubusercontent.com/233584/31498420-409fbf1c-af38-11e7-9590-a7dc28574036.png)

    Some details on what I did there:
    * you can access the 3D backscatter array directly for the `apply()` call with `ST2[['a', 'numeric']]`
    * the second argument for apply is where you specify the dimensions that you want to **keep**. So, to average across the four beams, we want to keep the `time` and `distance` dimensions, so the argument is `c(1, 2)`.
    * here is the function we want to "apply"
    * as @dankelley pointed out, this is where you can specify optional arguments for the function you are applying. In this case I want it to ignore NAs

Hope that helps!

**Comment by dankelley** [comment] 2017-10-14 14:02
@shaalboom If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Closed** 2017-10-16 06:03 UTC
Labels: adp, advice:programming, advice:science, good first issue, help wanted

**Comment by richardsc** [comment] 2017-10-16 11:53
Thanks for closing @shaalboom . Did the above help you achieve what you wanted?

**Comment by shaalboom** [comment] 2017-10-16 11:57
Yes it did, thanks a lot for your help!
