### ISSUE TITLE
Unexpected straight lines presents when using mapContour and mapDirectionfield

### ISSUE THREAD

**Issue by Hooke-Z** [dankelley/oce#1692] opened 2020-05-06 03:14 UTC
*Instructions: use this template, if it seems appropriate. For example, it only
applies to bug reports, so if you are suggesting a new feature, you should just
delete all the contents and write whatever you would like to write. If you have
private data that are required for your example, you may email them to the
developers, who will pledge to not to share them. Please delete this block
before submitting the issue.*

### Short summary of problem

Unexpected lines come out when using the mapContour and mapDirectionfield. The number of the lines increases the "levels" and "scale" in the two functions.

Code used:
mapPlot(coastlineWorld, projection="+proj=merc", col='grey',
        latitudelim=c(-40, 0),
        longitudelim=c(-15, 25),clip = TRUE)
mapImage(lon, lat, z=SLA, zlim=Zlim,colormap=cm,filledContour = TRUE)#
mapPolygon(coastlineWorld, col='grey')
mapContour(longitude = lon,
           latitude = lat, 
           z = SLA, 
           levels =  seq(-10,10,1),
           col = "black",
           lwd = .5,lty = 1,underlay = "erase")
![image](https://user-images.githubusercontent.com/64881340/81135434-29245e80-8f26-11ea-80e3-5134e6f86bde.png)

**Comment by dankelley** [comment] 2020-05-06 08:58
Thanks for the report.

My first step in looking at this will be to try to reproduce the error.

It would help if you provided a complete example.  (That means every step, including `library(oce)` and so forth.)  Of course, I'd also need data; you can email data to kelley.dan@gmail.com, or provide a file over dropbox.

Also, please post the output from `sessionInfo()`, so we can know more about your system.

Finally, you will need to be set up to build packages (which includes having a C compiler, etc.) if this turns out to be a bug that we will try to fix in the development version.  (Updates to CRAN are necessarily infrequent, according to CRAN policy.)

**Comment by Hooke-Z** [comment] 2020-05-06 20:57
Thanks for your reply. Here is the output from sessionInfo(). I send the data and code to your Gmail address. 
![image](https://user-images.githubusercontent.com/64881340/81227567-9da8dd00-8fba-11ea-95d2-938c126aa2f2.png)

**Comment by Hooke-Z** [comment] 2020-05-06 21:04
Dr. Dankelley,

Here are the code and data (https://drive.google.com/open?id=1ZE9GsPFKDuu-6OGtZTymR7NKyU_qUDgp <https://drive.google.com/open?id=1ZE9GsPFKDuu-6OGtZTymR7NKyU_qUDgp>). IF you need anything more, please let me know.

Thanks,

Hooke

**Comment by dankelley** [comment] 2020-05-07 09:34
Since you sent your data and code via GH, they are *de facto* public, so I am posting a solution below.  Note that I have pared-down the code, removing things unrelated to the issue at hand; thus, for example, I removed your specifications of margins, your drawing of the palette, your drawing of many contours, etc.

Please note 4 things:
1. The problem is that your longitudes are in (0,360)-range format, but the map functions require (-180,180) format.  I solve that in BLOCK 1.
2. You are plotting the whole world, which is very slow.  Therefore, I trimmed to your plot region, plus a bit more, in BLOCK 2.
3. To test whether BLOCK 1 and 2 worked, I have a test in BLOCK 3; this gets run if `test` is set to `TRUE` at the start of the file.
4. Other mods to your code include casting `lon` and `lat` to vectors, focussing on just a single level that showed the error, and removing some arguments that are no needed to demonstrate the problem.

Please let us know whether this works. On my machine, the bug disappears, and also it runs **much** faster.
```R
test <- !TRUE
library(ncdf4) 
library(oce)
data(coastlineWorld)
data<-nc_open("MSL.nc")
SLA<-ncvar_get(data,attributes(data$var)$names[1])
lat<-as.vector(ncvar_get(data, attributes(data$dim)$names[2]))
lon<-as.vector(ncvar_get(data, attributes(data$dim)$names[1]))
Zlim = c(-10,10)
cm <- colormap(SLA, col=oceColorsJet, breaks=seq(-10, 10, 0.25),missingColor = NA)

# BLOCK 1
# Put lon into -180 to 180 format
LON <- lon
lon <- ifelse(lon > 180, lon-360, lon)
o <- order(lon)
lon <- lon[o]
SLA <- SLA[o,]

# BLOCK 2
# Trim to plot region for speed
lonKeep <- -30 <= lon & lon <= 30
latKeep <- -50 <= lat & lat <= 10
lon <- lon[lonKeep]
lat <- lat[latKeep]
SLA <- SLA[lonKeep, latKeep]

# BLOCK 3
# Test without the complex map and colour details
if (test) {
    contour(lon,lat,SLA)
    stop()
}

mapPlot(coastlineWorld, projection="+proj=merc", col='grey',
        latitudelim=c(-40, 0),
        longitudelim=c(-15, 25),clip = TRUE)
mapImage(lon, lat, z=SLA, zlim=Zlim,colormap=cm,filledContour = TRUE)
mapPolygon(coastlineWorld, col='grey')
mapContour(longitude = lon,
           latitude = lat, 
           z = SLA, 
           levels =  5,
           underlay = "erase")
```

**Comment by Hooke-Z** [comment] 2020-05-07 20:11
Dr. Dan Kelley,
Thanks so much. Your way works well.
best,
Hooke-Z

**Comment by dankelley** [comment] 2020-05-07 21:45
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Closed** 2020-05-07 22:18 UTC
Labels: advice:programming
