### ISSUE TITLE
issues with read.odf()

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#768] opened 2015-10-28 14:58 UTC
I'm having issues with an ODF file. When I read the file using read.odf(), the first value in each @data variable is '%10.3f' or something along those lines.I looked at the file and didn't see anything out of the ordinary. This is the only file I've had this issue, its data from a microCAT instrument. I've attached a screenshot when I do a str() of the file when I read it in, as well as when I try to plot pressure. I can send data file in a separate e-mail. 

I thought it might have been due to my version of 'oce', but I re-installed it on my windows machine (can't on my macbook right now) to see if it would make a difference, but it didn't.
![capture](https://cloud.githubusercontent.com/assets/3463161/10792281/d24fdbe2-7d6a-11e5-84de-376f24811f35.PNG)

**Comment by richardsc** [comment] 2015-10-28 15:25
I know @dankelley will pop in on this, but when you say `oce` version, is that from CRAN or built from the `develop` branch? What is the output from `systemInfo()`?

The `%10.3f` is a format string, and since I don't see such specifications in the source for `read.odf()` it must be coming from the file.

**Comment by dankelley** [comment] 2015-10-28 15:33
I can reproduce your error. This is a big file! I'll look later today or this evening.

**Comment by dankelley** [comment] 2015-10-28 15:37
The problem is that the last line in the file is giving formats. I think this is an improper ODF file. I read the last two lines as below.  (I will look into a good way to avoid such lines, which should be a simple grep operation, maybe just not permitting any line with a ``%.*f`` pattern).
```
3.76560    764.119 '10-JUL-2014 15:40:00.00'   0.759535     34.888      3.711     27.727
 %8.5f %10.3f '%s' %10.6f %10.3f %10.3f %10.3f
```

**Comment by dankelley** [comment] 2015-10-28 15:40
@clayton33 -- can you retry with the ``develop`` branch? I put in a fix that should make it work now.

**Comment by richardsc** [comment] 2015-10-28 15:53
Yup, weird looking file. 

As an aside, it isn't actually the *first* value that has the format string, but the *last* one. When you do `str(d@datda)` you can see that R decided that the columns should be "factors", and the listing you get is a summary of the different "factor" levels rather than what would be returned by `head()`, e.g.
```r
head(d@data[['temperature']])
[1] 3.85270 3.85610 3.86010 3.85780 3.86000 3.86140
5629 Levels: %8.5f 3.47630 3.47800 3.47840 3.47940 3.47990 3.48030 ... 4.25810
```

I saw a twitter post one time that said something like:

> I've figured out my gravestone inscription: "stringsAsFactors=FALSE"

**Comment by dankelley** [comment] 2015-10-28 16:48
I checked, and using a textConnection doesn't help; FYI my test (not committed to code) was
```R
con <- textConnection(lines) 
print(system.time( data <- read.table(con, skip=dataStart)))
  ```

**Comment by dankelley** [comment] 2015-10-28 16:58
Given the off-web communication, I don't feel that this is a bug ... perhaps @clayton33 could close the issue, if agreed.

**Closed** 2015-10-28 17:17 UTC
Labels: ODF
