### ISSUE TITLE
Read all relevant RSK metadata

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#850] opened 2016-02-02 11:40 UTC
Mostly copied from #762, so that it can be closed for the next release, but to keep a list of future things to add to rsk support:
- [ ] details of the sampling schedule (e.g. continuous vs averaged, gating condition, ...)
- [ ] read `bursts` data from waves-enabled instruments
- [ ] `events` table, specifically the auto-detection of upcasts and downcasts

Low priority fixes:
- [ ] `offsetfromUTC` parameter (only in newest version of firmware)
- [ ] handle "iOS" format RSK files (which are slightly different from regular RSK files)
- [ ] handle new text export format (multiple file zip archive with JSON metadata)

**Comment by dankelley** [comment] 2016-05-02 22:08
Clark, I feel this should not be tagged "Next Release", because it's got 6 action items with none ticked off ... and it's been inactive for several months. Since you're assigned, I think it's up to you to decide on the label, though. (I see other rsk things tagged 'next release'...)

**Comment by richardsc** [comment] 2016-05-03 03:35
Agreed. This has become lower priority from some bigger data structure overhauls. Removing the tag (but keeping open).

**Comment by dankelley** [comment] 2017-07-12 23:13
@richardsc this issue has been stagnant for over a year, and I wonder whether it should be replaced by individual issues ("please handle X in read.rsk"), as reported by users who need those "X" things for their work.  That way, we could chip away at the problem, not out of some desire for completeness, but rather to help users in their work.  Up to you, though, since the issue is assigned to you, and you're the reporter!

**Comment by dankelley** [comment] 2017-07-13 19:41
I'm closing this, as agreed at our f2f discussion today. To other RSK users, this does not mean that the intention to improve RSK functionality has diminished ... please feel free to post individual issues on individual needs, and to expect us to devote our attention to them, as appropriate.

**Closed by dankelley** 2017-07-13 19:41 UTC
Labels: I/O, rsk
