### ISSUE TITLE
proj4 plots aren't always centered in the axis

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#539] opened 2014-11-03 01:48 UTC
I noticed this in the animated gif from issue #538. Here is the code that made the images used for the animation:

``` splus
library(oce)
data(coastlineWorldFine)
png('test-%03d.png', type='cairo')
for (lon in seq(179, -179, -10)) {
  par(mar=rep(0, 4), bg=NA)
  p <- paste('+proj=ortho +lat_0=30 +lon_0=', lon, sep='')
  mapPlot(coastlineWorldFine, projection=p)
  mapImage(topoWorld, colormap=cm)
  mapLines(coastlineWorldFine)
}
 dev.off()
```

which produces this wobbly globe:
![](https://cloud.githubusercontent.com/assets/233584/4877901/da556360-62fa-11e4-86bb-10ca840b27da.gif)

**Comment by dankelley** [comment] 2017-08-15 12:49
I'm reopening this as a sort of to-do item, since I'm altering code for #1282 and it can impinge on this because now I want to permit `type="polygon"` for `mapPlot` (as I have done, in `develop`, not yet pushed, for `plot,coastline-method`)

**Comment by dankelley** [comment] 2017-11-10 10:56
I came across this while looking for stale issues that could be cleaned up.  I've not read the code in the issues test for this, but the results are weird because of retracing, e.g. 5389A-030.png is below. I'll look into this within a few weeks.

![539a-030](https://user-images.githubusercontent.com/99469/32655500-23c0a9c0-c5e4-11e7-824c-df176d20eead.png)

**Comment by dankelley** [comment] 2017-11-25 13:13
The overdrawing problem mentioned in the previous comment is caused by the use of `par(..., bg=NA)`, which causes a `new=FALSE` declaration. It's thus an expected effect of the test code (and one that I've changed in that test code) so I'm closing this.

**Closed by dankelley** 2017-11-25 13:13 UTC
Labels: mapping
