### ISSUE TITLE
Unable to import .odf file using read.odf

### ISSUE THREAD

**Issue by danielgboyce** [dankelley/oce#1348] opened 2017-12-11 13:38 UTC
I recently ran into a problem while trying to import temperature climatology files downloaded from the DFO's Atlantic Zone Monitoring Program (AZMP) using read.odf. A subset of the individual data files can be accessed here:
http://www.meds-sdmm.dfo-mpo.gc.ca/isdm-gdsi/azmp-pmza/climat/sst-tsm/costal-cotieres-eng.htm

The files contain temperature data sampled at a single depth. When trying to import them I get the following error:
Error in abs(res@data$pressure) : 
  non-numeric argument to mathematical function

For some reason, the function seems to be looking for a pressure field and of course is not finding it (because it's not there).  It wasn't a huge issue, since I was able to import the file using read.table, but it would have been much easier if read.odf was able to accomplish it.

**Comment by richardsc** [comment] 2017-12-11 13:43
Thanks for the report @danielgboyce . I can confirm I see the issue trying to load the following file:

http://www.meds-sdmm.dfo-mpo.gc.ca/alphapro/zmp/Climate/CoastalSST/odf_data_files/Halifax_SST.odf

We'll take a look.

**Comment by richardsc** [comment] 2017-12-11 13:46
@dankelley the issue seems to be coming from lines 1113 to 1118 in `odf.R`:
```r
## Return to water depth issue. In a BIO file, I found that the missing-value code was
    ## -99, but that a SOUNDING was given as -99.9, so this is an extra check.
    if (is.na(waterDepth) || waterDepth < 0) {
        res@metadata$waterDepth <- max(abs(res@data$pressure), na.rm=TRUE)
        warning("estimating waterDepth from maximum pressure")
    }
```

**Comment by richardsc** [comment] 2017-12-11 13:58
I've fixed the reading by doing as below (not committed yet):
```r
    if (is.na(waterDepth) || waterDepth < 0) {
        if ('pressure' %in% names(res@data)) {
            res@metadata$waterDepth <- max(abs(res@data$pressure), na.rm=TRUE)
            warning("estimating waterDepth from maximum pressure")
        }
    }
```
but now I'm seeing an issue where an `odf` object with a single data type (other than time) isn't plotting properly:
```r
> plot(d)
 Show Traceback
 
 Rerun with Debug
 Error in par(mfrow = c(n - 1, 1)) : 
  invalid value specified for graphical parameter "mfrow" 
```
So I'm looking into that now

**Comment by richardsc** [comment] 2017-12-11 14:25
The issue here seems to be an `n-1` error at lines 175-177:
```r
                      } else {
                          par(mfrow=c(n-1, 1))
                      }
```
because `n` is built up to already *not* include time (if it exists). Changing this to 
```r
                      } else {
                          par(mfrow=c(n, 1))
                      }
```
Should fix this. Will commit and push shortly.

**Comment by richardsc** [comment] 2017-12-11 14:29
@danielgboyce I suspect @dankelley will be at least a few hours before he reviews the changes, but in the meantime are you able to build from the latest source?

If not I can provide you with a built tarball that you can install in RStudio.

**Comment by danielgboyce** [comment] 2017-12-12 13:33
Hey @richardsc, thanks for the quick fix. After installing the latest version of oce I'm now able to import the file with no issues.

**Comment by richardsc** [comment] 2017-12-12 14:22
Great, thanks @danielgboyce . I'll close the issue then, since it seems addressed as stated in the title.

**Closed by richardsc** 2017-12-12 14:22 UTC
Labels: ODF
