### ISSUE TITLE
Missing date from argo profiles

### ISSUE THREAD

**Issue by MarkTaylorNOC** [dankelley/oce#2122] opened 2023-07-11 11:44 UTC
Recently, I have not been able to read in the date/time variable of profiles using the `readProfiles()` function in the `argoFloats` package (which uses `oce`). I have been able to do this many times in the past. When using the example code from the package help file, the argoFloats object reports all variables (latitude, longitude, temperature, etc...) except the date. The resulting output looks normal other than the absence of the time variable.
``` r
library(argoFloats)
#> Warning: package 'argoFloats' was built under R version 4.3.1
ai <- getIndex("synthetic")
sub <- subset(ai, 1:2) # To subset for profiles
#> Kept 2 cycles (0.000698%)
profiles <- getProfiles(sub)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 2 profiles read, 2 have >10% of oxygen values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2

str(argos@data$argos[[1]]@data)
#> List of 14
#>  $ latitude                : num -40.5
#>  $ longitude               : num 73.3
#>  $ pressure                : num [1:71, 1] 6.5 10.5 19.8 29.7 40.4 ...
#>  $ pressureAdjusted        : num [1:71, 1] 6.7 10.7 20 29.9 40.6 ...
#>  $ pressureAdjustedError   : num [1:71, 1] 2.4 2.4 2.4 2.4 2.4 ...
#>  $ temperature             : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjusted     : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjustedError: num [1:71, 1] 0.002 0.002 0.002 0.002 0.002 ...
#>  $ salinity                : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjusted        : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjustedError   : num [1:71, 1] 0.01 0.01 0.01 0.01 0.01 ...
#>  $ oxygen                  : num [1:71, 1] 232 233 235 236 234 ...
#>  $ oxygenAdjusted          : num [1:71, 1] 261 261 263 264 263 ...
#>  $ oxygenAdjustedError     : num [1:71, 1] 1.59 1.59 1.59 1.59 1.59 ...
```

<sup>Created on 2023-07-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've tried uninstalling and updating the `argoFloats` package, as well as using older versions, however this hasn't made a difference. This only happens on my work PC (Windows), and identical code works fine on my laptop (also Windows).

I'm currently using the following versions:
R version 4.3.0 (2023-04-21 ucrt)
argoFloats 1.0.6,
oce 1.8-0
ncdf4 1.21

Here are some details of my machine:
platform x86_64-w64-mingw32
arch x86_64
os mingw32

**Comment by dankelley** [comment] 2023-07-11 11:48
Thanks. Can you post what you get for the "works fine" case?  I think what might be happening is that if a file has MTIME defined then a `time` vector might be put into the `data` slot, but that if MTIME is not defined, then a *single* value called `time` is put into the `metadata` slot.

The thing is, users are not recommended to look in slots directly.  The recommended approach is to use e.g. `a[["time"]]` which looks in both locations.

**Comment by dankelley** [comment] 2023-07-11 11:53
Can you report the filenames of the two files you have?  If I repeat your code, I might get different results for the top two "synthetic" datasets, because your database might be a day or two old, and mine would be refreshed to today (at this moment), because I have not downloaded the database in a long time and so it will surely be refreshed.

I get as follows
```R
sub@data$index
                                    file                date latitude longitude
1 aoml/1900722/profiles/SD1900722_003.nc 2006-11-11 10:12:22  -40.455    73.335
2 aoml/1900722/profiles/SD1900722_004.nc 2006-11-21 07:50:21  -40.134    73.080
  ocean profiler_type institution          parameters parameter_data_mode
1     I           846          AO PRES TEMP PSAL DOXY                DDDD
2     I           846          AO PRES TEMP PSAL DOXY                DDDD
          date_update
1 2022-06-28 08:08:26
2 2022-06-28 08:08:39
```

**Comment by dankelley** [comment] 2023-07-11 12:06
Below is what I get.  Do you get the same, on the two test machines?


**CODE**

```R
library(argoFloats)
library(oce)
library(ncdf4)
ai <- getIndex("synthetic")
sub <- subset(ai, 1:2) # To subset for profiles
profiles <- getProfiles(sub)
argos <- readProfiles(profiles)
files <- paste0("~/data/argo/", gsub(".*/", "", sub@data$index$file))
for (file in files) {
    cat(file, "\n")
    cat("    has time =", paste(read.argo(file)[["time"]], collapse=" "), "\n")
    nc <- nc_open(file)
    hasMTIME <- "MTIME" %in% names(nc$var)
    if (hasMTIME)
        cat("    this file has an TIME field\n")
    else
        cat("    this file does not have an TIME field\n")
}
```

**RESULTS**

```
~/data/argo/SD1900722_003.nc
    has time = 2006-11-11 10:12:21.998857
    this file does not have an TIME field
~/data/argo/SD1900722_004.nc
    has time = 2006-11-21 07:50:21.001906
    this file does not have an TIME field
```

**Comment by MarkTaylorNOC** [comment] 2023-07-12 09:02
Here is what I get on the machine that DOES WORK:

``` r
library(argoFloats)
#> Warning: package 'argoFloats' was built under R version 4.2.2
library(oce)
#> Loading required package: gsw
library(ncdf4)

ai <- getIndex("synthetic")
sub <- subset(ai, 1:2) # To subset for profiles
#> Kept 2 cycles (0.000698%)
profiles <- getProfiles(sub)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 2 profiles read, 2 have >10% of oxygen values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2

str(argos@data$argos[[1]]@data)
#> List of 15
#>  $ time                    : POSIXct[1:1], format: "2006-11-11 10:12:21"
#>  $ latitude                : num -40.5
#>  $ longitude               : num 73.3
#>  $ pressure                : num [1:71, 1] 6.5 10.5 19.8 29.7 40.4 ...
#>  $ pressureAdjusted        : num [1:71, 1] 6.7 10.7 20 29.9 40.6 ...
#>  $ pressureAdjustedError   : num [1:71, 1] 2.4 2.4 2.4 2.4 2.4 ...
#>  $ temperature             : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjusted     : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjustedError: num [1:71, 1] 0.002 0.002 0.002 0.002 0.002 ...
#>  $ salinity                : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjusted        : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjustedError   : num [1:71, 1] 0.01 0.01 0.01 0.01 0.01 ...
#>  $ oxygen                  : num [1:71, 1] 232 233 235 236 234 ...
#>  $ oxygenAdjusted          : num [1:71, 1] 261 261 263 264 263 ...
#>  $ oxygenAdjustedError     : num [1:71, 1] 1.59 1.59 1.59 1.59 1.59 ...
sub@data$index
#>                                     file                date latitude longitude
#> 1 aoml/1900722/profiles/SD1900722_003.nc 2006-11-11 10:12:22  -40.455    73.335
#> 2 aoml/1900722/profiles/SD1900722_004.nc 2006-11-21 07:50:21  -40.134    73.080
#>   ocean profiler_type institution          parameters parameter_data_mode
#> 1     I           846          AO PRES TEMP PSAL DOXY                DDDD
#> 2     I           846          AO PRES TEMP PSAL DOXY                DDDD
#>           date_update
#> 1 2022-06-28 08:08:26
#> 2 2022-06-28 08:08:39


files <- paste0("~/data/argo/", gsub(".*/", "", sub@data$index$file))
for (file in files) {
  cat(file, "\n")
  cat("    has time =", paste(read.argo(file)[["time"]], collapse=" "), "\n")
  nc <- nc_open(file)
  hasMTIME <- "MTIME" %in% names(nc$var)
  if (hasMTIME)
    cat("    this file has an MTIME field\n")
  else
    cat("    this file does not have an MTIME field\n")
}
#> ~/data/argo/SD1900722_003.nc 
#>     has time = 2006-11-11 10:12:21 
#>     this file does not have an MTIME field
#> ~/data/argo/SD1900722_004.nc 
#>     has time = 2006-11-21 07:50:21 
#>     this file does not have an MTIME field
```

<sup>Created on 2023-07-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


This was run with the following versions:
R 4.2.1 (2022-06-23 ucrt)
argoFloats 1.0.6
oce 1.7-6
ncdf4 1.19

The machine has the following spec:
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32

**Comment by MarkTaylorNOC** [comment] 2023-07-12 09:11
This is what I get on the machine that DOES NOT WORK.

``` r
library(argoFloats)
#> Warning: package 'argoFloats' was built under R version 4.3.1
library(oce)
#> Loading required package: gsw
library(ncdf4)

str(argos@data$argos[[1]]@data)
#> List of 14
#>  $ latitude                : num -40.5
#>  $ longitude               : num 73.3
#>  $ pressure                : num [1:71, 1] 6.5 10.5 19.8 29.7 40.4 ...
#>  $ pressureAdjusted        : num [1:71, 1] 6.7 10.7 20 29.9 40.6 ...
#>  $ pressureAdjustedError   : num [1:71, 1] 2.4 2.4 2.4 2.4 2.4 ...
#>  $ temperature             : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjusted     : num [1:71, 1] 13.2 13.2 13.1 13 12.9 ...
#>  $ temperatureAdjustedError: num [1:71, 1] 0.002 0.002 0.002 0.002 0.002 ...
#>  $ salinity                : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjusted        : num [1:71, 1] 35.1 35.1 35.1 35.1 35.1 ...
#>  $ salinityAdjustedError   : num [1:71, 1] 0.01 0.01 0.01 0.01 0.01 ...
#>  $ oxygen                  : num [1:71, 1] 232 233 235 236 234 ...
#>  $ oxygenAdjusted          : num [1:71, 1] 261 261 263 264 263 ...
#>  $ oxygenAdjustedError     : num [1:71, 1] 1.59 1.59 1.59 1.59 1.59 ...


sub@data$index
#>                                     file                date latitude longitude
#> 1 aoml/1900722/profiles/SD1900722_003.nc 2006-11-11 10:12:22  -40.455    73.335
#> 2 aoml/1900722/profiles/SD1900722_004.nc 2006-11-21 07:50:21  -40.134    73.080
#>   ocean profiler_type institution          parameters parameter_data_mode
#> 1     I           846          AO PRES TEMP PSAL DOXY                DDDD
#> 2     I           846          AO PRES TEMP PSAL DOXY                DDDD
#>           date_update
#> 1 2022-06-28 08:08:26
#> 2 2022-06-28 08:08:39

files <- paste0("~/data/argo/", gsub(".*/", "", sub@data$index$file))
for (file in files) {
  cat(file, "\n")
  cat("    has time =", paste(read.argo(file)[["time"]], collapse=" "), "\n")
  nc <- nc_open(file)
  hasMTIME <- "MTIME" %in% names(nc$var)
  if (hasMTIME)
    cat("    this file has an MTIME field\n")
  else
    cat("    this file does not have an MTIME field\n")
}
#> ~/data/argo/SD1900722_003.nc 
#>     has time = 2006-11-11 10:12:21.998857 
#>     this file does not have an MTIME field
#> ~/data/argo/SD1900722_004.nc 
#>     has time = 2006-11-21 07:50:21.001906 
#>     this file does not have an MTIME field
```

<sup>Created on 2023-07-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment] 2023-07-12 09:24
Can you state the machine type and software versions of the machine that does not work?  If they are the same as for the machine that does work, then we have a mystery.  If not, we'll know what might have happened.

But, regardless, note that the way to get the time is to do e.g.
```R
argos@data$argos[[1]][["time"]]
```
not to try to look for `@data$time`.  This is by design.  Using `[[` instead of direct lookup is a scheme used throughout the oce package, so that users will be insulated from changes to where things are stored.  The other advantage of `[[` is that the user can get *computed* things that are not stored in the data, but that can be computed from those stored things.  (For example, `[["N2]]` causes oce to calculate derivatives of density to get the square of buoyancy frequency.)

**Comment by dankelley** [comment] 2023-07-12 10:43
I think the updated oce has time in the `metadata` slot whereas the older oce had it in the `data` slot. Users are not advised to use direct access such as `x@data$something`, so such a change in where the information went would have not have been considered an important thing.

I can change oce to store time in `data` for argo objects.  That would not affect any user who uses the `[["time"]]` mechanism.  We had a CRAN submission recently so will be blocked out from another one for maybe 6 months by CRAN policy, so to get that change a user (like you) would have to be able to build oce from source. 

Are you able to build oce from source on your target machines?   You can see how at the "Installing" section of the README file at https://dankelley.github.io/oce/

Note that the version of oce you are using, oce 1.7-6, is really quite old.  From https://dankelley.github.io/oce/news/index.html you can see that this is 7 versions old.  So beware that updating might change other things.  If I were you, I would just change my code to use `[["time"]]` since that ought to work going back for years.  But updating to the present CRAN version gives a variety of new features, as you can see from the link earlier in this paragraph.

PS. I don't think the two machines can have the same oce version, at least if my theory is correct.

**Comment by MarkTaylorNOC** [comment] 2023-07-12 11:12
Thanks Dan, I'll update oce and I'll change my code such to use `[["time"]]`.

**Comment by dankelley** [comment] 2023-07-12 11:34
Good. Perhaps you can close the present issue, once you've verified that the code in this issue works with the new oce.  There is no need to build oce from source; the one on CRAN is quite up-to-date since I released to CRAN just a few weeks ago.

Note that the new oce has new features but of course there might be problems, so please feel free top post new issues, if you encounter any.

Best regards.

Dan.

**Comment by MarkTaylorNOC** [comment] 2023-07-12 11:45
Excellent, thanks. I'll do some further checks and then close the issue if all is fine.

**Comment by dankelley** [comment] 2023-07-30 12:31
This issue was closed by the developer who solved the problem, because the following conditions were met:
1. the solution is simple
2. new tests were added to ensure that the solution works
3. the reporter is in frequent contact with the developer

Of course, if the reporter wants to reopen the issue, that's perfectly fine! The point here is just to avoid having issues in the developers' "to do" list, when they are probably done.

**Closed by dankelley** 2023-07-30 12:31 UTC
Labels: argo
