### ISSUE TITLE
Request for support for NORTEK Signature55/Signature100 ad2cp format

### ISSUE THREAD

**Issue by krillThor** [dankelley/oce#1676] opened 2020-04-04 12:05 UTC
Current version of oce (github version as of 03 April 2020) fails to read Signature55/100 ad2cp files with included echosounder (4.th (55) /5.th (100) beam) data. 

Error messages for both types of files are of the type:
```
Error in do_ldc_ad2cp_in_file(filename, from, to, by) : 
  coding error in reading the header at cindex=7018; expecting 0xa5 but found 0xbf 
```
The Signature55 files I have are for a prototype instrument (I believe one of the first with the additional 4.th echosounder beam), and an earlier version of the firmware, so I'm not sure how standardized the file format would be, but the Signature100 file is from a production rig.

Both files are however huge, so I won't upload them directly to github, the Signature55 file can be found here: 

https://www.dropbox.com/sh/b3scip0l9jd2zwr/AAAuJZbWCUyHwIbR6NChH_CFa?dl=0

and the Signature100 file here:

https://www.dropbox.com/sh/bw8apzzeloqnvml/AAB_KwD5zUC4wKCygtw-_oBOa?dl=0

**Comment by dankelley** [comment] 2020-04-04 12:28
@krillThor on a unix-like machine, you can make a shorter data file with e.g.
```
head -c 100000 S101135A001_Ronald.ad2cp > test.ad2cp
```
and that is a good idea, even though it will end in the middle of an ensemble.  (A 1Gb file is quite a lot to download.)

With this `test.ad2cp`, I am able to reproduce your error.

**Comment by krillThor** [comment] 2020-04-04 12:36
Ok, will minimize the files in the future. Anyway, let me just say that you guys put commercial software firms to shame, I posted that initial request < 30 min ago.

**Comment by dankelley** [comment] 2020-04-04 13:19
Note to self: I instrumented the C code (not pushed to github) and see as below.  So, we have 6 normal-looking chunks, and then this unrecognized one.
```
> a <- read.adp("~/Downloads/test.ad2cp",debug=3)
  read.adp("~/Downloads/test.ad2cp", from=(missing), to=(missing), by=(missing), manufacturer="(missing)", ...) {
    using read.oce() since 'manufacturer' argument is missing
      oceMagic(file="~/Downloads/test.ad2cp") {
        checking filename to see if it matches known patterns
        first line of file: �
        second line of file: �����rGETCLOCKSTR,TIME="2019-01-30 14:28:19"
        first two bytes in file: 0xa5 and 0x0a
    read.oce("~/Downloads/test.ad2cp", ...) inferred type="adp/nortek/ad2cp"
    read.adp.ad2cp(..., from=1, to=0, by=1, plan=(missing), type="(missing)",...)
      fileSize: 1e+05 
      first 10 bytes in file: 0xa5 0x0a 0xa0 0x10 0xf2 0x11 0xf6 0x8f 0xb9 0x72
      headerSize: 10 
      ID: 0xa0 (NB: 0x15=burst data record; 0x16=avg data record; 0x17=bottom track record; 0x18=interleaved data record; 0xa0=string data record, e.g. GPS NMEA, comment from the FWRITE command)
      dataSize: 4594 
      buf[1+headerSize+dataSize=4605]=0xa5 (expect 0xa5)
to=1000000000
fileSize=100000
at cindex=        10, buf: 0xa5 0x0a 0xa0 0x10 0xf2 0x11 0xf6 0x8f 0xb9 0x72
at cindex=      4614, buf: 0xa5 0x0a 0x16 0x10 0x4c 0x02 0x3a 0xc0 0xcd 0x92
at cindex=      5212, buf: 0xa5 0x0a 0x16 0x10 0x4c 0x02 0xc6 0x11 0x59 0xe4
at cindex=      5810, buf: 0xa5 0x0a 0x16 0x10 0x4c 0x02 0xf9 0xc5 0x8c 0x98
at cindex=      6408, buf: 0xa5 0x0a 0x16 0x10 0x4c 0x02 0x5b 0xb7 0xee 0x89
at cindex=      7006, buf: 0xa5 0x0c 0x23 0x10 0xa0 0x3e 0x00 0x00 0x92 0x24
at cindex=      7016, buf: 0x86 0x35 0x01 0xf0 0x77 0x05 0x04 0x10 0x01 0x15
Error in do_ldc_ad2cp_in_file(filename, from, to, by) : 
  coding error in reading the header at cindex=7016; expecting 0xa5 but found 0x86
In addition: Warning message:
In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  ignoring 'despike' (see documentation)
```

**Comment by dankelley** [comment] 2020-04-04 13:24
I see the below on page 45 in my "System Integrator's Guide" dated 2015.  Note the word "always". Maybe they changed the format in the meantime.  I'll see if I can find an update to this manual.  (FYI the manual is at https://www.dropbox.com/s/5n6oazlu2yswabh/Integrators%20Guide%20AD2CP_A.pdf?dl=0)

<img width="808" alt="Screen Shot 2020-04-04 at 10 22 41 AM" src="https://user-images.githubusercontent.com/99469/78451863-56979700-765e-11ea-95df-24340c871aa6.png">

**Comment by dankelley** [comment] 2020-04-04 13:36
I found a more recent (year 2018) version of the manual, and put it at https://www.dropbox.com/s/09a5dha0dsrpbqr/N3015-007-Integrators-Guide-AD2CP_1018.pdf?dl=0

**Comment by krillThor** [comment] 2020-04-04 13:51
I don't know what the Synchronization byte means in this context. As background: AFAIK the echosounder is not synced to the operation of the ADP, and IIRC the Signature55 unit transmits 2 narrowband pulses in addition to a broadband chirp for the echosounder beam. FYI the IMOS matlab code parsed the 55 data, but not the Signature100 data, but I did not try to dig into where the problem lies (I only have access to octave, not matlab, so unless it is something really obvious I tend to just drop matlab code that does not work).

**Comment by dankelley** [comment] 2020-04-04 13:56
In the 2018 version (see previous comment), still in section 6.1, I read "Always 0xA5".  I searched for "86" (the byte code that's causing problems here) and cannot find it in the manual, except as a page number and within a string of other numbers.

So, basically, I have no idea what's going on, and am not seeing a way to find the solution.  Reading binary files is complex, because it involves reading and interpreting one byte at a time, and the only way to know how to do that is if the manufacturer provides the required information in documentation.  In this case, we have a byte that should not be there, at least according to the most recent documentation I can find on the manufacturer's website (see previous comment).

In case anyone else wants to give this a go, please note that I have pushed to "develop" (commit  2dce4b205a47a6c23a637b86b31921450f156d7a; click the link to see the diff).  You will need to be able to build packages containing C and fortran sources.  If you are set up that way, you might be able to build it.  The first step is to pull this version from github.  Then, uncomment line 2 of `src/ldc_ad2cp_in_file.cpp`.  Then,  build the package.  At that stage (fingers crossed!) you will see information being printed out as it tries to read the data.  (Note that this printing is not tied to the `debug` argument; the printing is being done in C, and I do not want a test with an `if` statement, which burns up time, but rather with a C macro that, if turned off, has zero impact on performance.)

So, unless @richardsc or @krillThor has some further ideas, I think we are at an impasse.

Sorry!

**Comment by krillThor** [comment] 2020-04-04 14:00
Thank you for your effort. I'll send an email to NORTEK directly, and ask if they can provide updated file format information: these files are read and converted by MIDAS, and also OceanContour reads these, though the output from the echosounder is not usable.

**Comment by dankelley** [comment] 2020-04-04 17:28
Thanks. I think we need an update to N305-007-Integrators-Guide-AD2CP_1018.pdf, and the first place to look will be table 6.1, because the present form of that table indicates that headers always contain 10 bytes, but in this case, we have a header with 12 bytes at cindex=7006.  Also, the present form of the table does not mention type 0x23, which is what we have in this signature 100 file.

**Comment by krillThor** [comment] 2020-04-06 13:51
Hi, I got a reply from Nortek this morning, that I've translated from Norwegian where needed below:

...this is caused by the inclusion of raw data from the echosounder, which unfortunately is not yet documented in our manuals. These raw data use a 12 byte header instead of the standard 10 byte one. The reason for this change was the need to increase dataSize from 16 to 32 bits. Telegrams of this type use a 12 byte header:

#define RECORD_ID_ECHO_RAW 0x23 ///< Echo Sounder raw sample data format
#define RECORD_ID_ECHO_RAW_XMIT 0x24 ///< Echo Sounder raw synthetic transmit pulse data format
typedef struct
{
unsigned char sync; ///< = 0xA5
unsigned char hdrSize; ///< = sizeof(CommandHeader_t)
unsigned char ID; ///< Record ID (data type)
unsigned char family; ///< bits 4-7 = instrument type/family, bits 0-3 unused (instrument dependent)
unsigned long dataSize; ///< Size of data block to follow
unsigned short dataChecksum; ///< Word-wise checksum of data block
unsigned short hdrChecksum; ///< Word wise checksum of this structure
} CommandHeader2_t;

We can send the documentation, but you can also find the last version of our integration manual on our webpages:

https://support.nortekgroup.com/hc/en-us/categories/360001447411-Manuals

I checked there, but was unable to dig up a more recent version.

**Comment by dankelley** [comment] 2020-04-06 14:08
Thanks.  I should be able to figure out how to modify the code. I have some other things on my plate now so it might be a couple of days.  We will need to ignore the echosounder "chunks" because we don't have any format for them.

**Comment by dankelley** [comment] 2020-04-06 18:46
Note to self -- in the `dk` branch, we now make some progress (not full progress -- I am not yet looking at the issue of what to do with these new data chunks, and all I'm trying to do is to parse and checksum them).  Anyway, I get as below, and it makes me wonder a bit about what's going on, because I would have expected a regular pattern of the interspersing of what is presumably echosounder data.

(PS. ignore the error at the end ... all I care about is the debugging stuff at the top, about the byte parsing.)
```R
> library(oce)
Loading required package: gsw
Loading required package: testthat
> d <- read.oce("test.ad2cp")
to=1000000000
fileSize=100000
at cindex=   0 chunk=   0: sync=0xa5 size=10 id=0xa0 family=0x10 dataSize=4594 dataChecksum=36854 haderChecksum=29369
at cindex=4604 chunk=   1: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=49210 haderChecksum=37581
at cindex=5202 chunk=   2: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=4550 haderChecksum=58457
at cindex=5800 chunk=   3: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=50681 haderChecksum=39052
at cindex=6398 chunk=   4: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=46939 haderChecksum=35310
at cindex=6996 chunk=   5: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=9362 haderChecksum=13702
warning: odd header.id (0x23) at chunk 5, cindex=7008
at cindex=23040 chunk=   6: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=13253 haderChecksum=1994
at cindex=24002 chunk=   7: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=25741 haderChecksum=14112
at cindex=24600 chunk=   8: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=16589 haderChecksum=4960
at cindex=25198 chunk=   9: sync=0xa5 size=10 id=0x16 family=0x10 dataSize=588 dataChecksum=55668 haderChecksum=44039
at cindex=25796 chunk=  10: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=14970 haderChecksum=19310
warning: odd header.id (0x23) at chunk 10, cindex=25808
at cindex=41840 chunk=  11: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=22409 haderChecksum=11150
at cindex=42802 chunk=  12: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=2418 haderChecksum=6758
warning: odd header.id (0x23) at chunk 12, cindex=42814
at cindex=58846 chunk=  13: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=44487 haderChecksum=33228
at cindex=59808 chunk=  14: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=16054 haderChecksum=20394
warning: odd header.id (0x23) at chunk 14, cindex=59820
at cindex=75852 chunk=  15: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=41174 haderChecksum=29915
at cindex=76814 chunk=  16: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=43859 haderChecksum=48199
warning: odd header.id (0x23) at chunk 16, cindex=76826
at cindex=92858 chunk=  17: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=27289 haderChecksum=16030
at cindex=93820 chunk=  18: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=19094 haderChecksum=23434
warning: odd header.id (0x23) at chunk 18, cindex=93832
warning: ran out of file on data chunk near cindex=93832; wanted 16032 bytes but got only 6168
Error in read.adp.ad2cp(file, processingLog = processingLog, ...) : 
  unknown key 0x35; only 0x15 through 0x0x1f, plus 0xa0, are permitted
Calls: read.oce -> read.adp.ad2cp
In addition: Warning messages:
1: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  using to=18 based on file contents
2: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  since 'plan' was not given, using the most common value, namely 0

Execution halted
```

**Comment by dankelley** [comment] 2020-04-07 20:59
Hi again, @krillThor.  I've tried adjusting oce to read the signature100 data you sent.  I wonder if I can get some "ground truth" from you.  If you rebuild oce (the "issue1676" branch, *not* the "develop" branch) and try running the R file at https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676a.R you will get output something like below (at the bottom of this comment).

My questions for you are:

1. Does the plot look halfway reasonable?  (It does to me, in the sense that it does not look like television "snow", or angled stripes, which are the kind of things that can happen when reading data incorrectly.)

2. Does the output of the summary seem okay?  I am particularly interested in what it says about the echosounder portion (ignore the coordinate system that gets stated for that).

NOTE: I've not tried plotting or even looking at the echosounder data.  First, I'd like to know whether the number of echosounder bins seems ok, whether cell size seems ok, etc.  I assume the Nortek software will tell you such things.  Indeed, if you can make it print out numbers, I'd be very keen to see the numerical values it has for the first and second profiles.  That way, I'd know whether I read the binary correctly (and e.g. it's easy to get nutty answers by slight mistakes in reading binary!)

```

R version 4.0.0 alpha (2020-04-01 r78130)
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(oce)
Loading required package: gsw
Loading required package: testthat
> d <- read.oce("test.ad2cp")# , debug=5)
warning: ldc_ad2cp_in_file() ran out of file on data chunk near cindex=93832; wanted 16032 bytes but got only 6168
Warning messages:
1: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  using to=18 based on file contents
2: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  since 'plan' was not given, using the most common value, namely 0

3: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  only keys 0x15 through 0x1f, plus 0xa0, are permitted, but found other keys as follows:
   key=0x23 found 5 times

> if (!interactive()) png("1676a.png")
> plot(d)
> summary(d)
ADP Summary
-----------

* Serial number:      101135
* Frequency:          100 kHz
* Record type 'average' (the default item)::
    Number of profiles:  7 
    Number of cells:     32 
    Blanking distance:   2 
    Cell size:           10 
    Number of beams:     4 
    Beam angle:          
    Coordinate system:   enu 
* Record type 'echosounder'::
    Number of profiles:  5 
    Number of cells:     438 
    Blanking distance:   20 
    Cell size:           0.75 
    Number of beams:     1 
    Beam angle:          0 
    Coordinate system:   enu 
* Processing Log
    - 2020-04-07 20:52:00.833 UTC: `read.oce("test.ad2cp")`
> if (!interactive()) dev.off()
null device 
          1 
```

**Comment by dankelley** [comment] 2020-04-08 10:16
An update: I tried with the original sig100 file, and got as follows (about 20,000 lines in), i.e. we find a checksum error.  Of course, I don't really know if the file had been corrupted.  Maybe @krillThor could try https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676b.R on it, to see if the code dies at the same spot.
```
  at cindex=166769238 chunk=20624: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=1155 haderChecksum=5495
  at cindex=166785282 chunk=20625: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=13270 haderChecksum=2011
  at cindex=166786244 chunk=20626: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=62255 haderChecksum=1059
warning: ldc_ad2cp_in_file() at cindex=166786256, data checksum is 63402 but it should be 62255
Error in do_ldc_ad2cp_in_file(filename, from, to, by, debug - 1) : 
  expected header.sync to be 0xa5 but it was 0x00 at byte 166802288
Calls: read.oce -> read.adp.ad2cp -> do_ldc_ad2cp_in_file
```

**Comment by krillThor** [comment] 2020-04-08 13:08
Hi, sorry for the slow response: 
Yes, that file fails in the same spot for me. Tried a different file from a different unit, and it fails like this:
`at cindex=788203560 chunk=97464: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=45209 haderChecksum=49549
  at cindex=788219604 chunk=97465: sync=0xa5 size=10 id=0x1c family=0x10 dataSize=952 dataChecksum=3545 haderChecksum=57822
  at cindex=788220566 chunk=97466: sync=0xa5 size=12 id=0x23 family=0x10 dataSize=16032 dataChecksum=38680 haderChecksum=43020
warning: ldc_ad2cp_in_file() at cindex=788220578, data checksum is 48856 but it should be 38680
Error in do_ldc_ad2cp_in_file(filename, from, to, by, debug - 1) : 
  expected header.sync to be 0xa5 but it was 0x00 at byte 788236610`

As for the output, I'll check the velocity output against a matlab export done by the MIDAS software and report back

**Comment by krillThor** [comment] 2020-04-08 13:30
Ok, just checked, the ENU velocities generated by oce are for all purposes identical (deltas found in 8.th decimal place, so rounding errors), and the amplitudes are also the same (save for the factor 0.5)

**Comment by krillThor** [comment] 2020-04-08 13:37
And NORTEK also sent me a page with the format for the echosounder data, I paste the contents in below. Wrt. the echosounder portion: The numbers look correct, with the caveat that I think NORTEK reports blanking distance in decimeters, 20 I believe should be 2, but also their MIDAS output reports this value as 20.

[Echo Sounder RAW Data format ver1.docx](https://github.com/dankelley/oce/files/4450776/Echo.Sounder.RAW.Data.format.ver1.docx)

**Comment by dankelley** [comment] 2020-04-08 16:00
Thanks for all of this. I plan to do the following, sometime over the next few days
* [ ] recover more gracefully after a bad checksum.  (I think I will set the whole profile to `NA`, on the principle that it's best not to expose users to potential garbage.)
* [ ] change the storage for the blanking distance (I prefer to use metres for distances)
* [ ] look at the doc for echosounder and adjust the code if necessary

**Comment by dankelley** [comment] 2020-04-12 13:21
I've started looking at the bytes in the chunk with the bad checksum. At the moment,  https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676c.R (with oce code **not** pushed to github because it's in such a state of flux, and printing so much information) I get as shown below.

I was thinking that maybe a single incorrect byte was causing the bad checksum, but instead what I see is a long list of zero bytes.  I wouldn't mind knowing what would cause this, because I think it would be good to understand, but my path forward is clear.  When I see a bad checksum, I'm going to have to skip forward until I find something that looks like a header, and if that fails, repeat that step until things clear up or the file ends.

All I really know is that headers start with 0xa5, so the probability of a false positive is 1/255.  After that, I suppose I can demand that the next byte corresponds to either 10 or 12, reducing the probability by a further factor of 2/255.  And then maybe (I hypothesize--but this needs chcking) the "Family" should be the same as in previous chunks, for a further reduction of 1/255.  So, the false-positive hit rate will be about 1e-7, or one in ten million.  This is all assuming that bytes are randomly distributed, which is not the case (see the graph).  Anyway, I plan to do this checking, and if the checksum from that fails, repeat the scan from where we were before.

I am not sure why I've never seen checksum failures before (in **any** instrument, adp or adv, RDI, Sontek, or Nortek).  Perhaps @krillThor or @richardsc has insights on that?  Maybe these new instruments are using different logging/storage hardware?

Happy Easter (or similar near-Equinox holiday).


![1676c](https://user-images.githubusercontent.com/99469/79069492-0d21fa00-7ca5-11ea-8fd8-e58eeb97ed01.png)

**Comment by krillThor** [comment] 2020-04-13 13:17
I have no idea what caused these glitches, and MIDAS reported some lost periods as well (though only a very few ones, I guess I was "unlucky" with the file I uploaded). As background information we had some issues with both our rigs, and were unable to export files via the connection software, though NORTEK were able to retrieve all files from the storage cards.

**Comment by dankelley** [comment] 2020-04-13 13:25
Actually, I think it is "lucky" because it gives the chance to improve the handling of checksum failure.  I am making progress on this, but am not committing changes until things get more stable.  I get 5 checksum errors in your sig100 file, but that might be incorrect, since my recovry scheme involves going back and trying again, but I might not have it quite right, yet.

That diagram that is posted in https://github.com/dankelley/oce/issues/1676#issuecomment-612613500 helped a fair bit.  I almost think it would be worth adding an oce function to do that, since I rewrite such code on-the-fly quite a lot, which means that other folks looking at binary data might want to do something similar.  Thoughts, @richardsc or @clayton33?

**Comment by dankelley** [comment] 2020-04-13 13:54
@krillThor Are the attached plots at least semi-reasonable for this code?  I am not looking for details -- just whether something seems crazy.  What I see is diurnal tide plus maybe a wind event (not sure on latter).  Plus, a reminder: the code is not pushed to github.
```R
library(oce)
file <- "~/Dropbox/S101135A001_Ronald.ad2cp"
d <- read.oce(file, debug=5)
if (!interactive()) png("1676b_image.png")
plot(d, zlim=c(-1.5, 1.5))
summary(d)
if (!interactive()) dev.off()
if (!interactive()) png("1676b_hist.png")
par(mfrow=c(3,1), mar=c(3,3,2,1), mgp=c(2,0.7,0))
v <- d[["v"]]
hist(v[,,1], xlab="u [m/s]", main="")
hist(v[,,2], xlab="v [m/s]", main="")
hist(v[,,3], xlab="z [m/s]", main="")
if (!interactive()) dev.off()
```
---

![1676b_image](https://user-images.githubusercontent.com/99469/79125700-f34fe800-7d74-11ea-8365-aa9570cfb4b8.png)

---

![1676b_hist](https://user-images.githubusercontent.com/99469/79125699-f2b75180-7d74-11ea-8d7a-cd6d09af6b73.png)

**Comment by krillThor** [comment] 2020-04-13 16:18
Looks good to me! Though I'm more used to looking at backscatter than currents, being a biologist.
From previous deployments and from the MIDAS generated matlab files I know we have a fairly clear diurnal tide in the region, so this looks reasonable to me, and the weather along the South Orkneys can be fairly hard, so a wind-event wouldn't surprise me either.

**Comment by dankelley** [comment] 2020-04-14 10:25
I think the "issue1676" branch may solve the problem.  I have test code at https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676b.R which uses your dataset. 

I have some requests of @krillThor:

1. Could you try building this branch and testing the code to see if it fails?
2. As you can see, I've tried putting a few tests at the bottom of https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676b.R which do not test against *reality* but rather against what I am getting *at this moment*.  Ideally -- but only if it's easy for you -- it would help if you could see if the numbers make sense compared to other software on this file.
3. Would you be willing to make say the first 100k or so of your file public?  If you could do that, then I could put tests like you see in 1676b.R into the actual oce test suite.  This would have the advantage of "cementing" things so that future changes to the oce ad2cp code would not break existing functionality.  If not, then would you be willing to let me and the other two core oce developers keep a non-public copy of those 100k of your file, so we can test it as we build oce?  (NOTE: if you don't want either of these, i.e. if you want to keep the data secret, please let me know, so I can delete it from https://github.com/dankelley/oce-issues/blob/master/16xx/1676 ... I don't think we need to worry about the references that have been made in this issue, because once you remove the Dropbox file, those references won't work, and your file will be private.)

**Note to other oce developers:** I plan to merge "issue1676" into "develop" on the upcoming Saturday morning.  All existing tests (in https://github.com/dankelley/oce/blob/develop/tests/testthat/test_ad2cp.R) still pass, so I don't think I've broken the ad2cp code that we already had.

**Comment by dankelley** [comment] 2020-04-14 11:31
I wrote some tests (as might be used if 100k of the file gets made public) in https://github.com/dankelley/oce-issues/blob/master/16xx/1676/1676d.R

**Comment by krillThor** [comment] 2020-04-14 18:26
Testing 1 & 2 now. I'm the PI on the project that these files come from, so I have no problem making the files public, whatever size that suits you.

**Comment by krillThor** [comment] 2020-04-14 18:52
The "original" file gives this output on my machine:

`bad data checksum (expected 0xf32f but got 0xf7aa) at cindex:166802288[166802288] (17.758% through file)
... got a sync character (0xa5) at cindex=166821942 (17.76% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=166822534 (17.76% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=166833909 (17.762% through file)
    BUT header-size is 182, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=166833949 (17.762% through file)
    BUT header-size is 161, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=166834106 (17.762% through file)
    BUT header-size is 15, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=166836301 (17.762% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=166836300[166836300]
bad data checksum (expected 0xec53 but got 0x166e) at cindex:184628312[184628312] (19.656% through file)
... got a sync character (0xa5) at cindex=184653178 (19.659% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=184659806 (19.659% through file)
    BUT header-size is 79, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=184659833 (19.659% through file)
    BUT header-size is 198, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=184659889 (19.659% through file)
    BUT header-size is 234, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=184659951 (19.659% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=184662325 (19.66% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=184662324[184662324]
bad data checksum (expected 0x1ea8 but got 0x475f) at cindex:571814346[571814346] (60.877% through file)
... got a sync character (0xa5) at cindex=571838056 (60.88% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=571841908 (60.88% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=571845272 (60.88% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=571846188 (60.88% through file)
    BUT header-size is 2, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=571847548 (60.881% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=571848359 (60.881% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=571848358[571848358]
bad data checksum (expected 0x629c but got 0x20b1) at cindex:608895860[608895860] (64.825% through file)
... got a sync character (0xa5) at cindex=608927988 (64.828% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=608928911 (64.828% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=608928910[608928910]
bad data checksum (expected 0x67d but got 0xa74f) at cindex:939274730[939274730] (99.998% through file)
... got to end of file while searching for a sync character (0xa5)
Warning messages:
1: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  using to=116125 based on file contents
2: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  since 'plan' was not given, using the most common value, namely 0

3: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  only keys 0x15 through 0x1f, plus 0xa0, are permitted, but found other keys as follows:
   key=0x23 found 55008 times`

And another file from a different unit gives these warnings:

`bad data checksum (expected 0x9718 but got 0xbed8) at cindex:788236610[788236610] (79.474% through file)
... got a sync character (0xa5) at cindex=788270623 (79.477% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=788270622[788270622]
bad data checksum (expected 0xce40 but got 0x42db) at cindex:923569412[923569412] (93.118% through file)
... got a sync character (0xa5) at cindex=923632614 (93.125% through file)
    BUT header-size is 255, not 10 or 12 as expected
... got a sync character (0xa5) at cindex=923637437 (93.125% through file)
        proper header-size character (either 10 or 20 decimal)
            family=16 is consistent with previous family
            All seems OK, so resetting to cindex=923637436[923637436]
warning: ldc_ad2cp_in_file() got to end of file near cindex=991822520 (100% through file); wanted 16032 bytes but got only 15336
Warning messages:
1: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  using to=122624 based on file contents
2: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  since 'plan' was not given, using the most common value, namely 0

3: In read.adp.ad2cp(file, processingLog = processingLog, ...) :
  only keys 0x15 through 0x1f, plus 0xa0, are permitted, but found other keys as follows:
   key=0x23 found 58088 times`

However, both files read in, and the output looks good, and is within rounding error of output from NORTEK's MIDAS software. Thanks a lot again, fantastic support!

For the record, there is now a subfolder in the dropbox folder that contains mat-files exported from MIDAS and my csv dumps from those files, that I used for comparison. 

Thor

**Comment by dankelley** [comment] 2020-04-14 19:01
Thanks, Thor.  This looks good.  (I edited your comment so it would get correct indentation.  Three backtick characters are the way to get that.)

These are the expected messages (at the moment) for dealing with failed checksums.  I will likely clean this up some more, removing intermediate message as the code tries to synch up with the next start-of-ensemble.

I'll have a look at the other files you put in the Dropbox, likely tomorrow sometime.

Thanks very much for your patience!

**Comment by dankelley** [comment] 2020-04-15 09:58
The "issue1676" branch now uses the first 50,000 bytes of the sample file in its test suite. Most of the tests therein are consistency checks that will ensure that future versions of oce will produce results matching the version as of today.  I like having tests like that, so that if oce changes (deliberately or by accident) then the test will fail.  That's a way to (a) prevent gratuitous changes to oce (like renaming data items) an also to (b) guard against errors that might arise as oce changes for other reasons (like bug fixes that have ripple effects).

**Comment by dankelley** [comment] 2020-04-20 16:35
Dear reporter,

Do you think this issue (as defined by its title) has been addressed in the "develop" branch of oce?  If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Closed** 2020-04-20 23:06 UTC
