### ISSUE TITLE
colormap default palette is still "Jet"

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1779] opened 2021-02-09 03:23 UTC
I thought we had this changed (based on #colormap, but I just installed from CRAN and see that `colormap()` still has the default as `oceColorsJet`:

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.1, PROJ 6.3.1
library(ocedata)
data(levitus)
imagep(levitus$SST, colormap=colormap(levitus$SST))
```

![](https://i.imgur.com/BhG56Bf.png)

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment] 2021-02-09 03:31
Fixed in afdd99a30

**Comment by richardsc** [comment] 2021-02-09 03:31
Too bad we just released this to CRAN, but whatayagonnado?

**Comment by richardsc** [comment] 2021-02-09 04:49
Re-opening because I think I need to also fix something in the tests -- @dankelley can you take a look?

**Comment by dankelley** [comment] 2021-02-09 10:04
I'm taking a look.  Thanks.  Also, I'll add an entry to `NEWS.md`, and add a note to the docs for the `col` arg of `colormap()`.

**Comment by dankelley** [comment] 2021-02-09 10:45
Thanks for the catch, @richardsc.

I think this is done now, in "develop" commit 849b6888bf24805410630f344cf1ba174cf4b4e9.  I have
1. documented the change in NEWS.md,
2. documented the default value (old and new, and time of change) in the docs for colormap(),
3. changed the test suite to "burn in" the new values returned by a colormap() call,
4. run `devtools::check()` as a first check,
5. run `R CMD build` to make a tarball and `R CMD check --as-cran` on that tarball (since that is what CRAN does),
6. checked the tarball size (4.9M, just under the 5.0M limit),
7. pushed to github, waited an hour or so for the automated tests to complete, and
8. demonstrated in the following example.

Since I'm not the original reporter, I won't close this ... please take a look and close or add more comments, @richardsc 

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
par(mfrow=c(1,2))
imagep(volcano, colormap=colormap(volcano, col=oceColorsJet))
mtext("OLD scheme")
imagep(volcano, colormap=colormap(volcano))
mtext("NEW scheme")
```

![](https://i.imgur.com/vHt7ZUQ.png)

<sup>Created on 2021-02-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-02-10 12:02
I see that it is disobeying the `name` argument.  Maybe it always was -- I don't see the point in checking; I'll just fix it.

**Comment by dankelley** [comment] 2021-02-10 14:02
I've made a branch for this, to test things out.  This is the most complicated code in `oce`, I think, with so many possibilities that have to work together, especially since `colormap()` and `imagep()` are probably always used together.  Did the user give `zlim`?  That's 2 choices.  But did the user give `z`? Now 4 choices in total.  What about `breaks`? 8 choices. What about `col`? 16 choices. What about `colMissing`? 32 choices. What about `name`? 64 choices.  And that's just off the top of my head for the choices.  Furthermore, these functions are old, and therefore users have expectations for how they work.

Below shows a workaround, which is what I wanted anyway.  I'm just using the "z" characteristics set by the named colormap.  Come to think of it, this may be the real answer: users who provide  `colormap()` with a `name` are asking not just for colors, but for colors *plus* a mapping to z values, and therefore they should not be giving things like `breaks` and so forth.  After all, the docs for `colormap()` say that setting `name` is the way to get predefined colour schemes, like GMT, and they say that `.cpt` files are used (which bind colours with values).  And the doc for `colormap()` says that providing `name` means that `x0`, `x1`, `col0` and `col1` will be ignored. I think it makes sense to ignore `zlim` and `breaks` also, if `name` is given (and this is where the problem is arising).

My plan is to look at this again when I have some spare time.  It's too tricky to do in a quick edit, and a lot of testing (all those many cases) will be needed for any change.  I don't want a desire to fix a bug (that nobody has noticed before) lead me down a path of altered code that might cause lots of problems.

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
data(topoWorld)
par(mfrow=c(2,1), mar=c(2,2,2,2))

imagep(topoWorld)
mtext("Expect oceViridis")

cm2 <- colormap(name="gmt_relief")
imagep(topoWorld, colormap=cm2)
mtext("Expect gmt_relief")
```

![](https://i.imgur.com/j24DEer.png)

<sup>Created on 2021-02-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-03-23 17:19
Jeeze, I'm lost on this issue.  Since a CRAN release is now imminent, I will try to see whether this is fully done.  It looks like I did the majority of the work in a separate branch ... and then got on to other things.  I'll make a decision by 1200h Halifax time, tomorrow, on whether to try to incorporate that branch into the main one, for a possible CRAN release at the end of the week.

**Comment by dankelley** [comment] 2021-03-23 17:23
I see
```
git wdiff 1779_colormap_name R/colors.R|wc
      99     567    6177
```
which makes it look as though that branch is quite different.  But I think more than half of that is just getting clearer debugging messages.  I am going to merge "develop" into "1779_colormap_name" and see if things still look okay in the latter.  That won't hurt anything.

**Comment by dankelley** [comment] 2021-03-23 17:43
I've looked at the 1779_colormap_name branch, and am making up some tests on it.  I am running to some problems.  It's the usual thing: we have a lot of arguments, and so there are a lot of intersecting combinations that need to be addressed properly.

Since the planned CRAN resubmission is only 2 to 3 days away, I will not be incorporating "1779_colormap_name" into "develop".  I'll return to it after the CRAN release.  I need time to check for ripple effects.

**Comment by dankelley** [comment] 2021-03-23 18:54
I am going to go ahead and close this, because all but the sidetrack (that is now in #1796) was done and tested long ago.

**Closed by dankelley** 2021-03-23 18:54 UTC
Labels: colormap
