### ISSUE TITLE
Adding Vertical Data To Section Plot

### ISSUE THREAD

**Issue by ajcanepa** [dankelley/oce#667] opened 2015-06-16 21:59 UTC
Dear All,
I'm coming back with the section plot, and now I'm interested into add vertical (distribution) data. I have for three depth ranges (0-25, 25-50 and 50-100 m.) abundance data that I would like to add to a section plot.
Does anyone know how to do it in OCE package?,
Please any comment will be very useful
Thanks,
Antonio
PS: Attached there is an example with a commercial software
![vertical_distribution_section](https://cloud.githubusercontent.com/assets/10628672/8195552/c47acd44-1459-11e5-8ef2-6a66e4100de3.jpg)

**Comment by richardsc** [comment] 2015-06-17 02:24
Hi Antonio,

I'm sure that it's possible to do what you want. It would help if you could give a better idea of what the results you want are meant to show -- in other words, how do I interpret the boxes in the example plot you showed? I assume the heights of the boxes correspond to the vertical extent over which the abundance data were collected. Are the widths related to the horizontal extent? Or the abundance within the box? What do the black vs grey boxes mean -- different species? Or do the colors represent abundance?

It would also be much easier to help if you provide some example data and code. It doesn't have to be your own data, but something similar (i.e. made-up) that demonstrates what you want to achieve.

Cheers,
Clark

**Comment by richardsc** [comment] 2015-06-17 04:06
Here is a pretty crude example that I think does what you want. Mind you, I don't know what the widths/colors of the boxes mean in your example, but here I've set the width to be the width of the abundance measurement region. The colors represent the abundances. I'm sure there's a more clever/elegant way of coding the z-levels, but it's late and I should be in bed :).

```r
library(oce)

## pull out the Gulf stream
data(section)
GS <- subset(section, 109<=stationId&stationId<=129)

## make up some abundance data
x <- c(50, 130, 200, 200, 200, 300) # x location of sample
w <- c(10, 5, 30, 2, 10, 50) # width in km
a <- abs(rnorm(x)) # abundance value
z <- c(2, 2, 1, 2, 3, 3) # code the height of the sample

## this is crude, but here z codes the depth range, e.g.:
## 1. 0-500
## 2. 500-1000
## 3. 1500-2000

## Now make a function that will draw boxes to represent abundance
plotAbundance <- function(x, w, a, z, col) {

    for (i in seq_along(x)) {

        ## elseif to do a lookup for the depth ranges -- crude
        if (z[i] == 1) {
            zlim <- c(0, 500)
        } else if (z[i] == 2) {
            zlim <- c(500, 1000)
        } else if (z[i] == 3) {
            zlim <- c(1500, 2000)
        }

        ## setup the polygon and draw it
        xx <- c(x[i]-w[i]/2, x[i]+w[i]/2, x[i]+w[i]/2, x[i]-w[i]/2)
        zz <- c(zlim[1], zlim[1], zlim[2], zlim[2])
        polygon(xx, zz, col=col[i])
    }
}

cm <- colormap(a, breaks=length(x))
drawPalette(colormap=cm)
plot(GS, which='sigmaTheta', mar=c(3, 3, 1, 4))
plotAbundance(x, w, a, z, col=cm$zcol)
```
![screen shot 2015-06-17 at 12 04 23 am](https://cloud.githubusercontent.com/assets/233584/8199497/8cd5cff8-1484-11e5-852e-e2c237ba1ed8.png)

**Comment by ajcanepa** [comment] 2015-06-18 15:41
Hi Clarck, 
Thank you for the code, you were pretty close, even with my poorly supported question ;)
I'm still don't have the data (raw or simulated), so I'll try to explain what the widths and the color of the boxes means.
The heights of the boxes are OK, they are the depth at which the abundance data was collected. Mostly every species are present at the 3 depths. Then, the width of the boxes represents the abundance, the wider the box the more abundant the species at this depth (I thought to plot a violin plot instead a box, but I'm also don't know how to do it). And finally, the colors (black/gray) corresponds to the moment of sampling (black = Night sampling and gray= daylight sampling) and it's stored as a new "factor" column in the spreadsheet.
Can I ask you, please, if you can modify your code to plot the with of the boxes as the abundance? (any idea how to make a label for this?) 
Thank you so much for your help.

Cheers,

Antonio

**Comment by richardsc** [comment] 2015-06-18 17:46
Hi Antonio,

Since you're the one who ultimately has to make an accurate and publication quality plot, I would suggest that you first try modifying my code above for the specific case you want. It mostly should be pretty similar, except with a two-colour palette and the width of the box scaled based on the abundance. I would start by thinking about how you could calculate the `w` variable (width on the plot) based on the abundance variable `a`. 

I'd be happy to offer more advice here if you get stuck. Just make sure you post a *self-contained and reproducible* example that others can run themselves.

Clark

**Comment by dankelley** [comment] 2015-06-26 11:48
@ajcanepa -- if you consider this issue to have been addressed, please close it. The normal convention with Oce is that reporters close issues, not developers. Thanks, and good luck with R and oce.

**Closed** 2015-06-26 16:03 UTC
