### ISSUE TITLE
plotProfile() not displaying units

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1413] opened 2018-05-08 15:08 UTC
Example:
```r
library(oce)
data(ctd)
plotProfile(ctd, xtype='temperature')
```
![image](https://user-images.githubusercontent.com/233584/39765543-76036e5a-52b8-11e8-8cfc-390eb6cab105.png)

**Comment by dankelley** [comment] 2018-05-08 18:37
Hm, only for `unesco` EOS. I'm making a test file.

**Comment by dankelley** [comment] 2018-05-08 18:51
The problem is seen in:
```R
plot(3,3,xlab=resizableLabel("T", "x", unit=unit))
```
so it's deep down in `resizableLabel`.

**Comment by dankelley** [comment] 2018-05-08 19:11
I see where it's happening. Because of some work on a previous issue (I'm not smart enough to search old issues) I had constructed code along the lines of the following. The first part of the `if` works, but the second is creating a sort of expression within an expression, and that's not working. I'll look into this -- there is likely some kind of a trick with `eval` or `dequote` or something, that will let `unit` in the second part of the `if` to be altered in some way so that the end result is a clean expression.
```R
        if (is.null(unit)) {
             full <- bquote(.(var)*.(L)*degree*"C"*.(R))
            abbreviated <- bquote("T"*.(L)*degree*"C"*.(R))
        } else {
             full <- bquote(.(var)*.(L)*.(unit)*.(R))
            abbreviated <- bquote("T"*.(L)*.(unit)*.(R))
         }
 
```

**Comment by dankelley** [comment] 2018-05-08 19:54
I think this is working now in "develop". There is also a test-suite item. I explain more in the commit note:

commit e3356bc089efbb89fd497199bb7a04d0085988fb
Author: dankelley <kelley.dan@gmail.com>
Date:   Tue May 8 16:50:27 2018 -0300

    plotProfile() handles units better (issue 1403)+
    
    + this should improve plot,ctd-method also, of course.  The problem came
    up in fixing another issue in which axis labels for unitless things were
    getting "[]" appended on the end, which looked like a weird cabalistic
    box on the plot (as it does, in this commit message, with the font I'm
    using in my terminal!).
    
    I am reasonably assured that the fix is OK, from inspection of the "git
    diff" output and from the 1403 test suite.

**Comment by dankelley** [comment] 2018-05-13 14:25
Dear reporter,

If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

PS.  This is a standardized reply.

**Closed** 2018-05-14 13:18 UTC
Labels: ctd, graphics, units
