### ISSUE TITLE
speed up plotting of large time series?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1805] opened 2021-04-15 13:31 UTC
This is something that Dan and I have been talking about for a few days, and that I explored a little in a blog post:

https://www.clarkrichards.org/2021/04/13/a-fast-time-series-plotting-function/

Some of @dankelley's thoughts from an email:

> How about "simplify"?  That seems to be a good name.
  I'd see options as
  `TRUE` (default)
  `FALSE` (as now)
  `number` (number of subdivisions)
  Then maybe like below for `simplify=TRUE`.  The `simplify=NUMBER` case is similar and could be interwoven.
  ```r
        deviceWidthInches <- diff(par("pin")[1:2])
        devicePixels <- deviceWidthInches * 400 # I think mac uses this
        n  <- length(time)
        if (n > devicePixels) {
          # your code here to change "t" and "x" or whatever we call the args
        }
  ```

**Comment by dankelley** [comment] 2021-04-16 10:25
Clark, I can set this up, if you like. Or were you going to?  It might be easiest for me to take the first cut, since I wrote a lot of the `oce.plot.ts()` code so it should be easy to see where to slot this in.

**Comment by dankelley** [comment] 2021-04-16 14:41
I'll do this in a branch called issue1805, based on Clark's code (https://www.clarkrichards.org/2021/04/13/a-fast-time-series-plotting-function/) and my snippet above.  There are a few other subtleties but I won't bother with the details until I have something ready to check or improve.

**Comment by dankelley** [comment] 2021-04-16 17:06
I'll start with the docs.  I have as follows (not pushed to GH).  It's quite long, so if I can see a way to shorten it, I will.  (It is not a good idea to say "see Details", I think, because if too many arguments do that, the user is going back and forth between two sections more than is comfortable.)

```R
#' @param simplify an optional logical or integer value that indicates
#' whether/how to speed up `type="l"` plots by replacing the actual data
#' with minimum and maximum values within a subsampled time mesh.
#' This can speed up high-density line plots, often with little change
#' in the appearance, if the number of points is large (say more than a few
#' hundred thousand). There are three cases.
#' (1) If `simplify` is `FALSE`, this feature is turned off.
#' (2) If `simplify` is `TRUE`, then the number of data points
#' in the plot view is divided by the figure width in inches, and if
#' the minimum/maximum method is used if that ratio exceeds 1000.
#' (3) If `simplify` is a number, then it is treated like the
#' 1000 in case 2. In any of these cases, a warning message is printed if the
#' simplification is done, so that the user will be aware that the
#' actual data are not being plotted.
#' *Note:* this is a provisional feature added in mid-April 2021,
#' and it may be changed or removed up until early June 2021.
```

**Comment by dankelley** [comment] 2021-04-16 20:16
After a Z meeting, I revised the docs to be as follows. I'll look into coding this on the weekend.
```R
#' @param simplify an integer value that indicates
#' whether to speed up `type="l"` plots by replacing the data
#' with minimum and maximum values within a subsampled time mesh.
#' This can speed up line plots with a large number of points,
#' sometimes with minor changes in appearance.
#' This procedure is skipped if `simplify` is `NA` or
#' an integer exceeding the number of data points in view.
#' Otherwise, `oce.plot.ts` creates `simplify` intervals ranging across
#' the visible time range. Intervals with under 2 finite
#' `y` data are ignored. In the rest, the `y` values
#' are replaced with their range, and the `t` values are replaced
#' to the midpoint time, repeated. Thus each retained subinterval
#' has exactly 2 data points.
#' A warning is printed if this procedure is carried out.
#' The default value of `simplify` means that cases with
#' under 2560 visible points are plotted conventionally.
```

**Comment by dankelley** [comment] 2021-04-17 12:53
I'm working on this now.  One thing: I'll need to tweak a test that expects `plot(rsk)` to be silent, because it now makes a warning that the dataset is being simplified. The new test will be
```R
          expect_output(plot(rsk), "simplifying data")
```
PS. it is not sensible to trim that dataset because it's in sqlite3 format and we want oce to work that format as created by the RBR/ruskin system.

**Comment by dankelley** [comment] 2021-04-17 15:30
This is done now in the "issue1805" branch, commit 245ceb4b4d766a8838e6bb48c0009dcabb84015d.

I have some tests in https://github.com/dankelley/oce-issues/tree/main/18xx/1805, including a timing test.  I ran the timing test by factor 10 in each step, up until it was taking a long time.

At a certain point in the computation, the memory pressure is doubled for the split-up data frame and, although that pressure eases up after the simplification is done, it may still overwhelm a system.  Basically, if you're working with really large datasets, you'll need lots of memory and lots of time.  Still, a factor of 10 speedup is useful to have, and presumably an analyst will realize that if it takes a long time to load a dataset then it's likely to take a long time to plot it... and perhaps they just won't use timeseries plots this way, instead perhaps looking at subsets, or spectra.

I'm putting the speed test 1805c.R below, so you can see the pattern of speedup.  I did triplicate measurements.

I propose that @richardsc use this branch for a while, to look for problems, but also perhaps to thin a bit more about what the default value of `simplify` ought to be.  He might also want to explore, for a given data size, how speed varies with alteration of the `simplify` value.  It would be great to get some real-world experience with this, because it *does* change the default behaviour of `oce.plot.ts()`.

<details><summary>Speed test and plot</summary>

``` r
# Display oce.plot.ts() speedup using simplify.
timing <- "
  N    orig    new
1e3   0.157  0.161
1e3   0.158  0.162
1e3   0.153  0.160
1e4   0.248  0.387
1e4   0.236  0.374
1e4   0.247  0.389
1e5   1.646  0.429
1e5   1.688  0.426
1e5   1.687  0.435
1e6  12.397  0.593
1e6  12.938  0.649
1e6  11.970  0.583
1e7  55.722  2.290
1e7  55.937  2.290
1e7  55.958  2.502"
d <- read.table(text=timing, header=TRUE)
par(mfrow=c(2,1), mar=c(3,3,1,1), mgp=c(2,0.7,0))
plot(d$N, d$orig, type="o", log="x",
     xlab="Number of Data Points", ylab="User Time [s]")
legend("topleft", col=1:2, legend=c("Unsimplified", "Simplified"), pch=1, lwd=1)
points(d$N, d$new, type="o", col=2)
plot(d$N, d$orig/d$new, type="o", log="x",
     xlab="Number of Data Points", ylab="Time Reduction Factor")
```

![](https://i.imgur.com/f3uPuZw.png)

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-04-17 17:45
Oh, I forgot that maybe `findInterval()` is faster than `cut()`.  Yup, the demo below shows that's the case.  The speedup (*for that portion of the computation alone*) may be something like a factor of 2 or 3 for typical cases of 1 to 100 million data.

So,  I'll recode `oce.plot.ts()` to use `findInterval()` tomorrow.

<details>
``` r
# is findInterval() faster than cut()?
t0 <- as.POSIXct("2021-01-01", tz="UTC")
Ns <- 10^(4:8)
As <- rep(NA, length(Ns))
Bs <- rep(NA, length(Ns))

for (i in seq_along(Ns)) {
    t <- t0 + seq(1, Ns[i])
    ninterval <- 2560
    y <- rnorm(Ns[i])
    df <- data.frame(t, y)
    b <- seq(min(t), max(t), length.out=ninterval)
    As[i] <- system.time(A <- split(df, cut(t, b)))[1]
    Bs[i] <- system.time(B <- split(df, findInterval(t, b)))[1]
}

par(mfrow=c(2,1), mar=c(3,3,1,1), mgp=c(2,0.7,0))
plot(Ns, As, type="b", log="x", ylim=range(c(As,Bs)),
     xlab="Number of Data Points", ylab="User Time [s]")
lines(Ns, Bs, type="b", col=2)
legend("topleft", col=1:2, lwd=1, pch=1, legend=c("cut", "findInterval"))
plot(Ns, As/Bs, type="b", log="x",
     xlab="Number of Data Points", ylab="Time Reduction Factor")
```

![](https://i.imgur.com/aGRsNM3.png)

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-04-18 12:34
I've switched to `findInterval()`.  Also, I changed the criterion to try to get 5 points within each interval. Previously, if the number of points exceeded `simplify` by a small amount, a lot of the intervals might only get 1 or 2 values, and the scheme would therefore skip those intervals (since then a line from min to max would just be a point).

The new timing test is in the Details.  I'm not sure why some of the triplicates are consistently unlike the others, but suspect it was a garbage-cleanup or other operation related to the fact that I was doing the tests interactively.

The main point is that the plot is done in under 3s for up to 10^7 points, whereas 10^7 points took about a minute before.  In other words, `oce.plot.ts()` is now fast enough to be fine for interactive use.

PS. I cannot test much higher than 1e7 on my machine, owing to memory constraints.  We need 8 bytes per number, for 8N bytes. But we need both x and y, for 16N bytes.  And then we need both user values and plot values, for 32N bytes. To get from user to plot values we need to do sums and multiplications, which will at least double that, for 64N bytes.  For N=1e8, that's 6.4Gbyte of memory, as a lower estimate.  This is about what's on my machine, so working with N=1e8 is beyond what I'd expect to work and, indeed, when I try tests in that range, I get out-of-memory errors from R.

<details>

``` r
# Display oce.plot.ts() speedup using simplify.
# The '*Data' come from 1805a.R runs, varying the 'N' definition.
cutData <- "
  N    orig    new
1e3   0.157  0.161
1e3   0.158  0.162
1e3   0.153  0.160
1e4   0.248  0.387
1e4   0.236  0.374
1e4   0.247  0.389
1e5   1.646  0.429
1e5   1.688  0.426
1e5   1.687  0.435
1e6  12.397  0.593
1e6  12.938  0.649
1e6  11.970  0.583
1e7  55.722  2.290
1e7  55.937  2.290
1e7  55.958  2.502"

findIntervalData <- "
  N    orig    new
1e4   0.236  0.249
1e4   0.254  0.255
3e4   0.672  0.495
3e4   0.609  0.430
1e5   1.616  0.503
1e5   1.585  0.438
3e5   3.969  0.564
3e5   3.932  0.417
1e6  11.581  0.675
1e6  11.479  0.463
1e6  11.414  0.471
3e6  26.590  1.136
3e6  25.641  0.627
3e6  25.483  0.615
1e7  49.957  2.409
1e7  47.437  1.139
1e7  47.179  1.124
3e7  78.386  2.983
3e7  79.046  3.275
3e7  79.574  3.030
1e8 176.972 12.296
1e8 175.567 12.965
"

par(mfcol=c(2,1), mar=c(3,3,1,1), mgp=c(2,0.7,0))
d <- read.table(text=findIntervalData, header=TRUE)
plot(d$N, d$orig, log="x",
     xlab="", ylab="User Time [s]")
grid()
legend("topleft", col=1:2,
       legend=c("simplify=NA", "simplify=2560 (default)"), pch=1, bg="white")
points(d$N, d$new, col=2)
mtext("1805c.R, plotting results from 1805a.R", cex=par("cex"), adj=1)
plot(d$N, d$orig/d$new, log="x",
     xlab="Number of Data Points (log scale)", ylab="Time Reduction Factor")
grid()
```

![](https://i.imgur.com/3eXPFSP.png)

<sup>Created on 2021-04-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-04-19 10:38
@richardsc it would be good if you could try out this "issue1804" branch for a while.  I suspect it's okay, but it probably should have a bit more real-world exercising before being merged into "develop".

I changed the procedure a bit.  If you say `simplify=N`, that means it will only apply the simplification if there are `5*N` points.  That way, the chance of having 2 or more points per interval becomes fairly high.  With the old scheme, if you had `N+1` points, it would only get a single interval with 2 points, meaning only a single vertical line would appear.  I picked the "5" out of the blue, really.

Also, I have not played with the default value of `simplify`.  It would maybe be good to have a real-world test on that (with some adv data perhaps).  Maybe 2000 would be better, or 1000.  (The 2560 number was the number of pixels on my screen ... I think it's unlikely to draw a 1-pixel-wide line, so maybe that should be reduced, and I actually think 1000 might be sensible.). I'd be interested, again for real-world data, in whether 1000 and 2560 look different, and also whether the speeds differ.

**Comment by richardsc** [comment] 2021-04-19 10:42
I will play with it this week!

Also, I edited your comment above to correct the branch name (1805 instead of 1804).

**Comment by richardsc** [comment] 2021-04-20 17:08
I haven't traced this down to exactly what is causing the error, but one quick test I did produced the following:
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
x <- rnorm(1e5)
t <- Sys.time() + seq_along(x)
oce.plot.ts(t, x)
#> Warning in oce.plot.ts(t, x): simplifying a large dataset; use simplify=NA to use raw data
#> Error in strptime(xx, f, tz = tz): invalid 'tz' value
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment] 2021-04-20 17:15
Looks like it is demanding `tz="UTC"`.  I suppose we could convert to UTC, if there is no tz given.  (I am not totally sure that will work out ... I think maybe `AST` has a meaning in the Maritimes, but another in Australia.)

**Comment by dankelley** [comment] 2021-04-20 18:10
This is because `Sys.time()` does not set a timezone attribute.  I'll see how this ripples through the code.
```R
> attr(Sys.time(),"tzone")
NULL
```

**Comment by dankelley** [comment] 2021-04-20 18:11
Maybe I can rely on e.g. the following working
```R
> Sys.timezone()
[1] "America/Halifax"
```

**Comment by richardsc** [comment] 2021-04-20 18:23
The problem with `NULL` `tz` isn't in the general `oce.plot.ts()` code because this works fine:
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
x <- rnorm(1e3)
t <- Sys.time() + seq_along(x)
oce.plot.ts(t, x)
```

![](https://i.imgur.com/t5J0sRY.png)

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment] 2021-04-20 18:24
My reading of `?Sys.timezone()` tells me that it may be risky to assume that it will return anything useful.  (Maybe it will, maybe it won't.)

You're right, the problem is not in the general `oce.plot.ts()`.  I'm looking into this.

**Comment by dankelley** [comment] 2021-04-20 18:25
The problem is that I'm using `numberAsPOSIXct()`, and it does not like `tz=NULL`, which is what we get if we inherit the `tz` from the first argument.

**Comment by dankelley** [comment] 2021-04-20 18:38
I think this ought to work now in "issue1805" branch, commit e7f6f5f59a782c7b3b59917f3b8a380eee596809, as evinced by the following.  (I like how it is spelling out the timezone on the plot, since I am pretty sure there be quite a lot of `ADT` timezones on this planet.  A local user might recognize that whacky abbreviation, but for a plot, likely to be seen by a wide audience, it makes sense to spell out the timezone in the new city/region way.)

<details>

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
x <- rnorm(1e5)
t <- Sys.time() + seq_along(x)
oce.plot.ts(t, x)
#> Warning in oce.plot.ts(t, x): simplifying a large dataset; use simplify=NA to use raw data
```

![](https://i.imgur.com/iGHrWqn.png)

``` r
t[1]
#> [1] "2021-04-20 15:35:56 ADT"
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by richardsc** [comment] 2021-04-20 18:47
Thanks! I'll test it.

I have to admit I'm not crazy about including the timezone in the "TimeRange" of the plot .... I see the value, but it's actually a big style change from how `oce.plot.ts()` has been for years, so might be worth its own issue to discuss further.

**Comment by dankelley** [comment] 2021-04-20 18:54
Sure, we can discuss in another issue.  I'm not sure if its an effect of this branch or not ... I am in a branch for odf right now.

**Comment by richardsc** [comment] 2021-05-01 12:38
Where are we with this issue now? Has the branch been merged? (it is good to merge before things diverge too much ...).

**Comment by dankelley** [comment] 2021-05-01 12:41
I think we were at your comment "Thanks! I'll test it." i.e. I was waiting for you.  Does it seem OK now?

PS. I agree with the idea of merging before too many changes :-)

**Comment by richardsc** [comment] 2021-05-01 12:50
It does seem ok to me!

**Comment by dankelley** [comment] 2021-05-01 12:57
Thanks.  I'll merge "1805" into "develop" at 1300h today.

**Comment by dankelley** [comment] 2021-05-01 16:16
Hm.  I looks as though I already merged it in, and forgot.  Anyway, it's now pushed to "develop" commit a7fdd9c1ddd04ad717d3343f08f2b04e6731b26a.  

This passes "R CMD check" on my machine.  In about 30 minutes, I'll have the results from nonlocal tests, and if those are OK, I'll close this issue.  Thanks for the reminder, Clark!

**Comment by dankelley** [comment] 2021-05-01 16:31
The external tests have passed (temporary website https://github.com/dankelley/oce/actions/runs/802524952) and so I'm closing this now.  Of course, @richardsc ought to feel free to reopen it (or create a new issue with a new title) if there is a problem.

**Closed by dankelley** 2021-05-01 16:31 UTC
