### ISSUE TITLE
despike() should have non-NA replacement for trim

### ISSUE THREAD

**Issue by lilizhix** [dankelley/oce#1067] opened 2016-08-23 02:28 UTC
I have a ts x1,  when I was using "trim" as reference, and set up min and max, when I try to replace to trimmed values with reference, but I only see NA here.

despike(x1, reference="trim",min=10000,max=20000, replace = "reference")

this is the value for x1

3715  7546 10903 13386 15196 14976 17718 17112 17295 16996 14523 15135 15126 15136 74444 73313 77076 80477 20775 19930 14747 10787 10671 12018 13086 13085 12904 12253 15245 16847 17490 17868 14542 13714 13628 14145 13749 14141 14069 13659 13879 13662 13935 15072 15572 15371 55748 71488 78153 80438 44134 28826

As you claimed:

For reference="trim", the reference time series is constructed by linear interpolation across any regions in which x<min or x>max. In this case, the value of n is ignored, and the return value **either uses the reference time series for spikes**, or NA, according to the value of replace.

**Comment by dankelley** [comment] 2016-08-23 09:53
Thanks. I have made a simpler example, below, and I'll use that to test my solution, which I expect later today or tomorrow.
```R
library(oce)
library(testthat)
min <- 10000
max <- 20000
x1 <- c(3715, 7546, 10903, 13386, 15196, 15371, 55748, 71488)
x2 <- despike(x1, reference="trim",min=min,max=max, replace = "reference")
print(data.frame(x1,x2))
x3 <- x1
x3[x3<min] <- min
x3[x3>max] <- max
expect_equal(x2, x3)
```

**Comment by dankelley** [comment] 2016-08-23 11:57
I think this is now fixed in `develop` commit 11d1bd54aa43e2832de4f1fb08d2537b027bfbc2. I put a more extensive test code at [the git issues site](11d1bd54aa43e2832de4f1fb08d2537b027bfbc2) and have reproduced it below. I have also clarified the documentation. The problem in this case was that I was not using `rule=2` in my call to `approx`.

Please try rebuilding from github (I can post instructions if you don't know how) and testing the code below. If it seems OK, please close the issue. Otherwise, let me know what is wrong.

Thanks very much for reporting this!

```R
library(oce)
library(testthat)
min <- 10000
max <- 20000
x1 <- c(3715, 7546, 10903, 13386, 15196, 15371, 55748, 71488)

x2 <- despike(x1, reference="trim", min=min, max=max, replace="reference")
x3 <- x1
x3[1:2] <- 10903 # result from approx() with rule=2
x3[7:8] <- 15371 # result from approx() with rule=2
expect_equal(x2, x3)

x4 <- despike(x1, reference="trim",min=min,max=max, replace="NA")
x5 <- x1
x5[x5<min] <- NA
x5[x5>max] <- NA
expect_equal(x4, x5)
```

**Comment by lilizhix** [comment] 2016-08-24 01:04
Yes, please post the instructions for rebuilding, thanks a lot.

**Comment by dankelley** [comment] 2016-08-24 01:20
Please see the 'source code...' portion of http://dankelley.github.io/oce/installation.html and note that the last method, the github one, is the easiest for most users. Also, pay attention to the 'note' at the end.

I'm offline now for the evening. Good luck.

**Comment by dankelley** [comment] 2016-08-25 09:49
Any success in building oce? If you use OSX or Windows, I can supply pre-built versions (although you are better off getting the build-from-github method to work because then you can stay up to date more easily).

**Comment by lilizhix** [comment] 2016-08-29 08:44
It worked. Thanks.

**Comment by dankelley** [comment] 2016-08-29 09:34
If you think the issue (as defined by its title) has been addressed, please close it. This comment is added to an issue when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Closed** 2016-08-30 01:30 UTC
