### ISSUE TITLE
‘manufacturer’ is not a slot in class “adp”

### ISSUE THREAD

**Issue by stynclaeys** [dankelley/oce#955] opened 2016-05-03 09:14 UTC
Sorry, found the same in another Issue

**Comment by stynclaeys** [comment] 2016-05-03 09:20
Sorry, found the same in another Issue

**Comment by dankelley** [comment] 2016-05-03 09:36
Sorry, I'm confused by "found the same". Are you saying the problem no longer exists, or that it has already been reported? Or maybe that there was no problem? If there *is* a problem (new or old), please clarify what it is, so we can have a look at it. Thanks.  (I reopened this.)

**Comment by stynclaeys** [comment] 2016-05-03 10:27
Dear Mr. Kelly,

My excuses. Found the same issue on https://github.com/dankelley/oce/pull/906

Kind regards,

Styn


Van: Dan Kelley [mailto:notifications@github.com]
Verzonden: dinsdag 3 mei 2016 11:36
Aan: dankelley/oce
CC: Claeys, Styn; State change
Onderwerp: Re: [dankelley/oce] ‘manufacturer’ is not a slot in class “adp” (#955)


Sorry, I'm confused by "found the same". Are you saying the problem no longer exists, or that it has already been reported? Or maybe that there was no problem? If there is a problem (new or old), please clarify what it is, so we can have a look at it. Thanks. (I reopened this.)

**Comment by dankelley** [comment] 2016-05-03 10:43
Thanks. Did you check the `develop` branch and found it to be OK? If so, please close this issue. If not, Clark and I can take a look but we would likely need sample R code and a data file (the latter can be emailed to me privately)

**Comment by stynclaeys** [comment] 2016-05-04 07:56
I tried to install the oce develop package, but not succesfull

(1)  install_github('dankelley/oce', ref='develop')

gives the following error:

_Downloading GitHub repo dankelley/oce@develop
from URL https://api.github.com/repos/dankelley/oce/zipball/develop
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached_

(2) downloaded the oce-develop.zip file => Install Packages => Package Arcive File 
I can find the oce-develop directory but the package does not show up in my Packages list in R-studio

**Comment by dankelley** [comment] 2016-05-04 09:32
I don't know how to do method (2) so I can't comment but I just tried method (1) and it works for me, so maybe this was a temporary network problem.

**Comment by stynclaeys** [comment] 2016-05-04 09:37
I tried it again, and get the same error. I will ask the IT department to check if the download is not blocked

**Comment by richardsc** [comment] 2016-05-04 11:10
I could be wrong, but my understanding of your **Method 2** is that is for pre-built binary package tarballs. So I'm not surprised that it won't work with the Github-downloaded `.zip` file, because that is just a zip of the source code.

What operating system are you on? Perhaps the below link could help with devtools issue:

http://stackoverflow.com/questions/31311872/error-while-using-install-github-devtools-timeout-issue

**Comment by dankelley** [comment] 2016-05-11 12:16
This issue seems to have gone stale. There is no problem in leaving issues open if tests or development is ongoing, but the developers do not like to leave users "high and dry" by mistake. Therefore, this is a request for a status update. If the issue is still active, perhaps someone can make a comment to that effect, ideally  with a suggested timetable or work-plan for resolution. Otherwise, this issue will become a candidate for closure by the developers, which is not the preferred scheme, since in "oce" we like reporters to be the ones to close issues. (This is a standardized reply.)

**Comment by stynclaeys** [comment] 2016-05-11 13:18
Dear Mr Kelley,

My excuses, I am busy executing measurements on the field and the data is not being processed now.

I’m using Windows 7 Prof and tried the code, options(download.file.method = "wininet"), without success. I cannot find the cause of the problem.

Kind regards

Styn

Van: Dan Kelley [mailto:notifications@github.com]
Verzonden: woensdag 11 mei 2016 14:17
Aan: dankelley/oce
CC: Claeys, Styn; State change
Onderwerp: Re: [dankelley/oce] ‘manufacturer’ is not a slot in class “adp” (#955)


This issue seems to have gone stale. There is no problem in leaving issues open if tests or development is ongoing, but the developers do not like to leave users "high and dry" by mistake. Therefore, this is a request for a status update. If the issue is still active, perhaps someone can make a comment to that effect, ideally with a suggested timetable or work-plan for resolution. Otherwise, this issue will become a candidate for closure by the developers, which is not the preferred scheme, since in "oce" we like reporters to be the ones to close issues. (This is a standardized reply.)

**Comment by dankelley** [comment] 2016-05-11 13:58
You might want to try the built-up windows version (see http://dankelley.github.io/oce/installation.html)

**Comment by stynclaeys** [comment] 2016-05-13 09:00
Dear mr. Kelley,

The standard solution “Download and build using install_github()”, does not work.
We will look at it next week with the internal R specialists.

King regards,

Styn


Van: Dan Kelley [mailto:notifications@github.com]
Verzonden: woensdag 11 mei 2016 15:59
Aan: dankelley/oce
CC: Claeys, Styn; State change
Onderwerp: Re: [dankelley/oce] ‘manufacturer’ is not a slot in class “adp” (#955)


You might want to try the built-up windows version (see http://dankelley.github.io/oce/installation.html)

**Comment by dankelley** [comment] 2016-05-13 09:29
It would help if you could post a self-contained sample of R code that will yield the issue you've reported. That should be posted here (instructions are given below). We would also need a dataset -- please send that privately to Dan and Clark by email, dropbox, etc., and be aware that we are very familiar with private data, and will keep the files confidential.

If you do these things, we can remove the guesswork in finding the bug. 

**How to use github issues**: please click the link at the bottom of the email, and enter your information there. If you do a reply, without trimming the extra information, your posting would be doubled (then trebled, etc) in length, and you may be revealing confidential information like emails and phone numbers. And please, when indicating code, click the "insert code" button at the top of the issue-reporting box (it looks like `< >`). Doing these things will protect your privacy and also make it easier for us to see what the problem is, so we can help.

**Comment by richardsc** [comment] 2016-05-15 03:45
To my knowledge, as pointed out previously, the issue reported here was fixed in #906. This seems now to be an issue of getting the updated package installed.

The easiest option given the devtools issues is to install the "pre-compiled" version, which can be downloaded as a `.zip` file from:

https://www.dropbox.com/sh/awlz31v1jj7w0ct/AAClePwKAwvJpwD8o385zfi2a/windows?dl=0

and then installed with RStudio by using the menu item **Install Packages** under the **Tools** menu, and selecting **Install from: Package archive file**.

**Comment by stynclaeys** [comment] 2016-05-16 09:58
@dankelley ; @richardsc 
Thanks for the help. 
Finally I installed the 

> OCE develop

 version on another computer on my private network.
Now the issue is solved.
Kind regards,
Styn

**Comment by dankelley** [comment] 2016-05-16 10:00
Thanks for the bug report, and good luck in your research.

**Closed by dankelley** 2016-05-16 10:00 UTC
Labels: adp, low priority
