### ISSUE TITLE
Problem with landsatTrim

### ISSUE THREAD

**Issue by Larissalesgn** [dankelley/oce#675] opened 2015-06-24 12:25 UTC
Hello,
I'm trying to use the function landsatTrim but I just can't make it work. I've tried some codes (including convert the coordinates from lon-lat to UTM) but I keep receiving the same error:
`Error in landsatTrim(ns, low, up) : 
  no intersection between landsat image and trimming box`

One of the codes I've tried was:
```R
library(oce)
low <- list(longitude=-39.5, latitude=-4.5)
up <- list(longitude=-39, latitude=-4)
ns <- read.landsat("LC82170632015124LGN00", band="tirs1")
trim <- landsatTrim(ns, low, up)
plot(trim)
```

I would really apreciate some help.
Thank you for the attention.

**Comment by dankelley** [comment] 2015-06-24 12:48
I'm setting up an issue so I can test. Any chance of a download link so I can get the file?

**Comment by dankelley** [comment] 2015-06-24 12:50
Cancel last msg -- I am downloading the file now.

**Comment by dankelley** [comment] 2015-06-24 13:07
I've started work on this, with [test code here](https://github.com/dankelley/oce-issues/tree/master/675). I'll post again when I see what the problem is. Thanks.

**Comment by richardsc** [comment] 2015-06-25 00:43
I see that you updated in the thread, but the downside to editing comments
is that I don't get an email notification. I browse the changes in the
commit, but it wasn't clear to me what was wrong -- was the bug specific to
that image, or is is something that might come up more generally?

**Comment by dankelley** [comment] 2015-06-25 09:19
Oh, interesting ... I thought you'd get notifications on within-comment edits, too. I'll keep that in mind.

I don't know how general the problem was. This test case was with negative lon and negative lat, which is a case I didn't try before (I was looking at Cape Split before). So that might be it. But the other problem may be (and I think is) an issue with ``lonlat2utm()``.

Previously, I was deciding on the intersection set (in image-index coordinates) based on UTM coordinates, as opposed to the lon-lat coordinates supplied by the user. Somehow I had thought that doing so was smarter, in some way relating to the usual map projection issues. However, these images are of limited area, so I think the practical difference between interpolating in lon-lat and in utm space may be small in practical terms. This method requires that ``lonlat2utm`` be correct, and my guess is that the error was in that reliance.  Conversion is actually quite tricky ... UTM has this "zone" concept that makes for complications.

In any case, the previous state was giving really nutty answers for the utm values. Probably it's the S hemi or the W hemi, or both ... but I realized that the images are of a small area so it's probably reasonable to work in lon-lat space anyway. (I don't really know whether NASA wants us to rely on corners in lon-lat space or utm space.)

Some tests with other images would be helpful.

In the meantime, below are related bugs (or buglets) that I plan to fix...

1. Trimming should probably update the utm-based corner values in the object metadata.  It does not do so anymore. Fixing this will require becoming certain that ``lonlat2utm`` is correct, however.  (It is not a simple matter of interpolation, because the corners might be in different UTM "zones".) The good thing is that these utm-based corners are not (I think) used for anything. And, to be honest, I don't really think they should even be stored in the metadata ... we have lon and lat, which is the only way plots can be done now.

2. I need to find a definitive source for test values for lonlat to utm conversion.  A book or an article would be fine. Then I can build the test values into the oce build-test suite, and there won't be as much need to worry. I still think the present way trimming is done is more sensible, and I'd like to do that because I think the chance for error is small. But I don't want ``lonlat2utm()`` to be wrong, if I can find a way to fix it.  (I am not entirely sure when anyone would use it though ... military people use utm, and so do hikers, but they use it with maps and GPSs, not oce.)

PS. I realized (duh) that landsat8 gets turned off away from the land. It's just a lucky accident that it works on Scotian Shelf and other near-land spots.  I imagine they do that to save 70% power, but too bad for oceanographers.

**Comment by dankelley** [comment] 2015-06-25 09:42
I'm going to put some web citations below. I plan to keep updating this comment as I find more. My first goal with each will be to (a) assess definitiveness (e.g. IBM might be reliable because they have a reputation to uphold) and (b) look for test values.
* http://www.ibm.com/developerworks/library/j-coordconvert/
* http://leware.net/geo/utmgoogle.htm
* http://www.uwgb.edu/dutchs/usefuldata/utmformulas.htm
* http://www.earthpoint.us/Convert.aspx

**Comment by Larissalesgn** [comment] 2015-06-26 13:18
I did what you said and work it fine...Thank you very much

**Comment by Larissalesgn** [comment] 2015-06-29 13:09
I updated the oce with your link e then I tried the code but the coordinates of the trim image weren't right...so I uninstalled the oce and installed again but the result was the same...I also tried with others landsat archives, without the latitude and longitude been both negative and they worked, but when the both are negatives I keep getting results like this:
![trim 1 teste](https://cloud.githubusercontent.com/assets/12861044/8408385/1e275fec-1e46-11e5-82df-b5d4ad8e96eb.png)

Is it like the image is upside down? Anyway it's confusing

**Comment by dankelley** [comment] 2015-06-29 13:20
Thanks. I've broken something again! I'll look sometime this evening.

**Comment by Larissalesgn** [comment] 2015-06-29 13:24
Thanks, I'll be waiting for your feedback

**Comment by dankelley** [comment] 2015-07-01 16:35
Sorry for the delay. I updated the test code to use a uniform colour scheme in both panels. I think the ``develop`` branch handles this properly now; code and plot below.
```R
library(oce)
#try(source("~/src/oce/R/map.R"))       # lets author test changes to the code
#try(source("~/src/oce/R/landsat.R"))   # lets author test changes to the code
if (1 == length(list.files(pattern="^LC.*$"))) {
    low <- list(longitude=-39.5, latitude=-4.5)
    up <- list(longitude=-39, latitude=-4)
    if (1 != length(ls(pattern="^ns$"))) { # buffer for speed of interactive testing
        ns <- read.landsat("LC82170632015124LGN00", band="tirs1")
    }
    trim <- landsatTrim(ns, low, up)
    if (!interactive()) png("675.png", width=7, height=3, unit="in", res=100, pointsize=9)
    par(mfrow=c(1,2))
    plot(ns, band="temperature", col=oceColorsJet, zlim=c(-35, 35))
    abline(h=c(up$latitude, low$latitude))
    abline(v=c(up$longitude, low$longitude))
    plot(trim, band="temperature", col=oceColorsJet, zlim=c(-35, 35))
    if (!interactive()) dev.off()
} else {
    message("675.R needs a directory named LC82170632015124LGN00")
}
```
![675](https://cloud.githubusercontent.com/assets/99469/8459785/ff131eaa-1ff5-11e5-8509-2df3896a1973.png)

**Comment by dankelley** [comment] 2015-07-05 17:07
@Larissalesgn -- if you think this has been fixed in the ``develop`` branch, could you close the issue, please?

**Comment by dankelley** [comment] 2015-07-07 13:05
I am closing this because it seems to be OK in my testing, and the original reporter has not responded to the 6-day-old fix. Of course, the original reporter should feel free to reopen this!

**Closed by dankelley** 2015-07-07 13:05 UTC
Labels: ****, landsat, Needs recheck
