### ISSUE TITLE
Backscatter vs Echo Intensity 

### ISSUE THREAD

**Issue by Vinterwoo** [dankelley/oce#1169] opened 2017-01-12 13:12 UTC
In the past I've been working exclusively with the velocity data coming from RDI workhorses. But now I'm interested in digging into the backscatter data, and I've come across a question concerning the terminology used.

I've used the WinRiver program to visualize backscatter data with success. Now I'm attempting to recreate these same plots in OCE using the` [['a']]` data, though I'm unsure if these are the same things as I've seen both the terms "backscatter" and "echo intensity" used to describe [['a']] data.  

It is my understanding that what WinRiver is calling "Backscatter" is the echo intensity data that has been corrected for distance (aka- a particle of the same size and acoustic properties will have the same backscatter intensity at 3 meters away and 30 meters away).

This would be different than just the raw echo intensity data (aka a particle of the same size and acoustic properties will have a lower echo intensity at 30 meter than at 3 meters).

Given an OCE adp object, can you tell me if the `[['a']]` data is consider backscatter (distance  corrected) or raw? If it is raw, is there a method in OCE to correct for distance?

**Comment by dankelley** [comment] 2017-01-12 13:18
I suspect Clark knows more about this than I do.

**Comment by richardsc** [comment] 2017-01-12 17:39
Hi @Vinterwoo,

Good question. I have seen lots of different terminology used for the various forms of "backscatter", and in `oce` we never decided formally on a naming scheme that is consistent. In my experience, the terms tend to vary from lab to lab, often because the data may be used for different purposes. I personally am probably guilty of using "backscatter amplitude" and "echo intensity" interchangeably, though what really matters is what *units* accompany the field, e.g. raw values are measured in `counts` and corrected values should be measured in something like `dB` (relative to some reference).

**SIDE NOTE: I notice that currently `oce` doesn't handle `units` for the `[['a']]` field. If the result of this issue is that we clean up the nomenclature and handling of the backscatter correction (my proposal), this would be another to consider adding.**

I don't use WinRiver for analysis, so I don't know what it does to the data or what it displays. I can tell you that by default when you create an `adp` object by reading from and RDI file the "backscatter" field `[['a']]` is the **raw** counts reported by the unit (i.e. *un*corrected).

To get the corrected backscatter, you can pass the object through the function `beamUnspreadAdp()`, which accounts for the reduction in backscatter with distance due to the spherical spreading. See `?beamUnspreadAdp` for details. You might also want to check out [Deines (1999)](http://www.comm-tec.com/library/Technical_Papers/RDI/echopaper.pdf).

In the current `oce` nomenclature, there is an `@metadata` item called `oceBeamUnspreaded` which describes whether this correction has been applied to the backscatter or not (e.g. `TRUE` or `FALSE`). You can also see from an object summary, e.g.:
```r
library(oce)
data(adp)
summary(adp)
```
```
ADP Summary
-----------
* Instrument:         adcp
* Serial number:      (serial number redacted)
* Firmware version:   16.28
* Source filename:    ``(file name redacted)``
* Location:           47.88126 N, -69.73433 E
* Number of profiles: 25 
* Number of cells:    84 
* Number of beams:    4 
* Cell size:          0.5 m
* Measurements:       2008-06-25 10:00:00 UTC to 2008-07-04 13:48:49 UTC sampled at 0.1 Hz
* Subsample:          2008-06-26 UTC to 2008-06-27 UTC sampled at 0.0002778 Hz
* Cells:              84, centered at 2.230 m to 43.730 m, spaced by 0.500 m
* Coordinate system:  beam [originally], enu [presently]
* Frequency:          600 kHz
* Beams:              4 beams (not attenuated) oriented upward with angle 20 deg to axis
```
Note the mention of "not attenuated" in the description of the beams. Actually, I think what that really means is "not corrected for attenuation", so I think that should be cleaned up.

**Proposal: the nomenclature regarding backscatter and whether or not the correction has been applied should be cleaned up. @dankelley and I have bounced this around in the past, and settled on "unspreaded", which actually I think is unclear (and poor english). I propose coming up with a better name for the procedure, perhaps `beamCorrectAttenuation()` or `beamCorrectSpreading()`. Suggestions appreciated**.

One final note, and part of the reason @dankelley and I found this tricky to name when we implemented it -- there are lots of things that can affect the actual *attenuation* of the beam (absorption by water, by the actual scatterers in the water, etc) as a function of distance from the transducer, which are not possible to correct using a simple geometric formula as is used in `beamUnspreadAdp()`. That function is really designed to correct *only* the reduction at range due to spherical spreading. If you are interested in actual measurements of things like volume backscattering strength, you'll need to think more about the other mechanisms for acoustic attenuation as well as calibration of the individual transducers.

**Comment by dankelley** [comment] 2017-01-13 12:33
My comments on bold-faced items in Clark's last comment:

1. I agree, `adp` items should have units, if they can be figured out. I propose also to add "originalNames" for these. The best source for names is (in my opinion) the "RDI ADCP WorkHorse Commands and Out Data Format - November 2007,pdf" document (or a newer version if we can get it ... we *do* need to settle on a particular document to refer to page numbers, though). On page 122 of that document I see the correspondance from oce name to RDI name as `q` -> "Correlation Magnitude", `a` -> "Echo Intensity", `g` -> "Percent Good".  I imagine that somewhere in this document they give units for these. Note that we store each in hexadecimal, so that's an extra complication in how to explain the unit for a `summary()`.

2. Naming is always hard!  I like `beamCorrectSpreading` except I wonder whether it's ambiguous (esp to those new to English).  The word "Correct" is both a verb and an adjective. We might imagine `dRaw` and `dCorrect` for some quantity d; here Correct is an adjective. Or in the verb form, a function `dCorrect()` might do a correction. In the present case we are talking about a function, so in my mind that means an action and therefore "Correct" is a verb. I looked up synonyms for correct, and found: adjust, regulate, fix, set, standardize, normalize, calibrate, fine-tune, rectify, amend, emend, remedy, repair.  I don't like any of these very much. So, my vote is for `correct` as the key word. Sounds like two votes for changing `beamUnspreadAdp()` to `beamCorrectAdp()`.  We might want to think of dropping the `Adp` part, since this only works for adp and not adv.

**Comment by dankelley** [comment] 2017-01-29 15:51
This issue seems to have gone stale. There is no problem in leaving issues open if tests or development is ongoing, but the developers do not like to leave users "high and dry" by mistake. Therefore, this is a request for a status update. If the issue is still active, perhaps someone can make a comment to that effect, ideally  with a suggested timetable or work-plan for resolution. Otherwise, this issue will become a candidate for closure by the developers, which is not the preferred scheme, since in "oce" we like reporters to be the ones to close issues. (This is a standardized reply.)

**Comment by richardsc** [comment] 2017-01-29 15:57
I've assigned the issue to me, and have started some working thinking about the `units` issue discussed above but also renaming the `adpUnspread...` function. I propose to leave open, even though the original general question from @Vinterwoo has mostly been addressed.

**Comment by dankelley** [comment] 2017-06-22 10:29
@richardsc -- I wonder if we can address the original question ("Given an OCE adp object, can you tell me if the [['a']] data is consider backscatter (distance corrected) or raw? If it is raw, is there a method in OCE to correct for distance?") by adding a sentence to the docs?

**Comment by dankelley** [comment] 2017-06-28 12:50
Meeting notes --

1. let's deprecate `beamUnspreadAdp` and rename it as ... to be determined by this Friday.

**Comment by dankelley** [comment] 2017-06-28 12:51
Also -- need to think about the units, and decide whether to include units in the metadata.

**Comment by dankelley** [comment] 2017-08-25 12:51
I'm looking at the open issues, because the time for a CRAN release seems to be drawing near. This particular issue seems to have stalled, with no recent comments. The original question was posted 8 months ago, and I suspect that @Vinterwoo has moved on, in that time.  It seems to me that there are three sensible choices here:
1. tackle this issue before a CRAN release (i.e. consider this a blocking issue)
2. leave the issue pending, and release to CRAN with it open
3. consider closing the issue, perhaps opening a new one if the original problem has been addressed and new problems have come up during discussion

The lack of comments over a long time usually implies either a tough issue or an issue of low interest. In this case, I think it must be the latter, since massive code refactoring would not be required to address the issue as originally posed.

**Comment by Vinterwoo** [comment] 2017-08-25 13:31
@Vinterwoo is still around, and still has interest if a solution can be found.

**Comment by richardsc** [comment] 2017-08-28 12:59
Apologies for letting this issue go stale -- I assigned it to myself but have focused on more intense fires since this one is mostly just an issue of documentation and nomenclature.

The answer to @Vinterwoo question is in my [comment](https://github.com/dankelley/oce/issues/1169#issuecomment-272229941) above, but then both @dankelley and I raised other issues that we think would be good to deal with. Since the title as posed is ambiguous enough, I'd like to keep the issue open for now.

However, I don't think that it is blocking for an oce release, meaning any changes as discussed will be incorporated into the *next* (as in, after the upcoming one) release.

**Comment by dankelley** [comment] 2018-05-15 13:17
The discussion of this issue seems to have ended, and the developers will likely close it soon, since it seems to have been addressed. This goes against the usual oce policy of hoping that reporters will close issues, so this is really a request to the original reporter to either (a) close the issue or (b) indicate that further action is desirable.

PS.  This is a standardized reply.

**Closed** 2018-05-15 23:28 UTC
Labels: adp

**Comment by Vinterwoo** [comment] 2018-05-15 23:31
Apologies for letting the issue go stale, I closed it off this evening.

Your work on this matter is greatly appreciated,

Vince
