### ISSUE TITLE
ctdDecimate() should perhaps have a `...` argument (e.g. for `na.rm=TRUE`)?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#2192] opened 2024-02-18 22:25 UTC
I just noticed that if a ctd object has some NAs in a field, and `ctdDecimate()` is used (e.g. wiith the default which does a simple boxcar mean), that the NAs will cause the entire bin to be missing. Normally, one would control this behaviour with an `na.rm=` argument, like the one in `mean()`.

I know that `ctdDecimate()` is quite sophisticated, and can handle `method=` arguments which are functions, so this could be accomplished that way. But it seems like the default method (which honestly most people are going to use because it is _very_ standard in the field) should allow for exclusion of NAs.

Of course, this function has been around for a long time, so we wouldn't want to change behaviour. But the default could still be set to `FALSE` so if the `...` arg (or however is decided as best to implement it) acheives the same result. It could be changed to spit a warning if NAs are detected.

**Comment by richardsc** [comment] 2024-02-18 22:31
I noticed that there are two instances of the "boxcar" implementation in `ctd.R` -- the first uses `binMean1D()`:

https://github.com/dankelley/oce/blob/e420a66eabb8ff1c57d14286a048163a28f72bb3/R/ctd.R#L2054

and the second uses `mean()`:

https://github.com/dankelley/oce/blob/e420a66eabb8ff1c57d14286a048163a28f72bb3/R/ctd.R#L2078

Note that `binMean1D()` _does_ have an `na.rm=` argument, however it isn't specified here. OTOH the `na.rm=` argument for the `mean()` call _is_ specified, as `TRUE`. 

So at the very least these two bits are going to give inconsistent results (though I'm not 100% sure what would trigger one vs the other).

**Comment by dankelley** [comment] 2024-02-18 22:40
Good find.  I think `ctdDecimate()` ought to have a `na.rm` argument.  As you say, it can be set to FALSE by default, so pre-existing scripts will still work.  (Some folks might have written code that detects a NA value and then does something and so making the default be TRUE would break their code.)

The code (including docs) spans from lines 1792 to 2141 so it's of moderate size.  Maybe the only method that needs adjustment is boxcar, but it would be necessary to look at them all.  I see that the boxcar one uses `binMean1D()`, and that it takes `na.rm` so a simple trial solution is just to add this as an arg.  (Maybe you said all this in the above.  I have a bad habit of just looking at a title and not what the other person has written.)

Do you need this soon?  I can look at this tomorrow or later this week, or you could look at it.

**Comment by richardsc** [comment] 2024-02-18 22:55
A quick fix for this (that isn't perfect, as it leaves an NA in the topmost bin ...) is to define a new function like:

```
boxcar <- function(x, y, xout) {
    dp <- diff(xout[1:2])
    pbreaks <- -dp / 2 + c(xout, tail(xout, 1) + dp)
    p <- x
    binMean1D(x, y, pbreaks, na.rm=TRUE)$result
}
```

Comparing the default behaviour with the new one:

``` r
library(oce)
#> Loading required package: gsw
data(ctd)
ctd[['temperature']][c(10, 20, 30, 40, 50)] <- NA
ctd1 <- ctdDecimate(ctd, p=1)
boxcar <- function(x, y, xout) {
    dp <- diff(xout[1:2])
    pbreaks <- -dp / 2 + c(xout, tail(xout, 1) + dp)
    p <- x
    binMean1D(x, y, pbreaks, na.rm=TRUE)$result
}
ctd2 <- ctdDecimate(ctd, p=1, method=boxcar)
ctd1[['temperature']]
#>  [1]        NA 14.217675 14.221173 14.177394        NA 12.757900        NA
#>  [8] 11.367763        NA 10.631646  9.889313        NA  9.270010        NA
#> [15]  8.948604  8.750449  8.450183  8.187470  7.907024  7.728340  7.704027
#> [22]  7.684461  7.641682  7.530185  7.370642  7.266145  7.114410  6.866554
#> [29]  6.799036  6.484307  6.026440  5.552774  4.922312  4.769560  4.564609
#> [36]  4.356659  4.202807  4.158744  3.605969  3.385925  3.373031  3.314089
#> [43]  3.135220  3.027180  2.935291
ctd2[['temperature']]
#>  [1]        NA 14.217675 14.221173 14.177394 14.103863 12.757900 11.845039
#>  [8] 11.367763 11.085478 10.631646  9.889313  9.485980  9.270010  9.035896
#> [15]  8.948604  8.750449  8.450183  8.187470  7.907024  7.728340  7.704027
#> [22]  7.684461  7.641682  7.530185  7.370642  7.266145  7.114410  6.866554
#> [29]  6.799036  6.484307  6.026440  5.552774  4.922312  4.769560  4.564609
#> [36]  4.356659  4.202807  4.158744  3.605969  3.385925  3.373031  3.314089
#> [43]  3.135220  3.027180  2.935291
```

<sup>Created on 2024-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment] 2024-02-18 22:56
Sorry, I was trying a solution while you were responding. 

Soon is good, but I can also just modify my local copy in the meantime, so it's not a big deal.

**Comment by dankelley** [comment] 2024-02-18 23:27
I can do it tomorrow morning. Thanks for the good idea. Enjoy ocean sciences!

**Comment by dankelley** [comment] 2024-02-19 01:51
I think it's fixed in "develop".  I need to check whether to use it in the other methods -- so far, it's only in "boxcar".  Also, I need to see if that last conditional is ever executed -- it may be a remnant.  Below is the commit note.  That code is now in the test suite.

commit 08f3084bf53780ddd08f695a55a702f62e6665f3
Author: dankelley <kelley.dan@gmail.com>
Date:   Sun Feb 18 21:49:23 2024 -0400

    ctdDecimate() has new na.rm argument
    
    See https://github.com/dankelley/oce/issues/2192 for discussion.
    
    Test code is below.
    
    ```R
    test_that("ctdDecimate() handles na.rm", {
        # See https://github.com/dankelley/oce/issues/2192
        # Insert NA temperature value within top (5-dbar) bin
        data("ctd")
        ctd2 <- ctd
        target <- 2
        i <- which.min(abs(target - ctd[["pressure"]]))
        ctd2@data$pressure[i]
        ctd2@data$temperature[i] <- NA
        p <- 5 # bin size
        CTD <- ctdDecimate(ctd, p = p)
        CTD2 <- ctdDecimate(ctd2, p = p)
        CTDnarm <- ctdDecimate(ctd, p = p, na.rm = TRUE)
        CTD2narm <- ctdDecimate(ctd2, p = p, na.rm = TRUE)
        expect_equal(as.vector(table(is.na(CTD[["temperature"]]))), 9)
        expect_equal(as.vector(table(is.na(CTDnarm[["temperature"]]))), 9)
        expect_equal(as.vector(table(is.na(CTD2[["temperature"]]))), c(8, 1))
        expect_equal(as.vector(table(is.na(CTD2narm[["temperature"]]))), 9)
    })
    ```

**Comment by dankelley** [comment] 2024-02-19 10:21
Here's a followup that is more like your example.  I think it is as expected.  (The top bin is NA because there are no data ia the 0 to 1dbar range.)

``` r
library(oce)
#> Loading required package: gsw
data("ctd")
a <- ctdDecimate(ctd)
cat(
    "Setting T to NA at p =",
    paste(ctd[["pressure"]][c(10, 20, 30, 40, 50)], collapse = " "), "\n"
)
#> Setting T to NA at p = 3.72 6.055 8.295 10.583 13.109
ctd[["temperature"]][c(10, 20, 30, 40, 50)] <- NA
b <- ctdDecimate(ctd)
c <- ctdDecimate(ctd, na.rm = TRUE)
df <- data.frame(
    p = a[["pressure"]],
    Tunaltered = a[["temperature"]],
    TalteredDefault = b[["temperature"]],
    TalteredNARM = c[["temperature"]]
)
print(df)
#>     p Tunaltered TalteredDefault TalteredNARM
#> 1   0         NA              NA           NA
#> 2   1  14.221087       14.217675    14.217675
#> 3   2  14.224586       14.221173    14.221173
#> 4   3  14.180797       14.177394    14.177394
#> 5   4  14.110264              NA    14.103863
#> 6   5  12.760962       12.757900    12.757900
#> 7   6  11.836679              NA    11.845039
#> 8   7  11.370491       11.367763    11.367763
#> 9   8  11.036884              NA    11.085478
#> 10  9  10.634198       10.631646    10.631646
#> 11 10   9.891686        9.889313     9.889313
#> 12 11   9.503544              NA     9.485980
#> 13 12   9.272235        9.270010     9.270010
#> 14 13   9.034932              NA     9.035896
#> 15 14   8.950752        8.948604     8.948604
#> 16 15   8.752549        8.750449     8.750449
#> 17 16   8.452211        8.450183     8.450183
#> 18 17   8.189435        8.187470     8.187470
#> 19 18   7.908922        7.907024     7.907024
#> 20 19   7.730195        7.728340     7.728340
#> 21 20   7.705876        7.704027     7.704027
#> 22 21   7.686305        7.684461     7.684461
#> 23 22   7.643516        7.641682     7.641682
#> 24 23   7.531992        7.530185     7.530185
#> 25 24   7.372411        7.370642     7.370642
#> 26 25   7.267889        7.266145     7.266145
#> 27 26   7.116117        7.114410     7.114410
#> 28 27   6.868202        6.866554     6.866554
#> 29 28   6.800668        6.799036     6.799036
#> 30 29   6.485863        6.484307     6.484307
#> 31 30   6.027887        6.026440     6.026440
#> 32 31   5.554107        5.552774     5.552774
#> 33 32   4.923493        4.922312     4.922312
#> 34 33   4.770705        4.769560     4.769560
#> 35 34   4.565704        4.564609     4.564609
#> 36 35   4.357704        4.356659     4.356659
#> 37 36   4.203816        4.202807     4.202807
#> 38 37   4.159742        4.158744     4.158744
#> 39 38   3.606834        3.605969     3.605969
#> 40 39   3.386737        3.385925     3.385925
#> 41 40   3.373840        3.373031     3.373031
#> 42 41   3.314884        3.314089     3.314089
#> 43 42   3.135972        3.135220     3.135220
#> 44 43   3.027907        3.027180     3.027180
#> 45 44   2.935995        2.935291     2.935291
```

<sup>Created on 2024-02-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment] 2024-02-19 11:03
The code was a bit of a tangle, so it took me a while to understand that final "else" block.  It was trying to capture both "boxcar" and "lm" methods.  But the "boxcar" had *already* been captured, so that part was moot.  Therefore the final "else" can become an "else if" that checksn for method "lm".

I have made this change. Below is a table of where the varioius "method" values are handled.  Not that the final "else" part reports an error stating that it is impossible to get there, and asks the user to report an issue.  But that ought not to happen unless new methods are added without checking in two spots: (a) an initial test on whether `method` is in an allowed list and (b) this long conditional sequence.

Here is a guidepost to the blocks (from a checklist I used in editing)

* `"approxML"` R/ctd.R line 1979
* `"approx"` R/ctd.R line 2006
* `"rr"` and `"unesco"` R/ctd.R line 2034
* `"boxcar"` R/ctd.R line 2053
* `"lm"` R/ctd.R line 2073
* none of the above: R/ctd.R line 2116 (error report)

**Comment by dankelley** [comment] 2024-02-19 11:10
I made a test, mainly just to see that they all didn't fail oddly with the recoding.  The warnings are to be expected, I think, being the result of trying to fit a line in a 1-decibar box that doesn't have enough points etc.

<details

``` r
options(warn = 1)
library(oce)
#> Loading required package: gsw
data(ctd)
methods <- c("approxML", "approx", "rr", "unesco", "boxcar", "lm", "junk")
for (method in methods) {
    cat("method=\"", method, "\"\n", sep = "")
    try(d <- ctdDecimate(ctd, method = method))
}
#> method="approxML"
#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values
#> method="approx"
#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values

#> Warning in regularize.values(x, y, ties, missing(ties), na.rm = na.rm):
#> collapsing to unique 'x' values
#> method="rr"
#> method="unesco"
#> method="boxcar"
#> method="lm"
#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases
#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases

#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases

#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases

#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases

#> Warning in predict.lm(m, newdata = list(xvar = pt[i])): prediction from
#> rank-deficient fit; attr(*, "non-estim") has doubtful cases
#> method="junk"
#> Error in ctdDecimate(ctd, method = method) : 
#>   unknown method 'junk'; valid methods are: 'boxcar', 'approx', 'approxML', 'lm', 'rr', 'unesco'
```

<sup>Created on 2024-02-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment] 2024-02-19 11:36
I just did local tests, rebuilt the webpage, and pushed it all to GH in "develop" commit fb905bd6741ffa1d660f40744133f83b4e552307.

PS. at present -- and this is documented -- `na.rm` applies only to the `boxcar` method.  The methods involving regression (`lm`, `approx` and `approxML`) are probably not affected by NA values, but I'll check on that.  I'll also check `rr` and `unesco`.  But the main method is `boxcar`, I think, so the code ought to be OK for your use-case, @richardsc.

**Comment by dankelley** [comment] 2024-02-19 11:40
Examination of `oceApprox()` in `R/oce.R` indicates that the `rr` and `unesco` methods already work as though `na.rm` had been set to TRUE, so they are okay. 

What I mean is that these algorithms are not set up to handle NA values, so they get trimmed. Therefore there is no reason to propagate an `na.rm` value to `oceApprox()`, because if it is FALSE then the methods would produce junk.

NEXT: I'll check `approx`, `approxML` and `lm`.

**Comment by dankelley** [comment] 2024-02-19 11:44
Code inspection of `approx` and `approxML` shows that they are immune to NA values.  A test reprex is below.

``` r
x <- 1:10
y <- sin(x)
y <- sin(x / 10)
y[5] <- NA
a <- approx(x, y)
plot(x, y)
lines(a, col = 2)
```

![](https://i.imgur.com/ZbAN871.png)

<sup>Created on 2024-02-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment] 2024-02-19 11:47
And here's a reprex showing that the `lm` method is already immune to NA values.  This concludes tests of all possible cases.  I think the issue can now be evaluated by @richardsc using real data.

``` r
x <- 1:10
y <- sin(x)
y <- sin(x / 10)
y[5] <- NA
m <- lm(y ~ x)
plot(x, y)
abline(m, col = 2)
```

![](https://i.imgur.com/mCLf73S.png)

<sup>Created on 2024-02-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by richardsc** [comment] 2024-02-24 03:10
I checked this and thought I replied, but must have only replied in email? Anyway, I believe this is fixed now. Thanks!

**Closed** 2024-02-24 03:10 UTC
Labels: ctd
