### ISSUE TITLE
sectionSmooth() error when providing xg and yg for barnes method

### ISSUE THREAD

**Issue by clayton33** [dankelley/oce#1583] opened 2019-07-17 12:06 UTC
### Short summary of problem

I'm trying to do barnes interpolation on sections with a pre-defined grid, but I'm getting an error when supplying the ``xg`` and ``yg`` arguments.

### What you did

Here's some example code using ``data(section)``

```
library(oce)
data(section)
gs <- subset(section, 115<=stationId&stationId<=125)

xgrid <- seq(0, ceiling(max(gs[['distance', 'byStation']])), by = 1)
ygrid <- seq(5, ceiling(max(gs[['pressure']])), by = 5)
# Barnes
gsBarnes <- sectionSmooth(gs, "barnes", xg = xgrid, yg = ygrid)
```

when running the above, I get the error

```
Error in section@data$station[[i]] : subscript out of bounds
```
Running the ``sectionSmooth`` function with ``debug = 4`` (randomly chosen number), it is able to smooth everything, but digging into the code, it looks like the issue might lie around line 2918 (?) in ``section.R`` develop branch.

### How urgent is this?

Not very urgent, but would be nice to get this figured out.

### Output from sessionInfo()
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] oce_1.1-1      gsw_1.0-5      testthat_2.1.1

loaded via a namespace (and not attached):
[1] compiler_3.5.0 magrittr_1.5   R6_2.4.0       tools_3.5.0    Rcpp_1.0.1     rlang_0.4.0 
```

**Comment by dankelley** [comment] 2019-07-17 13:44
I'll look this afternoon, if that's soon enough.

**Comment by clayton33** [comment] 2019-07-17 13:45
Yes, that's fine, no rush.

**Comment by dankelley** [comment] 2019-07-17 17:36
I see the problem but I also want to figure out why (sometimes) the results cannot be plotted.  (I think there may be a problem in how the other barnes parameters are being set.)  It may take me a while to sort through this. I will also add some tests to the build-test suite, so this problem cannot come back later. (I must not have tested this ... I find barnes so slow that I don't tend to use it, plus I like seeing contours jig-jag on the stations and never quite trust smoothing methods.)

**Comment by dankelley** [comment] 2019-07-19 13:09
Oh, I think I see the plotting problem now. This sample code had some xgrid values that exceeded the data range.  That causes some `NaN` values to appear in a variable (`xx`) within the plotting code. I'll look through `interpBarnes`, `sectionSmooth`, and `plot,section-method` to see where's the best place to change the `NaN` to a `NA`, and then to regard it as a non-problem.

**Comment by dankelley** [comment] 2019-07-19 13:35
@clayton33 -- question for you at the end. I'm a bit stuck on the right way to go forward.

The problem arises in `R/section.R` near line 2942 (the exact line number may change because I'm adding and removing debugging lines as I work on this), which reads
```R
    res@metadata$longitude <- approx(x, section[["longitude", "byStation"]], xg)$y
```

For the provided test case, this gives a `NA` value at the end, because the grid is extending beyond the data (owing to the `ceiling()` call).

I am not too sure what I ought to do about this. On the one hand, I can see an argument to let the user specify whatever grid they like, even if it goes beyond the data.  On the other hand, that grid might go up onto land ... and, besides, what do we do about the bottom, which is unknown outside the data (unless we start supplying a high-resolution bathymetry with oce).

We are using `approx()` to interpolate the station locations. Its `rule` argument lets us make out-of-range values be either `NA` (the default, used at this moment) or to repeat the last  point. Doing the latter is not good for plotting (two stations will then collide). I guess I could try to extrapolate, but how, exactly?  One option might be to linearly extrapolate using the last station and the station just preceding it. But what makes those two stations special? Maybe we ought to fit a line to all the data ... but that could have a jag at the end.

I do not quite see a sensible way to interpolate.

My inclination is to simply make `sectionSmooth` trim the `xgrid` values to those that exist in the dataset. @clayton33 does this seem reasonable to you?

**Comment by dankelley** [comment] 2019-07-19 15:38
@clayton33 -- there's a question for you (and @richardsc, if he's around) at the end of this comment.

Semi-fixed in the "develop" branch, commit fca694341422757bd7d0cda6e57f026fc2ec8d6a

As a workaround, I've made the `approx()` use `rule=2`, so we don't get `NA` values in the interpolated station longitudes and latitudes.

I also updated the plotting code, fixing an error that was occurring there (caused by `NA` for station locations).

I am not sure I like what I've done. What happens (with your test code) is that the last station in the result of `sectionSmooth()` has the same lon and lat as the second-last. That prevents the errors, and lets us get a plot, but it doesn't make much sense to me.  (What if the user set up an `xgrid` with a hundred out-of-range points?)  The problem is basically that the `xgrid` in this case is distance ... and I don't see any good way to extrapolate to the lon and lat values that are to go into the output object.  I guess we could take the two final stations in the input object and extrapolate them outwards, making up stations that would go on a straight line on a map. But that's weird, and also sensitive to the exact locations of just those two input stations.  **My conclusion:** we ought to simply trim the grid to fit inside the data.  So, if `distance` goes from say 0 to 100km, we trim the `xgrid` to that range.

@clayton33 -- what do you think of "my conclusion" in previous paragraph?

**Comment by clayton33** [comment] 2019-07-19 18:03
Answers from previous 2 comments, (sorry the more delayed response than usual, I had a meeting and then I moved cubicles today :) )

1. Agree that you should trim to what exists in the data.

2. Yes, I think it is sensible to trim to distance, the lat,lon problem seems tricky.

So now if xg and yg are supplied, and say you're supplying barnes with 10 stations, but your xg, say, has length of 100, will sectionSmooth then output with 100 stations or spit back out the interpolated values for those 10 stations ?

**Comment by dankelley** [comment] 2019-07-19 18:14
Re "so now": the scheme will be to obey your `xg`, but to trim it to the limits calculated from the data.  So for example, if your data go from distance 0 to 109, and you set `xg<-seq(0,200,5)` then the output stations would at distances 0, 5, 10, ... 90, 95, 100, 105 (a vector of 22 elements).  The lon and lat would all be non-NA, and they would be inferred from, basically, `approx(datax, datalongitude, xgrid)`, i.e. if you were to plot the resultant, there would be 22 stations, and they would be along lines made by the the original stations.  The number of output stations will be set by the grid (after trimming), not by the number of input stations.

This is a bit hard to explain. I'll code it, and try to write a cleaner explanation in the docs.  I will likely do that tomorrow morning, since I've got some other things I wanted to get done during working hours today.

Let me know whether the above halfway makes sense.

**Comment by clayton33** [comment] 2019-07-19 18:15
Yes, that makes sense.

**Comment by dankelley** [comment] 2019-07-20 12:17
I think the new form (in which the output grid's `xg` gets trimmed to the range of the data station's `x`) is working now in the "develop" branch, commit 26b6261aab71a0f51a75f5ee52da54345f4b7422

The code works for

* https://github.com/dankelley/oce-issues/blob/master/15xx/1583/1583a.R
* https://github.com/dankelley/oce-issues/blob/master/15xx/1584/1584a.R

in the oce-issues suite, and for

* https://github.com/dankelley/oce/blob/develop/tests/testthat/test_section.R

in the oce build-test suite.

I have not done a lot of testing (e.g. on what happens if "x" is "latitude" or "longitude", as opposed to "distance") so it would be sensible to keep an eye out for problems.  However, I think the new code is ready for evaluation by @clayton33, who I ask to either close the issue (if things are okay) or add new comments (if not).

I'm glad this issue got pointed out. The first problem was a simple copy/paste typo, but then I saw other problems as well.  I think I only use sections in my own work about once a year, for classes.  So, it's great to have someone else using the code and looking for errors or chances for new features.

**Closed** 2019-07-22 12:37 UTC
Labels: bug
