### ISSUE TITLE
handleFlags for Argo

### ISSUE THREAD

**Issue by AnneMTreasure** [dankelley/oce#1191] opened 2017-02-06 10:40 UTC
Hi there,

I just wondered if the `handleFlags() `function was resolved for Argo? I think the last discussion on this was in issue #896?

I'm a bit unclear on how to use it? Does the function perform default quality control if just used as is, or do I need to provide settings. For example, if I want to 'throw out' flags 0 and 3:9, do I write: 

`qc <- handleFlags(ArgoData, flags=list(all=c(0, 3:9)), action=list("NA"))`

Thanks so much,
Anne

**Comment by dankelley** [comment] 2017-02-06 11:27
The issue was closed, so that's a bit of indication that it has been addressed. Of course bugs can reappear, so please do some tests on your own data to see if you think it is working. Naturally, we'd be happy to try to help (we'd need a private copy of a data file, and test code posted here).

PS. because we don't like it when bugs reappear, we try to put tests in the "built-test" suite. The way those work is that the package simply will not build, if any tests fail. In a sense, then, these tests provide strong documentation. Please have a look at the test of the handling of argo flags at https://github.com/dankelley/oce/blob/develop/tests/testthat/test_flags.R (starting at line 32), which might clarify how things work, and might help you to do tests of your own. (The test I mention is only on the number of `NA` values ... it would of course be better to have individual tests of individual elements ... I may add that, this evening.)

**Comment by AnneMTreasure** [comment] 2017-02-06 13:00
Hi,

I think I'm probably not understanding how `handleFlags()` works. I will send a copy of one of the files I am working with as an example. To try and understand how it works, I ran the following code - findings in comments:

```
library(oce)

orig_file <- read.argo(file = "ct21-36-07_prof.nc")

# 'flags <- orig_file[['flags']]' and 'str(orig_file)' shows flags from 1:9

# test handleFlags using default settings:
qc1_orig_file <- handleFlags(orig_file)

# test handleFlags with own specs:
qc2_orig_file = handleFlags(orig_file, flags=list(all=c(0, 3:9)), action=list("NA"))

# test handleFlags with own specs:
qc3_orig_file = handleFlags(orig_file, flags=list(all=c(3:9)), action=list("NA"))

# test handleFlags with own specs:
qc4_orig_file = handleFlags(orig_file, flags=list(all=c(1,2)), action=list("NA"))


# looking at the summary output for the above 4 scenarios, the 3 cases where I have changed
the handleFlags() settings produce the same output. The output for these differ from the
default settings though (which sets the min, mean and max of salinity to NA?):

summary(qc1_orig_file)  # min, mean and max of salinity is NA?

summary(qc2_orig_file) # get a slightly different ouput to the default settings

summary(qc3_orig_file) # no change from qc2?

summary(qc4_orig_file) # no change from qc2?
```

My main query therefore is whether my understanding of how to change the default settings is correct, i.e. in this code:

`handleFlags(orig_file, flags=list(all=c(0, 3:9)), action=list("NA"))`

my understanding is that all rows that have flags 0 & 3:9 for any of the variables will be replaced with NA (and therefore excluded from analyses such as summary output?)

Thanks so much,
Anne

**Comment by dankelley** [comment] 2017-02-06 17:44
I'll set up some test code.  I'm not sure `summary` is the best test. I think what should be done is to find the indices of some bad data, and to see if the result from `handleFlags` changes the values to `NA`. That will require some detective work. 

I've done some of this but I'd like you to help if you can, Anne. Below you can see some steps.

```R
library(oce)
d <- read.argo("~/Desktop/ct21-36-07_prof.nc")
d1 <- handleFlags(d)
d[["salinity"]][17,395] # gives 34.4717
d1[["salinity"]][17,395] # gives NA
```
which looks OK to me.  BTW, the reason I picked these indices was because I did
```R
d[["salinityFlag]]==4
```
and looked at the output. The last one in the listed output was flagged with value 4.

Also, I did some more detective work on the flags in your file. The below indicates that the only flags in your whole file are 1 and 4.  So that may explain other details.
```R
library(oce)
d <- read.argo("~/Desktop/ct21-36-07_prof.nc")
## learn what sort of flats we have
for(flag in 0:5) {
    cat("flag", flag, "\n") 
    for (name in names(d[["flags"]])) {
        cat("  ", name, "has", sum(d[["flags"]][[name]]==flag),"flagged\n")
    }
}
```

PS. my testing will go into https://github.com/dankelley/oce-issues/blob/master/11xx/1191/1191a.R

**Comment by dankelley** [comment] 2017-02-06 18:17
Below is another test. I will put something along these lines into the test suite. I think I should add this to the docs also (but not the whole output)
```R
library(oce)
data(argo)
f <- argo[["salinityFlag"]][,2] # first column with a flag=4 entry
argoNew <- handleFlags(argo)
df <- data.frame(flag=f, orig=argo[["salinity"]][,2], new=argoNew[["salinity"]][,2])
head(df, 15)
```
which gives as below (looks right to me)
```
   flag   orig    new
1     1 35.193 35.193
2     1 35.193 35.193
3     1 35.194 35.194
4     1 35.198 35.198
5     1 35.200 35.200
6     1 35.201 35.201
7     1 35.201 35.201
8     1 35.202 35.202
9     1 35.205 35.205
10    1 35.209 35.209
11    1 35.207 35.207
12    1 35.207 35.207
13    4 35.209     NA
14    1 35.207 35.207
15    1 35.207 35.207
```

**Comment by dankelley** [comment] 2017-02-06 18:24
I've added a pared-down version of the just-previous comment to the docs for `?"handleFlags,argo-method"`

**Comment by dankelley** [comment] 2017-02-06 18:46
I'm building in some tests, and am seeing a problem in one of them. I'll report more when I've figured things out. In the meantime, please hold tight...

**Comment by dankelley** [comment] 2017-02-06 20:01
My previous comment was in error. I don't think anything is wrong. Anne (and Clark, if you get time later in the week) please check out the test code at https://github.com/dankelley/oce-issues/blob/master/11xx/1191/1191a.R or, better, do `git pull` on the repo. (You need to copy the private `.nc` file into the directory for the test to work.) Then please examine the `.R` code and the `.out` output. 

@AnneMTreasure -- if you agree that things are ok, Anne, please write a comment and close this. Otherwise, feel free to pose more questions on this thread or in a new issue. (Remember, we like issue titles to be narrow and precise.) Don't be shy about asking. This `handleFlags` code is new, and your questions will likely stem from inadequate documentation, so you're helping us to improve oce for others, when you ask your questions.

**Comment by AnneMTreasure** [comment] 2017-02-07 08:28
Hi there,

Thanks for all the tests. I've run through all of them with my example file and found the following:

In looking at what sort of flags we have, I find we also have a flag 9 (I haven't pasted the whole output here, but will do so if you'd like to see it?):

```
library(oce)
d <- read.argo("~/Desktop/ct21-36-07_prof.nc")

for(flag in 0:9) {
                cat("flag", flag, "\n") 
                for (name in names(d[["flags"]])) {
                        cat("  ", name, "has", sum(d[["flags"]][[name]]==flag, na.rm=TRUE),"flagged\n")
                }
        }

```
I also found this when I extracted the flags using `flags <- d[['flags']]` above to have a look.

Using the test code on [https://github.com/dankelley/oce-issues/blob/master/11xx/1191/1191a.R](url) I get different results to the expected:

```
library(oce)
d <- read.argo("~/Desktop/ct21-36-07_prof.nc")

d1 <- handleFlags(d)               # 1=good 4=bad
d2 <- handleFlags(d, flags=list(all=c(0, 3:9)), action=list("NA")) # expect same output as d1
d3 <- handleFlags(d, flags=list(all=c(3:9)), action=list("NA"))
d4 <- handleFlags(d, flags=list(all=c(1,2)), action=list("NA")) # should differ from d1

summary(d)
summary(d1)
summary(d2)
summary(d3)
summary(d4)
```

Unexpected, I get different output for summary(d1) and summary(d2)
As expected, output for d2 and d3 is the same
Unexpected, the output for d4 and d3 and d2 is the same (and all different from d1)


The results of the next test you provided look good to me:

```
library(oce)
d <- read.argo("~/Desktop/ct21-36-07_prof.nc")

f <- d[["salinityFlag"]][,1] # first column with a flag=4 entry
argoNew <- handleFlags(d)
df <- data.frame(flag=f, orig=d[["salinity"]][,1], new=argoNew[["salinity"]][,1])
head(df, 15)
```

gives the ouput:

```
   flag    orig new
1     4 34.2020  NA
2     4 34.2079  NA
3     4 34.0949  NA
4     4 34.1234  NA
5     4 34.3380  NA
6     4 34.4144  NA
7     4 34.4035  NA
8     4 34.4149  NA
9     4 34.3692  NA
10    4 34.4357  NA
11    4 34.4196  NA
12    4 34.4304  NA
13    4 34.3985  NA
14    4 34.3977  NA
15    4 34.5287  NA
```

So it is just the test code on [https://github.com/dankelley/oce-issues/blob/master/11xx/1191/1191a.R](url) that is not working for me?

Thanks so much for your help,
Anne

**Comment by dankelley** [comment] 2017-02-07 10:20
I updated https://github.com/dankelley/oce-issues/blob/master/11xx/1191/1191a.R with new expectations and better formatting.  Can you rebuild `oce` from github (I forget to remind people of that) and also pull the test case again and try it?   The test case has new expectations listed. It also states what I find, and I am getting `[OK]` in each case. If you are not finding ok, please email me your `1191a.out` file. (We don't want such long files in the comments.)

I have a bunch of meetings today, and so I have another request -- if you do not find that things seem to work, please go into the matrices and find a test case where it fails.  I'll need something specific. I would also need to see your reasoning as to the expected results. (For example, my reasoning was faulty because you had this `flag=9` case that I had never heard of.)

One more thing. At http://www.argo.ucsd.edu/Argo_date_guide.html I see the possible flags listed as 0 to 4. I wonder how you got a flag of 9? Maybe the official docs are wrong? Or is this a nonstandard argo?

PS. I am thinking of making `summary` also list some stats on flags. If we had that, then I would have noticed that you have this weird flag=9 condition from the start, and it would have been obvious that my initial reasoning had been wrong. I was thinking that your code used up to 9 just for caution ... not too bright of me!

**Comment by dankelley** [comment] 2017-02-07 10:22
PS. amusing, I did a search for 'argo flag 9' and got http://www.argoflag.com/product-page/03affc35-3c4b-b465-5bb7-7f0c5be3304e which is a somewhat different topic.

**Comment by dankelley** [comment] 2017-02-07 10:29
OK, now at http://www.argodatamgt.org/content/download/15699/102401/file/argo-quality-control-manual-version2.8.pdf (table 4.1) I see that flag=9 means missing data. I will therefore add this to the default test case, but *only* after we get clarity on the present case.

**Comment by dankelley** [comment] 2017-02-14 12:31
This issue seems to have gone stale. There is no problem in leaving issues open if tests or development is ongoing, but the developers do not like to leave users "high and dry" by mistake. Therefore, this is a request for a status update. If the issue is still active, perhaps someone can make a comment to that effect, ideally  with a suggested timetable or work-plan for resolution. Otherwise, this issue will become a candidate for closure by the developers, which is not the preferred scheme, since in "oce" we like reporters to be the ones to close issues. (This is a standardized reply.)

**Comment by dankelley** [comment] 2017-02-15 21:22
sorry, I closed this by mistake. Dan.

**Comment by richardsc** [comment] 2017-03-21 01:30
This issue got lost from my radar. @dankelley, let's chat about it in person to see what needs to be done.

**Comment by dankelley** [comment] 2017-05-10 11:10
@richardsc -- let's chat about this when we next meet in person.

**Comment by dankelley** [comment] 2017-05-13 12:59
This issue has stagnated, because I think we all got busy with other things. Another problem was that nobody was assigned to address the issue. To get things back on track, I have just assigned myself. My first action, tricky little weasel that I am, is to put the ball back into its original court by asking @AnneMTreasure whether things work in the present `development` branch. If not, please state clearly what behaviour you're looking for, and provide test code and data.

It is possible that I'll change the issue title. I like to have titles that are fine-grained, and that are phrased in such a way that it will be clear when to close the issue. For example, it might be "handleFlags,argo-method does not handle flag=9" (which I sort of think was the original problem, but that's been addressed for months).

Thanks!

**Comment by dankelley** [comment] 2017-05-22 19:25
**Standardized comment.** This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.

**Closed by dankelley** 2017-05-22 19:25 UTC
