### ISSUE TITLE
Add an `add=TRUE` arg for overlaying on section plots

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#996] opened 2016-06-23 18:21 UTC
Inspired by #995 , it might be a good idea to have an `add=TRUE` for section plots, so that other types of section plots can be overlain, (e.g. density contours over an image plot of temperature).

**Comment by dankelley** [comment] 2016-06-23 18:29
This is a good idea, and a lot easier than asking the user to figure out how to extract data from the object because of the gridding aspect.

**Comment by dankelley** [comment] 2016-06-25 13:20
Prescript: this is a long and meandering post, a sort of thinking-out-loud essay. It starts with some problems I see in the suggestion (as described in the title) and ends with what I think will give the users something that will be easier to use (and understand) and an awful lot easier to code. (I say the second because I've started playing with the code, to permit `add`, and it is quite complex, probably requiring a couple of dozen modifications that could have ripple effects.)  I hope that both @richardsc and @porterdf will have a quick look at this, and perhaps offer their thoughts. I apologize in advance that this is quite meandering ... a Saturday morning chat while listening to CBC talking about brexit. --DK.

I'm starting to wonder if this is going to help, or confuse, users. For example, what if the second call (or a third call, etc.) chooses a different x axis, or y axis? Then we'd need to put new axes on the plot, which raises some issues:
1. The user would have to set up wide margins, knowing how many axes would be drawn. *Comment:* That's not too much to ask, I think.
2. Require oce to remember something about the graphics state, so it would know where to put the new axis. That is not very R-like, though, which argues against this. *Comment:* A solution would be to add new arguments on where to place axes, which again is not too much to ask.

Another factor is the bottom trace. If the x axis is changed then the trace will change. Do we plot two bottoms, then? I think that would be totally confusing and should lead to an error message, but the only way to "know" that things have changed would be to store a lot of info from the previous plot, which is not in the "R way".  (The "R way" stores only a very few things about the plot, mainly `mar` or equivalently `mai`, and `usr`, and also info on the tic locations and whether log or non-log).

All of these problems can be solved by having a lock-out in arguments, i.e. if `add=TRUE`, we would *only* examine e.g. `which` (and check that it is a vector of single length), plus a few other things.  Well, that could be done (although a coding nightmare).  Now, another problem: what if the previous version was an image and the new one is also an image? Is that useful? No, because images overpaint.

I'm thinking as I write this, so I know this is a bit meandering. What I am coming to, as I write this, is that maybe we should *not* do as the title suggests. It is complex for the code, not R-like, and may be quite  confusing to the user, with the special cases (i.e. it's confusing to read that an arg means such-and-such, except if another argument is TRUE, in which case the arg is skipped).

We may gain by thinking about how R itself works. In the main R system, the user makes a plot with ``plot()`` and then adds things with e.g. ``points()``, ``lines()``, ``contour(..., ADD=TRUE)`` and so forth. Now, these will all "just work", so long as we provide good interfaces to the data (including gridded data).

Now, they can get the raw data with existing `[[` calls. So that's no problem, for drawing data points, etc.  Below is an example of that, colour-coding so we can see med water, etc.
```R
library(oce)
data(section)
plot(section, which='salinity')
distance <- section[['distance']]
pressure <- section[['pressure']]
salinity <- section[['salinity']]
temperature<-section[['temperature']]
points(distance, pressure, col=ifelse(salinity<35.7&temperature<15,'red','blue'))
```

As for the gridded data, we have something tricky regarding state. If the `plot()` call is with a gridded object, then the user already has that, and therefore they could do whatever they want with it. However, if `plot()` was given an ungridded section, then the user won't know how to grid, to get corresponding fields. But there's a simple solution to that: `plot()` should return (silently) the gridded object. That's a one-line change. Then all I need to do is to ensure that `[[` can be used to retrieve the grid (as opposed to the data), and then we are done, with no need to alter either `plot()` or `oceContour()`.

Your thoughts, @richardsc and @porterdf ?

**Comment by dankelley** [comment] 2016-06-25 22:57
An addendum to last post: in the `kelley` branch, the code (from the doc)
```R
## 4. Image of temperature, with a high-salinity contour on top;
##    note the Mediterranean water.
sec <- plot(section, which='temperature', ztype='image')
S <- sec[["salinity", "grid:distance-pressure"]]
contour(S$distance, S$pressure, S$field, level=35.8, lwd=3, add=TRUE)
```
yields as below
<img width="574" alt="screen shot 2016-06-25 at 7 51 02 pm" src="https://cloud.githubusercontent.com/assets/99469/16359547/018333d4-3b0f-11e6-894a-4b20aaab2391.png">

**Comment by richardsc** [comment] 2016-06-26 02:06
Interesting. I think in some ways you're overthinking this (e.g. multiple axes), but ultimately you're probably right about causing confusion. I like the idea of returning gridded objects, which would be a lot simpler than overhauling the `plot.section()` code with lots of conditionals. I'll try the `kelley` branch over the next few days and see what I think.

Has the `[[..., 'grid:']]` functionality always been there, or was that new for this issue. If that's the solution for this, I think we'll want to think more about the syntax (I was confused as to why `distance` and `pressure` were being subtracted, which is what it looks like ... )

**Comment by dankelley** [comment] 2016-06-26 11:05
Thanks. The syntax was very provisional, and I realized later that I want to change to be e.g. `section[["salinityGrid"]]` etc because then it's similar to `"salinityFlag"` and `"salinityUnit"` etc. **The coding will be a lot easier if we get clarity on this issue now, so, @richardsc , please weigh in on this by adding a comment below.**

Then we have the question about telling it what kind of grid to get. (**Aside:** we have to tell it *something* unless I make `plot,section-method` store that information in the state ... and R discourages storing state, apart from `par` things.) As I coded for `"distance-pressure"` I was thinking of an analogy to `"x-y"` as for normal plots. But you read it as subtraction, so my analogy was poor!  

Note that the `[[` generic has arguments `i`, `j` and `...`. That means we could let the user specify the x and y variables directly, if we want.  I don't know if that would be more confusing, or less confusing. Right now I lean towards more confusing, but I could be argued out of that. (I'd still need to check that it was legit and R-like. TBH I'm not sure why it permits the `[[` as I've coded it. The generic is supposed to have the argument `exact` in there after the dots, but I don't have that. I guess it's using the rule that things after dots are not checked for consistency.)

It will be easier, I think, to just write down some possible schemes and get opinions. That's below. I'm voting between -1 and 1, fractional. If you do the same, with -1 meaning "no, I can't stand that" and +1 meaning "this is the total solution" then we can probably just add them up to decide, perhaps after one more pass.  This stuff needs to get settled because once things get into code, they are hard to alter.  Also, we need to bear in mind that our ideas could get extended later for other things, besides section grids!
Clark, please edit the below with your votes. I won't bother trying to name schemes; they will just be exemplified.

1. ``section[["salinity", "grid", "distance-pressure"]]` DK -0.5, CR ?

2. ``section[["salinityGrid", "distance-pressure"]]` DK 0.5, CR ?

3. ``section[["salinityGrid", "pressure versus distance"]]` DK 0, CR ?

4. ``section[["salinityGrid", "pressure*distance"]]` DK -0.5, CR ?

5. ``section[["salinityGrid", "x=distance,y=pressure"]]` DK -0.7, CR ?

Any others Clark wants to add... just go ahead.

**Comment by richardsc** [comment] 2016-06-26 23:38
I will vote when I'm ready, but first some clarification on what the arguments for the `[[` generic can be, and some of my own thinking out loud ... :)

You mentioned that they are `i`, `j`, and `...`. So that would suggest to me that one could do something like: `section[["salinity", grid=TRUE, x="distance", y="pressure")`. While it's more typing than most of the options above, if such a syntax was possible I think that would make a lot of sense, as it behaves similarly to a "functional" approach to manipulating and extracting information from an object.

Writing the above reminded me that we currently have a *function* called `sectionGrid()`, which does **half** of what we're talking about here -- it puts each `station` object in the section onto a uniform vertical grid. But it inherently has no information one the "x" gridding, because that depends on the desired coordinate, and the coordinate is derived from information contained in the `section` object.

No solutions in my mind yet ... just thinking out loud. Perhaps a phone call would be good to sort this out a bit better.

**Comment by richardsc** [comment] 2016-06-27 02:24
Thinking about the issue a bit more, I actually don't see why `sectionGrid()` couldn't be tweaked to do what we want here. Particularly, why does the "x" variable have to be specified at all? Currently (at least based on my understanding) the *values* for the x-axis used when making a contour or image plot of a section are simply pulled from the object itself -- that is, they are either `distance`, `longitude`, `time`, etc. What is required to "grid" the section to an array is to interpolate each cast to regular pressure levels and then "stack" the profiles into a matrix. Really, this is the same sort of structure as an `argo` object which has been run through `argoGrid()`.

Maybe I've got the gridding procedure wrong (I haven't had a good dig through the code yet), but what if `sectionGrid()` had an argument to return *matrices* of the fields instead of a standard `section` object? The syntax might be something like:
```r
plot(section, which='temperature', ztype='image')
SG <- sectionGrid(section, matrix=TRUE)
contour(SG[['distance']], SG[['pressure']], SG[['salinity']], level=35.8, add=TRUE)
```

In any case, I think a phone call would be good -- this is starting to veer way off the original issue title into the land of never ending UI improvements. I do like where this is going though -- as I have often found sections a bit tricky to work with beyond summary plots.

**Comment by dankelley** [comment] 2016-06-27 09:19
This is probably good for a phonecall. If you're able, my 'usual time' of 1030 would be fine today, or tomorrow (but only a short call tomorrow since another meeting at 1100). This is all tricky stuff. And you're right on something I hadn't thought of: we should think of `argo` also, because we need things to be similar across oce.

The core issue is of synching up with the previous plot call. I had the idea of using the return value from `plot` to do it. Your method does not really work (I think) because we would have to hope that the args to `sectionGrid` called by the user will be the same as those called by `plot`, which is a lot to ask. (Even just consider the choice of whether x is distance, longitude, time, etc, and y is depth, z, pressure, etc.) I prefer not to demand that users weave the calls together properly, because we can already have the return value to work with, and we can know for sure that it is right.
```R
sg <- plot(section, which='temperature', ztype='image')
SG <- sectionGrid(sg, matrix=TRUE)
contour(SG[['distance']], SG[['pressure']], SG[['salinity']], level=35.8, add=TRUE)
```
but I see a better way.  If we have `sectionGrid` with this new `matrix` argument, we just call it that way inside `plot`. Then users can write
```R
SG <- plot(section, which='temperature', ztype='image')
contour(SG[['distance']], SG[['pressure']], SG[['salinity']], level=35.8, add=TRUE)
```
which is simpler for them, I think.  

PS. in all of these, we are assuming that the user will realize that their plot had e.g. `pressure` on the y axis.  We don't quite have to do that, though. We could have `SG[['x']]` etc. in the `SG` object, perhaps in addition to `distance`, and in fact that is how I'd always call the code because I don't like assumptions.

**Comment by porterdf** [comment] 2016-06-27 21:31
Hey guys, sorry for the apparent radio silence from me, but you move super fast (!) and my lack of familiarity with the inner workings of ‘oce’ means I’ve always been a few emails behind. I have been following along, and I do find it quite interesting, just without anything too interesting to say.  However, I felt compelled to respond to this last email because I find this last suggestion by Dan to be very usable.  Obviously your understanding of where it fits into the rest of oce trumps (sorry!) it, but this seems like a very usable and understandable function.  Pertaining to this last suggestion:

1) Intuitive syntax 
2) Adding a single contour line of either the already filled variable or a different variable is immediately useful.  
3) Could a vector be supplied for the ‘level’ field, e.g. seq(33,34,0.05)?  Or would we need to loop here?
4) I don’t ever anticipate overplotting with a different x axis, and only slightly more likely with a different y axis. Of course, this is not reason to exclude this functionality, just giving my own personal view
5) I would not be offended to specify the y-coordinate in the original call to plot.  In other words, what about forcing user to include 

I’ve got a few other draft emails I’ll send along soon, but this is if for now.  I also have a few bugs to report, but not obviously reproducible using oce-data, so I might need to send along a few data files.  

Dave

**Comment by dankelley** [comment] 2016-06-27 21:42
Hi Dave. Clark and I talked about this on the phone, and he reminded me that other `oce` plotting functions have an `add` argument, and so I am inclined to code things in that way. We are not immediately close to any of these solutions, and are at the moment mostly concerned with how things would look to the user. As of now, with the `add` syntax, one might write something like
```R
plot(sec, which='salinity')
plot(sec, which='temperature', add=TRUE)
```
where `sec` is a section object.  The trick (for coding and documenting) will be that when `add=TRUE` is the case, a lot of other arguments will get ignored, to avoid e.g. one call having the vertical axis be pressure, and the other call being z (negative numbers).

We are planning a release to CRAN on Canada Day (July 1, if you're not familiar with this) and so certainly none of this new stuff will go into that release.  For this reason, and generally, there is **no problem at all** in being a bit slow to respond!! Clark and I discussed, in our phone meeting today, how much we appreciate input from people like you. This sort of request can only help to make `oce` better for all users ... including us, when we are in a panic to write a proposal or paper, and we can take advantage of something coded to help someone else, when *they* were in a panic :-)

PS. I trimmed some stuff from your comment. It seems you replied by email. It's a good idea to instead click the link and reply in the text box on the web. That way, there's never a problem with accidentally including info like phone numbers, etc.

**Comment by dankelley** [comment] 2016-06-27 21:48
Sorry, I was wrong in the last. I should have said that axis-related arguments in the second call will *not* be ignored, and *must* be identical to the first, or else odd things will happen. The other syntax, which I had devised and upon which you commented, may also get done (in some way, with syntax yet to be decided), because it will be useful for other purposes.

**Comment by dankelley** [comment] 2016-07-04 12:13
IMPORTANT:

At present, the docs for `plot,section-method` contain as below. This will need to get removed or updated in the next day or so, to get a release later this week.  We still have this unresolved question of how to indicate a grid (the 4th line). 

My vote is to remove this from the docs, because that yields the possibility of change later. (Undocumented features can change without much hassle.) We've had over a week with no action (by me) on implementing other schemes for indicating how to grid, and that tells me that rushing to code something today (for a release at the end of the week) is a *very* bad idea.

@richardsc -- your vote?

```R
#' ## 4. Image of temperature, with a high-salinity contour on top;
#' ##    note the Mediterranean water.
#' sec <- plot(section, which='temperature', ztype='image')
#' S <- sec[["salinity", "grid:distance-pressure"]]
#' contour(S$distance, S$pressure, S$field, level=35.8, lwd=3, add=TRUE)
#'
#' ## 5. Contours of salinity, with dots for high pressure and spice
#' plot(section, which='salinity')
#' distance <- section[["distance"]]
#' depth <- section[["depth"]]
#' spice <- section[["spice"]]
#' look <- spice > 1.8 & depth > 500
#' points(distance[look], depth[look], col='red')
'```

**Comment by richardsc** [comment] 2016-07-04 15:06
My vote is (I think) as yours -- remove from the docs and only make further changes for a future release. I guess it's not a big deal to leave the present functionality in place, which will get refined/updated/overhauled for the following release.

I don't think this is the time to implement a major `section` plot overhaul for `add=TRUE`.

**Comment by dankelley** [comment] 2016-07-05 09:56
This recent business (geeze I wish GH had threaded comments) is now fixed in `develop`; to see, try 
```
git diff ba3f48b3011ea1081d1312efd857cc718846d877 ce6077407329547a2c1e0274ad659cf35b945737
```

**Comment by dankelley** [comment] 2018-01-20 13:58
I am inclined to close this, in a week (unless @richardsc objects), given:
1. the issue is old but discussion petered out half a year ago
2. the coding to do this would be very tricky, would therefore make the code fragile, and could also introduce new bugs
3. the method would necessarily require remembering state in **user** terms, as opposed to graphical terms. This is not very R-like; when we add to a plot with `lines`, for example, we do so strictly in terms of the variables presented. But consider e.g. the y axis, which might be depth or pressure. The important thing is that the graph itself does not "know" which it is; it just knows the numbers. But the idea of this seems to be to permit `plot,section-method` to add to an existing plot made by the same function, so we get an extra demand that the state has to be remembered, either because the second call has not supplied that state or because it *was* supplied and therefore has to be checked for consistency. But this is not R-like, e.g. when we `lines`, we tell it the x and y; it's up to us to keep track of what those things mean (maybe x is time, maybe it's distance, etc).
4. possibly user interest is not terribly high (item 1 shows that, as does CR's comment https://github.com/dankelley/oce/issues/996#issuecomment-230310383)

My main concern is point 3 above, since point 2 stems from that. So far, oce has remembered state in only one instance -- map projection -- and that is actually a bit problematic.  For example, most graphics items (like margins etc) get erased when you do a new `pdf()` or similar call. But map projections do not ... maybe they should, but how could we do that, without somehow hijacking `dev.off()` to add an extra operation of altering the local function defined in line 6 of `R/map.R` (and note the scary trick that's used with the `<<-` in line 10 of that file).

TLDNR: I plan to close this in 1 week, unless someone asks for a delay (US Senate, anybody).

**Comment by richardsc** [comment] 2018-01-20 17:51
I agree that this issue should be dealt with. Can we at least save the closing for a face-to-face so that we can go through it all together? (it looks like there is a solution posed partway up, that is easy enough as long as it is documented, but I'd rather be sure).

**Comment by dankelley** [comment] 2018-01-20 18:11
Right, let's decide f2f

**Comment by dankelley** [comment] 2018-01-26 18:28
f2f discussion says to close, given new in docs:
```R
## 5. Temperature with salinity added in red
s <- plot(section, which="temperature")
distance <- s[["distance", "byStation"]]
depth <- s[["station", 1]][["depth"]]
salinity <- matrix(s[["salinity"]], byrow=TRUE, nrow=length(s[["station"]]))
contour(distance, depth, salinity, col=2, add=TRUE)
```

**Closed by dankelley** 2018-01-26 18:28 UTC
Labels: fix for next^2 release, graphics, section
