### ISSUE TITLE
mapImage missing bottom color (again?)

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#655] opened 2015-05-27 03:30 UTC
Came across this bug while playing with GSW, hence the sort-of specific looking example:

``` r
library(oce)
library(gsw)
data(coastlineWorld)

## generate a vector for a grid of points on the Earth
lo <- seq(-180, 180, 1)
la <- seq(-90, 90, 1)
lon <- expand.grid(lo, la)[,1]
lat <- expand.grid(lo, la)[,2]

SA <- array(gsw_SA_from_SP(rep(35, length(lon)),
                           rep(100, length(lon)), lon, lat),
            dim=c(length(lo), length(la)))

if (!interactive()) png('gsw_onland.png', width=7*72, height=4*72, type='cairo')

par(mar=rep(1, 4))

mapPlot(coastlineWorld)
mapImage(lo, la, SA, missingColor=NA, col=oceColorsJet)

if (!interactive()) dev.off()
```

![screen shot 2015-05-26 at 11 26 49 pm](https://cloud.githubusercontent.com/assets/233584/7828243/e0b4a6e4-03fe-11e5-8dd4-de7188b8f8e1.png)

Notice that the continents are white, at the minimum value of SA.

However, if I use `colormap()` to control the coloring, everything works as expected:

``` r
cm <- colormap(SA, missingColor = NA)
mapPlot(coastlineWorld)
mapImage(lo, la, SA, colormap = cm)
```

![screen shot 2015-05-26 at 11 29 59 pm](https://cloud.githubusercontent.com/assets/233584/7828254/2680d54e-03ff-11e5-9a84-a9156caa4a43.png)

**Comment by richardsc** [comment] 2015-05-27 03:34
A search of old issues gives a few possibly related previous ones: #368, #516, #337, #309 

Whew, color limits and `mapImage()` clearly have not been trivial!

**Comment by dankelley** [comment] 2015-05-27 13:32
Thanks. I verified the problem in a newly-added item in the test suite. There is also a new meta-issue invoked by ``make issue655``, which exercises the other 4 issues you mention.

**Comment by dankelley** [comment] 2015-05-27 14:10
I wouldn't mind some help on this. I tried changing a ``<=`` into a ``<`` in ``R/map.R`` line 1418. This seems to fix this issue but please try out ``make issue566`` at the main directory level of ode-issues. I am wondering about the check for ``368``. (We don't have test code for the 309 and 337, so I did not put them into the Makefile list for ``issue566``.) The thing is, just looking at the purple text, I don't know whether the behaviour is right or wrong. (As you know, I'm on a mission that we have purple text that tells us whether something is right or wrong, avoiding the need to look through the .R file that makes the test.)

I sort of think the bottom-left panel should is supposed to look like the one above it, but don't know the expected behaviour from the purple text.  (It looks like maybe things are being done in that bottom panel only if debug is 99, and if that's the case I will just remove the bottom panels because this is a long-ago issue and any test code I made for it is either incorporated into oce already or gone from memory.)

**Comment by dankelley** [comment] 2015-06-14 18:28
This is interlocked with #517; if one works, the other fails. Below is a diff that shows how to make one work or the other. I have yet to find a solution that works for both and am mostly posting this to show clearly which part of the code is involved (since a lot of code has changed in the past 19 days)
```
diff --git a/R/map.R b/R/map.R
index bb02a2f..c21f8d0 100644
--- a/R/map.R
+++ b/R/map.R
@@ -1302,7 +1302,8 @@ mapImage <- function(longitude, latitude, z, zlim, zclip=FALSE,
             }
             ## issue522: this was w <- which(zval <= breaks)[1]
             ## issue655: this was w <- which(zval <= breaks)[1]
-            w <- which(zval < breaks)[1]
+            ## **ISSUE644** w <- which(zval < breaks)[1]
+            w <- which(zval <= breaks)[1]
             #if (zval == 0) browser()
             ## if (debug > 10) { ## FIXME (issue 522): retain this test code until 2014-oct
             ##     message("zval:", zval, ", w:", w)
```

**Comment by dankelley** [comment] 2015-06-14 21:27
I think that tomorrow I may make a new issue that combines these several issues, as noted even in the code fragment above. This is just because I find it too confusing to juggle fixes for related issues. The idea will be that I will copy test codes from the existing issues, making sure that there is purple "expect" text on each graph, so that I can do "make" and then "make view" and see all the test results at once, in one directory. I will use checkboxes in the first comment, and will edit the comment as I do the work. My goal in that is to keep the issue webpage simple, since the lack of threading on GH confuses the heck out of me, as does the huge amount of whitespace on GH ... once I have to scroll a page across more than 3 or so screens, I basically lose track.

**Comment by dankelley** [comment] 2015-06-15 11:51
I copied test code ``517/517Bdk.R`` to the present test-code directory, for ease of checking. I also tweaked the code again, with diff as follows. Now, it runs the two examples in ``655`` properly (oce commit 10788e3c62023b172623b07c4f2fc55a8ba86744).

I wonder if @richardsc can check on these test codes, and possibly add others (see the README.md file).

Below is a diff.
```Diff
@@ -1302,7 +1300,7 @@ mapImage <- function(longitude, latitude, z, zlim, zclip=FALSE,
             }
             ## issue522: this was w <- which(zval <= breaks)[1]
             ## issue655: this was w <- which(zval <= breaks)[1]
-            w <- which(zval < breaks)[1]
+            w <- which(zval < breaks + small)[1]
             #if (zval == 0) browser()
             ## if (debug > 10) { ## FIXME (issue 522): retain this test code until 2014-oct
             ##     message("zval:", zval, ", w:", w)
```

**Comment by dankelley** [comment] 2015-06-15 12:30
@richardsc I updated the group test suite so that ``make mapImage`` tests 309, 336, 368, 516, 517 and 655. I had to add some test code for some that were submitted before we used test code. I think everything works except that for both 309 and 368 I was not sure what was expected. If you have time sometime this month, perhaps you could pull and add purple text to 309 and 368 so that a person can tell by reading such text whether the test worked.  (I say "this month" because I think there is no hourly or daily timescale need for this, unless of course you have one.) Thanks!

**Comment by richardsc** [comment] 2015-06-15 17:58
Yup, I can have a look a bit later. I'm the one who keeps finding these bugs, so I should probably be as up to speed on the code behind them as possible. Stay tuned.

**Comment by richardsc** [comment] 2015-06-17 02:15
I spent some time tonight going through the tests for `make mapImage`, and I think everything now looks ok. I had to make a bunch of changes (e.g. for the now deprecated `mapproj` notation), so make sure you pull `oce-issues` before you try the tests again. Might also be a good idea to read some of my commit notes to see other things I changed.

Anyway, this seems fixed for now, so closing!

**Comment by dankelley** [comment] 2015-08-29 17:56
Reopened because the tweak I did for #655 broke this again. The tweak was as follows, i.e. an undoing of a tweak done to get the present thing working. Clearly this needs some more thought.
```
diff --git a/R/map.R b/R/map.R
index ac2c498..8ce2804 100644
--- a/R/map.R
+++ b/R/map.R
@@ -1351,7 +1351,7 @@ mapImage <- function(longitude, latitude, z, zlim, zclip=FALSE,
             }
             ## issue522: this was w <- which(zval <= breaks)[1]
             ## issue655: this was w <- which(zval <= breaks)[1]
-            w <- which(zval < breaks + small)[1]
+            w <- which(zval < breaks + 0*small)[1]
             #if (zval == 0) browser()
             ## if (debug > 10) { ## FIXME (issue 522): retain this test code until 2014-oct
             ##     message("zval:", zval, ", w:", w)
```

**Comment by dankelley** [comment] 2015-08-29 18:03
Hm. I reopened this because I thought the behaviour was wrong. But now I don't think so. My reading of ``?colormap`` tells me the lower-left panel of 655b.R (below) *should* have red splotches, because ``zclip`` is FALSE. So I don't think there is a bug at the moment.  I think the purple text for panel (c) is erroneous ... it should say "as (a) but red for z>100m".

I wonder, can @richardsc comment?

![655b](https://cloud.githubusercontent.com/assets/99469/9563604/24445558-4e5f-11e5-9057-50b18be83abe.png)

**Comment by dankelley** [comment] 2015-08-30 13:56
This is fixed in the ``issue721`` branch (commit a6216ea95e677c2fb94d29dea02f714d323c9862) so I am closing this.

**Comment by dankelley** [comment] 2017-11-19 16:05
I just happened to try these test cases again, after some changes to mapping code, and the results are now crazily bad, e.g. below is 655d.png

![655d](https://user-images.githubusercontent.com/99469/32992517-fc393864-cd21-11e7-907c-59729e1d532a.png)

**Comment by dankelley** [comment] 2017-11-19 16:11
Hm. The test code for `mapImage` works fine, though.

Methinks the problem is in lon either being in (0,360) or (-180,180).

**Comment by dankelley** [comment] 2017-11-22 19:48
The most recently reported problem (https://github.com/dankelley/oce/issues/655#issuecomment-345527882) is now fixed in the "dk" and "mapping" branches, so I'm closing this.

**Closed by dankelley** 2017-11-22 19:48 UTC
