### ISSUE TITLE
T和

### ISSUE THREAD

**Issue by tongruiju** [dankelley/oce#2167] opened 2023-11-13 08:24 UTC
Dear the Team,

I tried to use the approx3d() function from the oce package for trilinear interpolation, but encountered the following error:
> # Use approx3d for trilinear interpolation

> trilinear <- approx3d(x, y, z, v, new_x, new_y, new_z)
Error in approx3d(x, y, z, v, new_x, new_y, new_z) : 
  f must be an array with 3 dimensions
> v_array <- array(NA, dim = c(length(unique(lon)), length(unique(lat)), length(unique(depth))))
Error: cannot allocate vector of size 14689.9 Gb

> len_x <- length(x)
> len_y <- length(y)
> len_z <- length(z)
> v_3d <- array(v, dim = c(len_x, len_y, len_z))
Error in array(v, dim = c(len_x, len_y, len_z)) : vector is too large
> v_3d <- aperm(array(v, dim = c(len_z, len_y, len_x)), c(3, 2, 1))
Error in array(v, dim = c(len_z, len_y, len_x)) : vector is too large
> v_3d <- array(NA, dim = c(len_x, len_y, len_z))
Error in array(NA, dim = c(len_x, len_y, len_z)) : vector is too large

**Comment by dankelley** [comment] 2023-11-13 09:44
1. The error from the oce function means just what it says.  That argument must not be a an array of the required properties.  This is a non-reproducible example, so we can only guess what you have done.
2. The other errors have nothing to do with oce, but they seem to indicate that you are asking for more memory than R on your computer can provide.

**Comment by dankelley** [comment] 2023-11-18 11:59
This is essentially a duplicate of  #2168, so I am closing it here to avoid confusion.

**Closed by dankelley** 2023-11-18 11:59 UTC
