### ISSUE TITLE
OCE ODF Parser doesn't handle well the DFO-IML Flag columns associated with the code QQQQ_XX

### ISSUE THREAD

**Issue by JessyBarrette** [dankelley/oce#1808] opened 2021-04-19 20:05 UTC
### Short summary of problem
DFO-IML uses the GF3 code QQQQ_XX to identify flag column variables within their ODF files. OCE doesn't seem to be able to handle this flag format yet. ODF variables associated with the QQQQ_XX code, where XX is a number, corresponds to the flag column of the corresponding column just on the left of that present one. 

### What you did

Read IML ODF file

### What you expected to happen

ODF QQQQ columns get associated with the matching variables within OCE. 

### What happened

Flag columns are identified but are associated with what seems to be a random character.

### How urgent is this?
This is not a very urgent.

### Output from sessionInfo()
An example file with the present issue can be found [here](https://raw.githubusercontent.com/cioos-siooc/cioos-siooc_data_transform/odf_transform/projects/odf_transform/sample_data/test_files/CTD_1994038_147_1_DN.ODF).

**Comment by dankelley** [comment] 2021-04-19 20:23
Any chance you can add a reprex?  (It saves the oce developers the task of writing test code, and then trying to see what the problem is.  Including a comment like "expect <something> here" can help.  Even better, use `stopifnot()` when that is possible.). Thanks.

**Comment by JessyBarrette** [comment] 2021-04-19 20:47
Sorry my R skills aren't the bests
``` r
odf_data = read.odf("C:/Users/jessy/Documents/test/CTD_1994038_147_1_DN.ODF")
odf_data@metadata["flags"]
```
Gives the flag variables available. With the flags called respectively: `['S','S2','S3','P','S4','QC']`

I would expect them to be called instead `['temperature', 'pressure', 'depth', 'salinity', 'sigmat','QC']`

**Comment by dankelley** [comment] 2021-04-19 21:39
Thanks.  I'll have a look tomorrow or later this week. 

Since you're an R newcomer, I'll explain more about `reprex`.  You really ought to install that package.  Once you have it, check the docs for the `reprex()` function.  Providing a reprex relieves developers from having to write code.  For example, in the reprex given below, I load the library (that's typing for me to do) and then I download the file (again, typing that has to be repeated by the developer).

From the below, I agree that this is a bug.


``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
dir <- "https://raw.githubusercontent.com/cioos-siooc/cioos-siooc_data_transform/odf_transform/projects/odf_transform/sample_data/test_files"
file <- "CTD_1994038_147_1_DN.ODF"
download.file(paste0(dir, "/", file), file)
d <- read.oce(file)
#> Warning in read.odf(file = file, columns = columns, exclude = exclude, debug =
#> debug - : estimating waterDepth from maximum pressure
names(d@metadata$flags)
#> [1] "S"  "S2" "S3" "P"  "S4" "QC"
```

<sup>Created on 2021-04-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by dankelley** [comment] 2021-04-20 10:09
@JessyBarrette In your first comment, you write "DFO-IML uses the GF3 code QQQQ_XX to identify flag column variables within their ODF files." and that makes me think that you must have a copy of DFO-IML documentation on their variant of the ODF format.  If so, could you post it here, or (if GH doesn't permit posting the file type) email it to kelley.dan@gmail.com?

Some of the ODF code was based on reverse-engineering files (and those were mostly DFO-BIO variant).  I've been informed that there are differences between the variants.

**Comment by dankelley** [comment] 2021-04-20 17:10
I see why my pattern-matching was failing.  The ODF/BIO file I based the code on has a line like
```
  NAME= 'Quality Flag for Parameter: PRES_01',
```
(i.e., keyed to the low-level name AKA original-name in oce parlance -- note the lack of spaces) whereas the ODF/IML file provided with this issue has e.g.
```
  NAME= 'Quality flag: Sea Temperature (IPTS-68)',
```
(i.e., keyed to a high-level name).

So I need to find a way to detect this (perhaps by lack of spaces, but preferably by something near the start of the file that indicates the dialect) and then compensate.

I want to find something in an overall header that indicates whether it's BIO or IML dialect, but if that fails, I can try other schemes.

Jeeze, I hope the west-coast people don't have yet another variant...

**Comment by JessyBarrette** [comment] 2021-04-20 17:50
Thanks @dankelley  for looking into this! Unfortunately, I personally don't have access to any documentation related to the IML/MLI ODF format, but I can ask people related to this group for more information. 

CIOOS is working on developing a method to convert the ODF format to NetCDF, we've discussed [here](https://github.com/cioos-siooc/cioos-siooc_data_transform/issues/33) the main differences between the two offices format, perhaps that can be useful. 

As far as I can see based on some files I received, IML has been using the term under NAME instead of CODE to relate the Flag variable. You can find more files IML [here](https://github.com/cioos-siooc/cioos-siooc_data_transform/tree/dev/projects/odf_transform/sample_data/mli_data/2020-12-23/ODF_files_MLI).

Regarding the west coast people (I'm on the west coast), they are using a completely different format, which is based on some Fortran packaged developed at DFO-IOS a long time ago, We used at CIOOS the same Fortran package through some python FORTRAN interface to parse the format and convert it to a NetCDF format (https://data.cioospacific.ca/erddap/tabledap/index.html?page=1&itemsPerPage=1000). Perhaps, OCE could potentially use the same avenue.

**Comment by dankelley** [comment] 2021-04-20 17:59
As Jackson Browne says,
> 'Cause when you stop to let 'em know
You got it down
It's just another town along the road

**Comment by dankelley** [comment] 2021-04-21 13:30
I think this works now in the "odf" branch, commit 8d513b9208684f5728fc2ef29803ef617735f395.  You can see an example at the "Details" section.  Note that I am now more specific on the names of the FFFF and QCFF flags, so that folks who know what those flags really mean can use them without guessing on which is which as they get stored in the `metadata` slot.

@JessyBarrette, could you install that version from github and then try it out, letting me know of any problems you encounter?  (Problems should be in new issues, unless they relate closely to the title of this issue.  We try to avoid issue drift in oce.). Or, if you think this has been addressed, please close the issue.

NOTE: I plan to merge this "odf" branch into the "develop" branch on Saturday morning, unless there are serious problems with it.

<details>

``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

# Test a file from DFO/BIO
bio <- read.oce("~/CTD_BCD2014666_008_1_DN.ODF")
#> Warning in read.odf(file = file, columns = columns, exclude = exclude, debug =
#> debug - : "CRAT_01" should be unitless, but the file states the unit as "S/m" so
#> that is retained in the object metadata. This will likely cause problems. See ?
#> read.odf for an example of rectifying this unit error.
summary(bio)
#> CTD Summary
#> -----------
#> 
#> * Instrument:          Sea-Bird SBE25 
#> * File:                "/Users/kelley/CTD_BCD2014666_008_1_DN.ODF"
#> * Institute:           OESD @ BIO
#> * Chief scientist:     Catherine Johnson
#> * Start time:          2014-12-16 14:09:09
#> * Cruise:              Scotian Shelf
#> * Vessel:              CCGS SIGMA T (Call Sign: unknown)
#> * Station:             008
#> * Location:            44.267N 63.318W
#> * Water depth:         156
#> * Data Overview
#> 
#>                                  Min.    Mean    Max. Dim. NAs OriginalName
#>     scan                         1781  3695.5    4995  294   0      CNTR_01
#>     pressure [dbar]               0.5  74.248   147.5  294   0      PRES_01
#>     temperature [°C, IPTS-68]  3.9824  7.5195  10.421  294   0      TEMP_01
#>     conductivity [S/m]        0.69343 0.78562 0.89532  294   0      CRAT_01
#>     oxygenVoltage [V]          1.6158  2.2027  2.5992  294   0      OXYV_01
#>     fluorometer [mg/m³]        0.3636  1.6972  4.5732  294   0      FLOR_01
#>     par                       0.00197  4.7286  104.43  294   0      PSAR_01
#>     salinity [PSS-78]          30.851  32.693  34.868  294   0      PSAL_01
#>     oxygen [ml/l]              3.0636  5.0665  6.5227  294   0      DOXY_01
#>     sigmaTheta [kg/m³]          24.29  25.515   26.78  294   0      SIGP_01
#> 
#> * Data-quality Flags
#> 
#>     pressure:      "1" 294
#>     temperature:   "1" 294
#>     conductivity:  "1" 294
#>     oxygenVoltage: "1" 294
#>     fluorometer:   "1" 294
#>     par:           "1" 294
#>     salinity:      "1" 293, "3" 1
#>     oxygen:        "1" 294
#>     sigmaTheta:    "1" 290, "3" 4
#>     overall(FFFF): "0" 294
#>     overall(QCFF): "0" 290, "2048" 3, "4096" 1
#> 
#> * Processing Log
#> 
#>     - 2021-04-21 13:26:00.128 UTC: `create 'ctd' object`
#>     - 2021-04-21 13:26:00.129 UTC: `as.ctd(salinity = odf, debug = debug - 1)`
#>     - 2021-04-21 13:26:00.129 UTC: `as.ctd(salinity = odf, debug = debug - 1)`

# Test a file from DFO/IML
iml <- read.oce("~/CTD_1994038_147_1_DN.ODF")
summary(iml)
#> CTD Summary
#> -----------
#> 
#> * Instrument:          Applied STD-12 PLUS 
#> * File:                "/Users/kelley/CTD_1994038_147_1_DN.ODF"
#> * Institute:           DPMM
#> * Chief scientist:     L. Savard et B. Morin
#> * Start time:          1994-09-02 14:15:47
#> * Cruise:              Releve dabondance des poissons de fond et de la crevette et evaluation oceanographique de letat du Golfe
#> * Vessel:              Alfred Needler
#> * Station:             147
#> * Location:            49.972N 65.144W
#> * Water depth:         -99
#> * Data Overview
#> 
#>                                Min.   Mean   Max. Dim. NAs OriginalName
#>     temperature [°C, ITS-90]  0.011  2.192  9.935  433   0      TEMP_01
#>     pressure [dbar]             1.7 105.51  176.9  433   0      PRES_01
#>     depth [m]                  1.69 104.59 175.34  433   0      DEPH_01
#>     salinity [PSS-78]        28.462 32.663 33.897  433   0      PSAL_01
#>     sigmat [kg/m³]           21.865 26.052 26.969  433   0      SIGT_01
#> 
#> * Data-quality Flags
#> 
#>     temperature:   "1" 433
#>     pressure:      "1" 351, "3" 82
#>     depth:         "1" 351, "3" 82
#>     salinity:      "1" 334, "3" 99
#>     sigmat:        "1" 331, "3" 102
#>     overall(QCFF): "0" 331, "2" 6, "16" 28, "18" 54, "2048" 3, "4096" 8, "6144" 3
#> 
#> * Processing Log
#> 
#>     - 2021-04-21 13:26:00.258 UTC: `create 'ctd' object`
#>     - 2021-04-21 13:26:00.258 UTC: `as.ctd(salinity = odf, debug = debug - 1)`
#>     - 2021-04-21 13:26:00.258 UTC: `as.ctd(salinity = odf, debug = debug - 1)`
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by JessyBarrette** [comment] 2021-04-23 19:27
@dankelley I installed the `odf `branch and tried to run it on some of our test ODF files and found two new issues present below, but let's start with a working example! 

``` r
remotes::install_github("dankelley/oce", ref="odf")
#> Skipping install of 'oce' from a github remote, the SHA1 (3cd95a0a) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

dir <- "https://raw.githubusercontent.com/cioos-siooc/cioos-siooc_data_transform/odf_transform/projects/odf_transform/sample_data/mli_data/2020-12-23/ODF_files_MLI"
file <- "CTD_2019004_1_2A_DN.ODF"
download.file(paste0(dir, "/", file), file)
d <- read.oce(file)
#> Warning in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, :
#> unable to interpret ODFunits[10]='Total scale', for item named 'PHT_', so making
#> an educated guess using parse() or, as a last-ditch effort, simply copying the
#> string
#> Warning in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, :
#> unable to interpret ODFunits[12]='metres/sec', for item named 'DPDT', so making
#> an educated guess using parse() or, as a last-ditch effort, simply copying the
#> string

names(d@metadata$flags)
#> [1] "pressure"      "temperature"   "PHT_"          "depth"        
#> [5] "salinity"      "sigmat"        "oxygen"        "overall(QCFF)"
```

That's great!


## Issue 1: Failed to read few ODF files
Some ODF are read normally by the OCE `developed `branch but no in the odf:
``` r
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

dir <- "https://raw.githubusercontent.com/cioos-siooc/cioos-siooc_data_transform/odf_transform/projects/odf_transform/sample_data/mli_data/2020-12-23/ODF_files_MLI"
file <-"MADCP_BOUEE2019_RIMOUSKI_553_ANC.ODF"

download.file(paste0(dir, "/", file), file)
d <- read.oce(file)
#> Warning in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, :
#> unable to interpret ODFunits[6]='True degrees', for item named 'HEAD', so making
#> an educated guess using parse() or, as a last-ditch effort, simply copying the
#> string
#> Error in if (sum(bad) > 0) oceDebug(debug, "set ", sum(bad), " values in '", : missing value where TRUE/FALSE needed
names(d@metadata$flags)
#> Error in eval(expr, envir, enclos): object 'd' not found
```
<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
`Repgex()` does not capture the full error which is:

> d <- read.oce(file)
![image](https://user-images.githubusercontent.com/30420025/115918370-4b133b80-a42c-11eb-99fe-8f9410c0a33a.png)

This same issue applies to the test files listed below for which we have access to [here](https://github.com/cioos-siooc/cioos-siooc_data_transform/tree/odf_transform/projects/odf_transform/sample_data/mli_data/2020-12-23/ODF_files_MLI) and are successfully read by the development branch (ignoring the present flag naming issue) :
``` r
failed_file_list = list('MADCP_BOUEE2019_RIMOUSKI_553_ANC.ODF','MCM_2009098_M2_1378D_3600.ODF','MCTD_2015016_RIKI_2386_900.ODF','MMOB_BOUEE2019_RIMOUSKI_IML4_METOCE.ODF','MTC_2018028_SHEDIAC_THERMO_300.ODF','MTG_2006095_ISTPAUL_1124_3600.ODF','MTR_2018028_RIMOUSKI_3495_300.ODF','TCTD_2005036_81_1_.ODF','TSG_LTTSGP2019_1230_CONNAIGRA_60.ODF')
``` 

## Issue 2: Failed to parse flag variables with NAME = "quality flag of ..."
Unfortunately, it seems like the flag variables aren't consistently using the prefix  `Quality flag:`  but `quality flag of` instead. This lead to the following results:
``` r
remotes::install_github("dankelley/oce", ref="odf")
#> Skipping install of 'oce' from a github remote, the SHA1 (3cd95a0a) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

dir <- "https://raw.githubusercontent.com/cioos-siooc/cioos-siooc_data_transform/odf_transform/projects/odf_transform/sample_data/mli_data/2020-12-23/ODF_files_MLI"
file <-"BOTL_2019004_1_1A_.ODF"

download.file(paste0(dir, "/", file), file)
d <- read.oce(file)
#> Warning in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, :
#> unable to interpret ODFunits[12]='Total scale', for item named 'PHT_', so making
#> an educated guess using parse() or, as a last-ditch effort, simply copying the
#> string
# ...
#> Warning in ODFNames2oceNames(ODFnames, ODFunits, PARAMETER_HEADER = NULL, :
#> unable to interpret ODFunits[58]='mmol/m**3', for item named 'SLCA2', so making
#> an educated guess using parse() or, as a last-ditch effort, simply copying the
#> string
names(d@metadata$flags)
#>  [1] "  NAME= 'quality flag of bottle sample salinity',"                                 
#>  [2] "  NAME= 'quality flag of bottle sample oxygen',"                                   
#>  [3] "  NAME= 'quality flag of bottle sample chlorophyll content',"                      
#>  [4] "  NAME= 'quality flag of bottle sample phaeopigment content',"                     
#>  [5] "  NAME= 'quality flag of bottle sample pH, lab measurement',"                      
#>  [6] "  NAME= 'quality flag of bottle sample pH, in situ calc',"                         
#>  [7] "  NAME= 'quality flag of bottle sample alkalinity',"                               
#>  [8] "  NAME= 'quality flag of bottle sample total inorganic carbon',"                   
#>  [9] "  NAME= 'quality flag of bottle sample nitrite (NO2-N) content',"                  
#> [10] "  NAME= 'quality flag of bottle sample nitrate (NO3-N) + nitrite (NO2-N) content',"
#> [11] "  NAME= 'quality flag of bottle sample phosphate (PO4-P) content',"                
#> [12] "  NAME= 'quality flag of bottle sample silicate (SIO4-SI) content',"               
#> [13] "overall(QCFF)"
```
<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I'm not sure if that is your desired outcome if the commonly used name `Quality flag:` is used. 

This is a pretty long post, but both issues are related to the recent changes to handle to this present issue. Let me know if you want to break this apart.

**Comment by dankelley** [comment] 2021-04-23 19:32
No need to break it apart.  I'll take a look.  NOTE: I will edit the present comment to make a checklist. I do that a lot, to reduce the need to scroll through comments.  (For the same reason, I've edited your previous comment to insert a `<details>` line, so the details can be collapsed.)

**Comment by dankelley** [comment] 2021-04-24 16:56
For clarity, I am going to close this issue because it has spawned other issues with more precise titles.  Please see newer issues with the `ODF` tag.

**Comment by dankelley** [comment] 2021-05-03 09:50
@JessyBarrette -- perhaps you can test out the "odf" branch in the next few days to see if you agree that this problem has been handled.  It is my intention to merge "odf" into "develop" in the afternoon, two days from now.  In the meantime, I'm reopening this, just so it will appear in my "open issues" landing page.

**Comment by dankelley** [comment] 2021-05-07 12:53
NOTE: I plan to merge the "odf" branch into "develop" next Wednesday (May 12) sometime between 1300h and 1500h, Halifax time.  (This comment is being added to all open ODF-related issues.)

**Comment by JessyBarrette** [comment] 2021-05-10 15:54
Sorry for the late reply, yes I'll have a look!

**Comment by JessyBarrette** [comment] 2021-05-10 17:16
@dankelley  Looks like everything is working as expected!!! Thanks for all the work :fireworks:

**Comment by dankelley** [comment] 2021-05-12 19:32
I think this is done now in the "develop" branch (commit 7559d2409e82da14b76180ba27dd0d885ab68b73), which I pushed recently after merging in the "odf" branch.  

To make progress, and in recognition that I have been slow on the ODF changes made over the past few weeks, I am closing this issue, along with the other open ODF issues.  The reporter may, of course, reopen the issue, if desired, or open a new one with a new title, if that is appropriate.

**Closed by dankelley** 2021-05-12 19:32 UTC
Labels: ODF, bug, flags
