### ISSUE TITLE
Reading files from Sontek mod. XR with read.adp.sontek.serial

### ISSUE THREAD

**Issue by stefano-guicciardi** [dankelley/oce#803] opened 2015-12-18 13:24 UTC
In the working directory, I have the files generated by the ADCP Sontek Argonaut mod. XR (files attached in a zip folder). After having created a file list with the following command:
```
files <- list.files(path = "D:\\Documenti\\File_R\\Analisi_oceanografiche\\",pattern="^[DEF]",full.names = TRUE, ignore.case = TRUE)
```
I tried to feed the list to the command read.adp.sontek.serial as follows:
```
read.adp.sontek.serial(files, from=1, by=1, tz=getOption("oceTz"),
longitude=46, latitude=13, type=c("adp","pcadp"), processingLog, debug=getOption("oceDebug"))  
```
but I get the following error message:
```
“Error in read.adp.sontek.serial(files, from = 1, by = 1, tz = getOption("oceTz"),  : cannot determine #beams or #cells, based on first 1000 bytes in buffer”
```
The sessionInfo() are the following:
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ocedata_0.1.3 oce_0.9-17    gsw_1.0-3    

loaded via a namespace (and not attached):
[1] tools_3.2.3
```

I do not have the ability to compile R packages from source.
I have emailed the test files by private email.

[Sontek_XR_files.zip](https://github.com/dankelley/oce/files/66602/Sontek_XR_files.zip)

**Comment by richardsc** [comment] 2015-12-18 14:31
Hi @stefano-guicciardi , thanks for the Issue report -- nicely put together and very descriptive!

I can confirm that oce cannot read those Sontek files, but I'm not surprised, since that looks like a (relatively) new instrument and our experience with reading Sontek data is from only a couple of ADPs last used in 2008!

Further, the `read.adp.sontek.serial()` is a function for reading a special case of sontek data collected via a CF2 data logger (which we used in an experiment), so is unlikely to apply to your case. However, `read.adp.sontek()` doesn't recognize them either (not surprisingly).

I don't understand all the data files in the zip you included, but most of them seem to be plain text files with the ADP data. There is only one binary file, `DEF003.fpx`, which I assume contains the original raw data from the instrument. Do you know @stefano-guicciardi were the other files produced using software, e.g. as an exported data product?

A quick google turned up the manual at:

http://www.hydroscientificwest.com/cms/docs/Argonaut-XR_manual.pdf

What do you think is the best approach here @dankelley ? I expect reading the text files should be pretty straightforward, but the question is if `as.adp()` can handle that yet and if that's a generic enough solution to be useful long term.

**Comment by dankelley** [comment] 2015-12-18 15:18
Thanks for supplying the manual. I'll have a look, during a break from grading, to see whether oce can be altered to handle that. But we have here a user who cannot (yet) build from source, so testing is going to be slow and awkward.  (I can test to see if we read something, but I won't know if it's right without some back-and-forth with the reporter.)

If it were me, i.e. if I were @stefano-guicciardi, I'd try reading the text files and assembling the data into an `oce` object. Note that `as.adp()` is the first step in creating such an object, but it's likely that some customization will be required also, which is not hard, actually.

@stefano-guicciardi -- how will we know if things are right? Do you have some other software that can help us with that? Otherwise it can be very difficult, trying to code things and have them tested nonlocally. Also, I advise you highly to get set up to build from source -- it's not hard, and my guess is that most scientific users set that up at some time or another.

**Comment by richardsc** [comment] 2015-12-18 15:32
@stefano-guicciardi , you can find some instructions for getting set up to build from source here:

https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source#2-windows

It's very easy for Windows.

**Comment by dankelley** [comment] 2015-12-18 15:38
I have to admit I can't figure out even what this instrument is, from the data files! Below is some code that looks at one of the columns in one of the files.
```{r}
library(oce)
d <- read.table("DEF003.dat", header=TRUE)
t <- ISOdatetime(d$Year, d$Month, d$Day, d$Hour, d$Minute, d$Second)
e <- d$VelocityE                       # I have no idea on what this is ... cm/s??
oce.plot.ts(t, e, ylim=c(-100, 100))
```
but in the file named `DEF003.vel` I see entries for 3 cells. And in `DEF003.ctl` I see that the device was set up for 3 cells. So maybe the proper thing to do is to read the cells from `DEF003.vel`?? I can easily hack in some code but I'd prefer not to be guessing on what I should be reading :smiley_cat:

**Comment by stefano-guicciardi** [comment] 2015-12-18 15:45
Dear Prof. Kelley and dear Prof. Richards,

 

first of all I would like to thank you for the time you are spending on my issue. 

Usually I analyze my data with MATHEMATICA, and sometimes with MATLAB. However, to get all the information that is possible to summarize with OCE, I have to elaborate files separately. Moreover, there is not a so large and collaborative MATHEMATICA community as there is for R.  

As I can read on OCE manual, my hope was that with a little modification some OCE commands could work on my files as nicely as your examples show.

OCE works very smoothly with my CTD or sea-level files. It just can’t cope with my ADCP files. 

 If you believe the problem is time-consuming, please let it drop.

Many thanks for your kind attention.

 

My best regards,

Stefano Guicciardi

 

Da: Dan Kelley [mailto:notifications@github.com] 
Inviato: venerdì 18 dicembre 2015 16:19
A: dankelley/oce <oce@noreply.github.com>
Cc: stefano-guicciardi <stefano.guicciardi@an.ismar.cnr.it>
Oggetto: Re: [oce] Reading files from Sontek mod. XR with read.adp.sontek.serial (#803)

 

Thanks for supplying the manual. I'll have a look, during a break from grading, to see whether oce can be altered to handle that. But we have here a user who cannot (yet) build from source, so testing is going to be slow and awkward. (I can test to see if we read something, but I won't know if it's right without some back-and-forth with the reporter.)

If it were me, i.e. if I were @stefano-guicciardi <https://github.com/stefano-guicciardi> , I'd try reading the text files and assembling the data into an oce object. Note that as.adp() is the first step in creating such an object, but it's likely that some customization will be required also, which is not hard, actually.

@stefano-guicciardi <https://github.com/stefano-guicciardi>  -- how will we know if things are right? Do you have some other software that can help us with that? Otherwise it can be very difficult, trying to code things and have them tested nonlocally. Also, I advise you highly to get set up to build from source -- it's not hard, and my guess is that most scientific users set that up at some time or another.

**Comment by dankelley** [comment] 2015-12-18 15:57
I've tried something that might be partly useful. I made it subset a day and plot it. I hope it's OK to plot it and post it here; if not, @stefano-guicciardi please let me know and I or Clark will delete the image.
```r
## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 4))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[-1 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,4] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
res <- as.adp(time=time, distance=distance, v=v)
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)
```
<img width="680" alt="screen shot 2015-12-18 at 11 57 29 am" src="https://cloud.githubusercontent.com/assets/99469/11900840/8b7b901c-a57e-11e5-8470-d8b7da692123.png">

**Comment by richardsc** [comment] 2015-12-18 16:00
That looks halfway sensible, except that this is a 3 beam instrument (I think) so there is no "error" velocity. The velocity array should just have E, N, and U.

**Comment by stefano-guicciardi** [comment] 2015-12-18 16:02
Dear Prof. Kelley,

 

many thanks for your help. Here it is 5pm so I am leaving to come back home.

I will be back to you on Monday.

Again, many thanks for your support.

 

Regards,

Stefano

 

Da: Dan Kelley [mailto:notifications@github.com] 
Inviato: venerdì 18 dicembre 2015 16:58
A: dankelley/oce <oce@noreply.github.com>
Cc: stefano-guicciardi <stefano.guicciardi@an.ismar.cnr.it>
Oggetto: Re: [oce] Reading files from Sontek mod. XR with read.adp.sontek.serial (#803)

 

I've tried something that might be partly useful. I made it subset a day and plot it. I hope it's OK to plot it and post it here; if not, @stefano-guicciardi <https://github.com/stefano-guicciardi>  please let me know and I or Clark will delete the image.

## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 4))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[-1 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,4] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
res <- as.adp(time=time, distance=distance, v=v)
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)

 <https://cloud.githubusercontent.com/assets/99469/11900840/8b7b901c-a57e-11e5-8470-d8b7da692123.png>

**Comment by dankelley** [comment] 2015-12-18 16:02
Thanks; I updated code to as follows
```r
## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 3))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
res <- as.adp(time=time, distance=distance, v=v)
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)
```
and it makes like shown below.
<img width="680" alt="screen shot 2015-12-18 at 12 02 16 pm" src="https://cloud.githubusercontent.com/assets/99469/11900948/34568cf0-a57f-11e5-9cbe-e11cfe68dfe9.png">

**Comment by stefano-guicciardi** [comment] 2015-12-21 08:09
Good morning Prof. Kelley and Prof. Richards.

 

When I tried to run the script below, I get an error message reading “Error: could not find function "as.adp"”.
Also in the OCE package manual, there is no entry for the item “as.adp”.

What function is it?

Many thanks for your kind attention and cooperation.

 

Best regards,

Stefano Guicciardi

­­­­­____________________

Stefano Guicciardi

CNR-ISMAR

Largo Fiera della Pesca, 1

60125 Ancona

Tel: 071-2078850

Fax: 071-55313

 

 

 

Da: Dan Kelley [mailto:notifications@github.com] 
Inviato: venerdì 18 dicembre 2015 17:02
A: dankelley/oce <oce@noreply.github.com>
Cc: stefano-guicciardi <stefano.guicciardi@an.ismar.cnr.it>
Oggetto: Re: [oce] Reading files from Sontek mod. XR with read.adp.sontek.serial (#803)

 

Thanks; I updated code to as follows

## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 3))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
res <- as.adp(time=time, distance=distance, v=v)
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)

and it makes like shown below.
 <https://cloud.githubusercontent.com/assets/99469/11900948/34568cf0-a57f-11e5-9cbe-e11cfe68dfe9.png>

**Comment by dankelley** [comment] 2015-12-21 11:48
Sorry, that is in the *development* branch on GitHub. I really think you should set up to build packages, because otherwise it will be difficult to keep up-to-date on most packages. (The CRAN policy is to limit releases to about 1 per year or season, but many research-level packages tend to be updated almost daily.)

Anyway, the code that *may* work in your old version of `oce` is as follows.
```r
## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 3))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
#res <- as.adp(time=time, distance=distance, v=v)
res <- new("adp", time=time, distance=distance, v=v)
res@metadata$numberOfBeams <- 3
res@metadata$numberOfCells <- ncell
res@metadata$oceCoordinate <- "enu"
res@metadata$cellSize <- "4"
res@metadata$orientation <- "upward"
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)
```

**Comment by stefano-guicciardi** [comment] 2015-12-21 13:30
I greatly appreciate your kind help and suggestions: I will try to set up to build packages.

Merry Christmas and Happy New Year.

 

Stefano Guicciardi

 

Da: Dan Kelley [mailto:notifications@github.com] 
Inviato: lunedì 21 dicembre 2015 12:49
A: dankelley/oce <oce@noreply.github.com>
Cc: stefano-guicciardi <stefano.guicciardi@an.ismar.cnr.it>
Oggetto: Re: [oce] Reading files from Sontek mod. XR with read.adp.sontek.serial (#803)

 

Sorry, that is in the development branch on GitHub. I really think you should set up to build packages, because otherwise it will be difficult to keep up-to-date on most packages. (The CRAN policy is to limit releases to about 1 per year or season, but many research-level packages tend to be updated almost daily.)

Anyway, the code that may work in your old version of oce is as follows.

## a hack that may get us started.
library(oce)
d <- read.table("DEF003.vel", header=FALSE, skip=2)
time <- ISOdatetime(year=d$V2, month=d$V3, day=d$V4, hour=d$V5, min=d$V6, sec=d$V7, tz="UTC")
## Assume an order to the cell info: east, north, up, speed, direction
ntime <- length(time)
ncell <- (dim(d)[2] - 7) / 5
if (ncell != round(ncell, 0))
    stop("cannot understand cells; expecting 5 columns, after 7 columns of sample+time information")
v <- array(NA, dim=c(ntime, ncell, 3))
for (cell in 1:ncell) {
    v[,cell,1] <- d[[ 0 + 7 + cell]] / 100
    v[,cell,2] <- d[[ 1 + 7 + cell]] / 100
    v[,cell,3] <- d[[ 2 + 7 + cell]] / 100
}
## FIXME: next should be inferred from `DEF003.ctl`
distance <- seq(1, by=4, length.out=ncell)
#res <- as.adp(time=time, distance=distance, v=v)
res <- new("adp", time=time, distance=distance, v=v)
res@metadata$numberOfBeams <- 3
res@metadata$numberOfCells <- ncell
res@metadata$oceCoordinate <- "enu"
res@metadata$cellSize <- "4"
res@metadata$orientation <- "upward"
look <- subset(res,
               as.POSIXct("2015-03-19 00:00:00", tz="UTC") <= time &
               time <= as.POSIXct("2015-03-20 00:00:00", tz="UTC"))
plot(look)

**Comment by dankelley** [comment] 2016-01-12 23:43
@stefano-guicciardi did you have any luck? It's been 3 weeks since there have been comments on this issue, and it would be great to know if this is still a problem or whether things are ok now.  In the oce community, we encourage reporters to close issues, rather than to have the developers close them. So, if you think things are resolved, please close this ... otherwise, please put a note on the current status. Thanks, and Happy New Year!  Dan.

**Comment by stefano-guicciardi** [comment] 2016-01-13 07:48
We are struggling to write our own package for the elaboration of data coming from our instrument.

One of the problem is that I am not able to get the original OCE  package code so to be able to modify it according to our needs.

 

Regards,

Stefano Guicciardi 

 

 

Da: Dan Kelley [mailto:notifications@github.com] 
Inviato: mercoledì 13 gennaio 2016 00:43
A: dankelley/oce <oce@noreply.github.com>
Cc: stefano-guicciardi <stefano.guicciardi@an.ismar.cnr.it>
Oggetto: Re: [oce] Reading files from Sontek mod. XR with read.adp.sontek.serial (#803)

 

@stefano-guicciardi <https://github.com/stefano-guicciardi>  did you have any luck? It's been 3 weeks since there have been comments on this issue, and it would be great to know if this is still a problem or whether things are ok now. In the oce community, we encourage reporters to close issues, rather than to have the developers close them. So, if you think things are resolved, please close this ... otherwise, please put a note on the current status. Thanks, and Happy New Year! Dan.

**Comment by richardsc** [comment] 2016-01-14 17:14
Hi @stefano-guicciardi,

If you're looking for the oce source code, you can find it [here on the github repository page](https://github.com/dankelley/oce). If you want to install the most recent version (i.e. the `develop` branch), follow the instructions at:

http://dankelley.github.io/oce/installation.html

If you need help setting up your system to build packages, I've written a guide here:

https://github.com/dankelley/oce/wiki/Configuring-a-system-to-be-able-to-build-oce-from-source

The code snippet that @dankelley wrote [above](https://github.com/dankelley/oce/issues/803#issuecomment-166280127) should be enough to get you going to read the files that you provided, and you can modify as necessary.

**Comment by richardsc** [comment] 2016-01-23 13:03
It's been 9 days since the last comment, and more than a month since the original issue was opened. Since support for these particular files won't be added to oce I'm closing this issue.

**Closed by richardsc** 2016-01-23 13:03 UTC
Labels: adp, I/O
