### ISSUE TITLE
Low-pass filter to remove tidal and diurnal variability

### ISSUE THREAD

**Issue by spencer-tassone** [dankelley/oce#2013] opened 2022-11-03 22:25 UTC
(1) Is the `oce` package capable of performing a low-pass filter to remove tidal and diurnal variability from a water temperature or dissolved oxygen time series? I have little experience with digital filters or complex numbers, etc.

(2) The attached example data is a one-year time series of high-frequency (15-minute) water temperature (`temp`), dissolved oxygen concentration (`do_mgl`), and depth (`depth`) observations. The data come from one of the National Estuarine Research Reserve sites.

[example.csv](https://github.com/dankelley/oce/files/9933391/example.csv)

```r
library(ggplot2)

setwd() # you will need to save the example.csv file then set your working directory wherever you saved it
dat <- read.csv('example.csv')
dat$datetimestamp <- as.POSIXct(dat$datetimestamp, tz = "America/Jamaica", "%Y-%m-%d %H:%M")

ggplot(dat, aes(datetimestamp,temp)) + geom_line()
ggplot(dat, aes(datetimestamp,do_mgl)) + geom_line()
ggplot(dat, aes(datetimestamp,depth)) + geom_line()
```

(3) 
```r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.utf8 
#> [2] LC_CTYPE=English_United States.utf8   
#> [3] LC_MONETARY=English_United States.utf8
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] withr_2.5.0     digest_0.6.29   lifecycle_1.0.3 magrittr_2.0.3 
#>  [5] reprex_2.0.2    evaluate_0.15   highr_0.9       stringi_1.7.8  
#>  [9] rlang_1.0.6     cli_3.3.0       rstudioapi_0.13 fs_1.5.2       
#> [13] rmarkdown_2.14  tools_4.2.1     stringr_1.4.0   glue_1.6.2     
#> [17] xfun_0.33       yaml_2.3.5      fastmap_1.1.0   compiler_4.2.1 
#> [21] htmltools_0.5.3 knitr_1.39
Created on 2022-11-03 with reprex v2.0.2
```

**Comment by dankelley** [comment] 2022-11-03 23:09
oce fits tides by regressing to known tidal frequencies.  From our emails, I think you are interested in removing diurnal signals.  I tried doing some tests with regression along the lines of how tides are done, but didn't get great results. Anyway, the background signal is much stronger than the thing I was regressing to, so I'm not too surprised.  Possibly you can learn something by using smoothing splines.  I show below some ideas on that.  I don't use ggplot so this is using base R.  Also, to fit a smoothing spline you have to remove NA points, so I did that.  I also converted to days, which might help in doing the spline.  The plots could use the original time axis with a bit more fiddling.  This is just a quick demo, in case you're trying to remove diurnal signals.

Try playing with `FAC`, to see what happens.

Digital filtering can also do this kind of thing.  I think your data are on a uniform time interval, so filtering is possible.  Perhaps other oce folks will chime in.  I won't likely see this again until afternoon tomorrow.

I am here just smoothing.  It would leave tidal effects like spring-neap cycles and so forth.  I have only looked at temperature.

```R
dat <- read.csv('example.csv')
t <- as.POSIXct(dat$datetimestamp, tz = "America/Jamaica", "%Y-%m-%d %H:%M")
# It's convenient to put time into a known unit, here seconds.
t <- as.numeric(t)/86400 # time in days
t <- t - t[1]
T <- dat$temp
ok <- is.finite(T)
t <- t[ok]
T <- T[ok]

par(mfrow=c(2,1), mar=c(3,3,1,1), mgp=c(2,0.7,0))
plot(t, T, type="l")
# We must remove NA values to fit a spline.
# Let's set df to FAC x sampling interval
FAC <- 50
dt <- t[2] - t[1]
df <- diff(range(t)) / (FAC*dt)
s <- smooth.spline(t, T, df=FAC)
ps <- predict(s)
lines(t, ps$y, col=2)
# show just the spline
plot(t, ps$y, type="l")
```

![oce2013](https://user-images.githubusercontent.com/99469/199851747-12905426-2d27-4153-b130-2744f3aaf9cf.png)

**Comment by richardsc** [comment] 2022-11-03 23:54
Hi @spencer-tassone -- thanks for using `oce`!

As @dankelley pointed out, there are a bunch of different approaches depending on what your science questions are. Fitting tides to known harmonics is the basis of "tidal analysis", which can then be used to "de-tide" a signal without actually doing any filtering. This works best when the tidal components are stationary, so that the harmonic fit produces sines and cosines that truly capture the tidal variations over the length of the record. This is likely to work best for something like water height, where the astromonical forcing of the sea surface is the dominant mechanism and doesn't change appreciably over seasons/years.

However with something like temperature, which has a lot of potential for other sources of variability, this approach might not work so well. E.g., you might see a tidal signal due to horizontal gradients being sloshed back and forth, but if they are not sinusoidally varying then the de-tiding will fail to remove all of the "tidally-driven" signals.

@dankelley has proposed smoothing splines, which are a wonderful tool for data analysis.

But I suspect that digital filtering is probably more what you're looking for here. `oce` does provide a few functions that can do some "smoothing" or "filtering", such as `lowpass()`, but I recommend you have a look at the [`signal`](https://cran.rstudio.com/web/packages/signal/) package which contains some very commonly used digital filter designs, such as the "Butterworth" filter. The advantage to a digital filter is that it allows you to precisely define frequencies for low- and high-pass cutoffs, which when combined can be used to create a "band-pass" or "band-stop" filter that will remove all variance within a specified frequency band.

If I have a chance I'll try a quick demo using your data sometime in the next day or two.

**Comment by richardsc** [comment] 2022-11-04 01:25
Below is an example using `butter()` and `filtfilt()` from the `signal` package. I've used a first order lowpass filter with a cutoff period of 32 hours (to make sure to get rid of diurnal variability. Note that `filtfilt()` isn't great at handling "edge effects", when the time series doesn't start and end close to zero. A good way to fix this is to detrend the raw data before filtering, then add the trend back after.

```r
library(oce)
library(signal)

dat <- read.csv('example.csv')
dat$time <- as.POSIXct(d$datetimestamp, tz='UTC')

## setup lowpass butterworth filter
fs <- 1/median(diff(as.numeric(dat$time)))
fc <- 1/(32*3600)
W <- fc / (2 * fs)
b <- butter(1, W, 'low') # first order, but could make n larger if needed

## Extract vars for easier access
t <- dat$time
T <- dat$temp
d <- dat$depth

## linearly interpolate NAs to filter, and then replace them after
missingT <- is.na(T)
missingd <- is.na(d)
T <- approx(t, T, t)$y
d <- approx(t, d, t)$y
Tf <- filtfilt(b, T)
Tf[missingT] <- NA
df <- filtfilt(b, d)
df[missingd] <- NA


par(mfrow=c(2, 1))
oce.plot.ts(t, T)
grid()
lines(t, Tf, col=2, lwd=3)

oce.plot.ts(t, d)
grid()
lines(t, df, col=2, lwd=3)
```
<img width="689" alt="image" src="https://user-images.githubusercontent.com/233584/199864993-5c50a521-5f47-4954-a518-d0cf8f95d47e.png">

**Comment by dankelley** [comment] 2022-12-18 14:13
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done.

We use open issues as a sort of "to do" list, so it helps us to know which issues still need to be addressed.

*Thanks!*

PS.  This is a standardized reply.

**Closed** 2022-12-19 12:58 UTC
Labels: advice:science, advice:programming
