### ISSUE TITLE
Feature request: tidal current analysis in tidem()

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1344] opened 2017-11-28 16:30 UTC
@clayton33 and I were chatting last week about doing tidal analysis on ADCP data, and noted that currently `tidem()` is only really capable of handling scalar (i.e. sealevel) data. That means that to do a tidal analysis of current meter data involves treating the u/v components separately.

The analog in the MatlabTM [`t_tide`](https://www.eoas.ubc.ca/~rich/#T_Tide) package is to pass an input time series `XIN` which is complex, of the form `u + iv`. The result (as I recall, haven't gone through an example in awhile) is to produce tidal ellipse parameters (major/minor axes, etc).

Any idea where to start on this @dankelley, and whether it fits with the current approach in `tidem()`? I tagged @clayton33 to help work on it (parly because she is very likely to need it for her current work).

**Comment by dankelley** [comment] 2017-11-28 16:46
We talked about that yesterday during a meeting about a paper in submission.  I think it's well worth doing, and I think @clayton33 was planning on looking into how t-tide does it. Plus I sent some Foreman papers on the topic. A collaboration makes sense in this. I'm going to be quite busy until after exams are finished so I'd propose that she and I start work in Jan 2018. The work would start by my explaining the current code (there are fiddly bits and `R/tides.R` is 1204 lines long). A key thing is that the code uses `data(tidedata)`, which is a set of numbers from Foreman's fortran code (which I think he got from some other researchers). I view Foreman's work as seminal in all of this, because he figured out how to deal with nearby constituents, etc.

One tricky feature is that `lm`, which `tidem` uses, cannot handle complex numbers. Now we could simply do the regression using formulae, but I like the idea of retaining `lm` if we can because then a person could drop in another regression method (e.g. for robust regression, or least-absolute-regression, or any of the dozen types of regression) and `tidem` would still work.

Maybe the three of us should meet sometime. But 2018 would be best for me because of classes.

**Comment by richardsc** [comment] 2017-11-28 16:56
> One tricky feature is that lm, which tidem uses, cannot handle complex numbers.

Yes, I was browsing the `tidem()` and the `t_tide` code, and noticed some of these differences. By my (quick) look, it appears as though `t_tide` is doing a regular matrix inversion approach to the fit? Then it does some bootstrap stuff to figure out errorbars and 95% confidence limits.

Anyway, I agree -- I like the approach of using `lm()` because it makes it simple to potentially change the fitting function, and we also benefit from all the great stuff that `lm()` already does (relatedly, does `tidem()` produce uncertainties from `lm()` the way `t_tide` does?).

Jan 2018 to meet and start looking at it works for me.

**Comment by clayton33** [comment] 2017-11-28 17:13
Starting this in January works for me as well.

**Comment by dankelley** [comment] 2017-11-28 18:10
`tidem` does uncertainties differently than `t-tide`; it uses the `lm` results.

**Comment by dankelley** [comment] 2018-01-07 11:42
Over holiday/storm/weekend breaks, I did some groundwork on this by (a) reformulating how phase is computed, (b) adding inferred constituents and (c) ensuring that `tidem` and T_TIDE produce identical results for amplitude and phase.

I also set up #1358, for making `tidem` compute signal-to-noise ratio, as T_TIDE does (and, I am guessing, as Foreman does).

**Comment by dankelley** [comment] 2018-09-18 11:16
The reasoning for analysis of tidal currents is given in section 3.7, page 44, of Forrester (1983).

Forrester, Warren D. “Canadian Tidal Manual.” Ottawa, Canada: Department of Fisheries and Oceans, 1983. https://www.psmsl.org/train_and_info/training/reading/canadian_manual.php.

**Comment by clayton33** [comment] 2019-02-25 19:39
@richardsc and I sat down weeks ago and he mentioned that it was possible to run python inside of R. I was able to get it going. It requires that you install the `reticulate` R package, python, and the python `utide` package, https://github.com/wesleybowman/UTide . To get a feel for it, I recreated an example that is provided on the utide github site, 

```
# utide_uv_example.ipynb from
# https://github.com/wesleybowman/UTide/blob/master/notebooks/utide_uv_example.ipynb
# but in the R/python environment
rm(list=ls())
library(oce)
library(reticulate)
utide <- import('utide')
pandas <- import('pandas')
np <- import('numpy')
mpl <- import('matplotlib')

# create fake tide function
fakeTide <- function(t, M2amp, M2phase){
  sin(2 * pi * t/12.24 - M2phase)
}

# construct fake data
N <- 500 # odd number for ttide
t <- pandas$date_range(start = '2016-03-29', periods = N, freq = 'H')
np$random$seed(np$int(1))
u <- fakeTide(np$arange(N), M2amp = 2, M2phase = 0) + np$random$randn(np$int(N))
v <- fakeTide(np$arange(N), M2amp = 1, M2phase = np$pi) + np$random$randn(np$int(N))


#df <- data.frame(u = u, v = v)
#write.table(df, file = 'uvForTidalAnalysisTest.txt', row.names = FALSE)

# convert time to number
tnum <- mpl$dates$date2num(d = unlist(t$to_pydatetime()))

# do tidal analysis
coef <- utide$solve(tnum, u, v,
                    lat=-42.5,
                    nodal=FALSE, # note : had to change False to FALSE
                    trend=FALSE,
                    method='ols',
                    conf_int='linear',
                    Rayleigh_min=0.95)
# doing a names(coef) gives
#[1] "name"     "aux"      "nR"       "nNR"      "nI"       "weights"  "Lsmaj"    "Lsmin"    "theta"    "g"        "umean"   
#[12] "vmean"    "g_ci"     "Lsmaj_ci" "Lsmin_ci" "theta_ci" "diagn"
# name has the tidal constituent names,
# Lsmaj, Lsmin are the major and minor amplitude, 
# theta is orientation, and g is greenwich phase

# reconstruct time
tide <- utide$reconstruct(t = tnum, coef = coef)

# plot
#
# py_to_r() doesn't seem to work for DatetimeIndex formatted thing
# so just reconstruct in R
# note that this wouldn't be a big deal using real data 
# because we'd have it in its original format
tR <- seq(from = ISOdate(2016, 03, 29, tz = 'UTC'), length.out = N, by = 'hour')
par(mfrow=c(3,1))
oce.plot.ts(x = tR, y = u)
oce.plot.ts(x = tR, y = tide['u'])
oce.plot.ts(x = tR, y = u - tide['u'])

par(mfrow=c(3,1))
oce.plot.ts(x = tR, y = v)
oce.plot.ts(x = tR, y = tide['v'])
oce.plot.ts(x = tR, y = v - tide['v'])
```

I did a quick comparison to the amplitude, orientation, and phase results from the MATLAB `ttide` package, seemed to do a pretty good job. So for those interested in doing tidal analysis using current meter data, this is an OK way to do it in R for now.

Dealing with times is a bit tricky. For real data, the following rough (non-working) example, is a way to get around it. I found a nice flow chart somewhere on the web that described all of the date formats in python and how to convert one to another. If I come across it again, i'll update this comment.

```
mpl <- import('matplotlib')
# let t be some POSIXct format time vector
tpy <- pandas$to_datetime(r_to_py(t)) # get it in right DatetimeIndex format
tpynum <- mpl$dates$date2num(d = unlist(tpy$to_pydatetime())) # convert to numeric for use in utide$solve
```

I also found that the u,v I supplied to `utide$solve` had to be a numpy array. This might be obvious for more experienced python users, but wasn't entirely obvious to me at first.

**Comment by richardsc** [comment] 2019-02-26 12:16
I think that the above would make a *great* vignette! (though preferably one that doesn't require adding `reticulate` as a depends or suggests).

**Comment by dankelley** [comment] 2019-02-26 12:17
+1 on the vignette, authored by CL :-)

**Comment by clayton33** [comment] 2019-02-26 18:13
Ok ok, you guys win, I'll write one up. 

What are our feelings on this issue? Should we close it for now, or keep it open ?

**Comment by dankelley** [comment] 2019-02-26 18:44
I suggest closing this, but opening a new one titled "Need vignette on tidal analysis" or something.

I was thinking that it might be nice to have a vignette on maps also.  I could write that up, starting with some tables I created for my book.  I also have a blog posting somewhere that shows dozens of maps -- I don't think anyone would bother actually printing a vignette, so I don't see a problem in putting a ton of map projection examples in there.

I propose CL opens an issue and assigns herself. (Not sure if all developers can assign people.) It ought to have labels 'development' and 'request', I think ... again, I can add those if the interface doesn't let CL do it at the start.

**Comment by clayton33** [comment] 2019-03-22 17:37
Request to close this, for now, based on the comment above. I'll open another for the vignette.

**Comment by dankelley** [comment] 2019-03-22 17:40
Thanks, I'll close it. Hint on the vignette: copy the first 25 lines of `vignette/adp.Rmd` exactly, then alter the lines that clearly should be altered, for the names and such. Lines 2 and 15 must have the same text for the title, I think, or else some extra magic doesn't work.

**Closed by dankelley** 2019-03-22 17:40 UTC
Labels: high priority, pinned, request, tidem
