### ISSUE TITLE
Modifying plot titles with oce::plot()

### ISSUE THREAD

**Issue by atcogswell** [dankelley/oce#697] opened 2015-07-13 14:19 UTC
Can anyone tell me how I might be able to create a "main" heading for the oce::plot() function?  I'd like to label the typical 4 plot oce::plot() output with a title detailing the location and metadata date for the cast.

**Comment by dankelley** [comment] 2015-07-13 15:46
There are some tricky ways to handle this, but I think the simplest is to draw the panels individually (which also affords more flexibility if you want to add anything to one of the panels).  I would do as below

```r
library(oce)
data(ctd) # sample data
par(oma=c(0,0,2,0)) # outer margins: thick at top, or side=3
par(mfrow=c(2,2)) # four panels, filled in reading order
plot(ctd,which=1)
plot(ctd,which=2)
plot(ctd,which=3)
plot(ctd,which=5)
title(ctd[["filename"]],outer=TRUE,cex=1.4) # title for overall plot (filename, here)
```
It's not unlikely that @richardsc will have a more elegant solution.

**Comment by atcogswell** [comment] 2015-07-13 16:01
Hi Dan,

I’ll give it a go and let you know.

A

**Comment by richardsc** [comment] 2015-07-13 18:43
This is a great question @atcogswell, and one that I've often avoided trying to answer myself because I just didn't quite care enough. It is a question that highlights some of the peculiarities of the R-graphics way of doing things with `par()` (mfrow, mar, oma, etc).

I tried a slight variation, that doesn't involve plotting individually, but does require a "trick" to actually place the title in the correct place:
```r
library(oce)
data(ctd) # sample data
par(oma=c(0,0,2,0)) # outer margins: thick at top, or side=3
plot(ctd)
t <- sprintf("%.3fE %.3fN %s", ctd[["longitude"]], ctd[["latitude"]],
    format(ctd[["date"]],"%Y-%m-%d %H:%M"))
title('') # empty title to trick it into letting us do the 
title(t, outer=TRUE, cex=1.4) # title for overall plot
```

**Comment by atcogswell** [comment] 2015-07-13 18:46
Dan - seems to work fine, just a small adjustment for my purposes:
    
    par(oma=c(0,0,2,0)) # outer margins: thick at top, or side=3
    par(mfrow=c(2,2)) # four panels, filled in reading order
    plot(ctd,which=1)
    plot(ctd,which=2)
    plot(ctd,which=3)
    plot(ctd,which=5)
    title(paste("Compass Buoy Station CTD Profile",  ctd@metadata$date,sep=": "),outer=TRUE,cex=1.4) # title for overall plot (filename, here)

**Comment by atcogswell** [comment] 2015-07-13 18:53
Thanks **@richardsc** this is a little cleaner.  Weird to have to create empty title, but hey it works!

**Comment by dankelley** [comment] 2015-07-13 18:53
Also, note that Clark's solution is probably nicer. Consider also the ability to wrap this in a function, which is pretty common, e.g.
```r
plotctd <- function(filename) {
d <- read.oce(filename)
# plot as above
}
```
so then e.g. all files in a directory can be plotted with e.g.
```r
for (f in ist.files(pattern="*.odf")) plotctd(f)
```
and one final trick: you can make a whole whack of PNG/whatever files very easily, and build their filenames from the input filenames. Or you can make a multipage PDF, which I find really helpful esp if the ``Slim`` etc are set up to work for the whole dataset ... you can then bang on the arrow key to "animate" through the data.

Not sure on your R skills, so the above might be something you could have taught me :-)

Offline for a few hours now.

**Comment by atcogswell** [comment] 2015-07-13 18:56
I am a relative newbee (2 yrs) so all help is welcome.  I was on my way to the solution you provided for batching, png/pdf exporting and file names, but you saved me the work so thank you very much.

Tks to Clark as well.

**Comment by richardsc** [comment] 2015-07-13 18:58
I think the `title('')` trick has to do with the way that `plot.ctd()` tries to reset the `par` values after it is done plotting. So it sort of "forgets" that it had an outer margin. If instead of doing an empty title you do something like `title('A title')` you'll see it show up in the place that the title *would* have been before doing a four panel plot as is done in `plot.ctd()`. 

The advantage to the oce way of resetting par after finishing the plot, is that you can do something like
```r
plot(ctd) # gives a four-panel plot
plot(x, y)
```
and the second plot will be a single panel, without having to explicitly reset it yourself with a `par(mfrow=c(1,1))`.

**Comment by richardsc** [comment] 2015-07-13 19:03
One note on @dankelley's helpful batch processing example, if the profiles contain quite a few data points, the multi-page pdf can get quite large and slow to view. If you use a `png()` device, you can create a filename that increases incrementally with each plot by doing something like:

```r
png('plot_filename_%03d.png')
for (f in ist.files(pattern="*.odf")) plotctd(f)
dev.off()
```

will create sequentially numbered files like `plot_filename_001.png`, `plot_filename_002.png`, etc ...

If you think the issue is addressed, feel free to close it! We like to let the reporter close the issue so that we can be sure it's been addressed to their satisfaction.

**Comment by dankelley** [comment] 2015-07-16 22:08
@atcogswell please close this if you think it's OK. It can always be reopened later. Our policy with oce is that reporters (not developers) should close issues. That just seems more polite and helpful to us. Thanks. Dan.

**Closed** 2015-07-17 16:17 UTC
Labels: ctd
