### ISSUE TITLE
mapPolygon(coastlineWorld) has horiz. lines in some projections

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#388] opened 2014-01-27 20:44 UTC
Example:

``` splus
library(oce)
data(coastlineWorld)
mapPlot(coastlineWorld)  # default mollweide
mapPolygon(coastlineWorld, col='red')
```

![screen shot 2014-01-27 at 3 44 25 pm](https://f.cloud.github.com/assets/233584/2013321/d802d658-8793-11e3-82fd-2776ed73f33b.png)

**Comment by dankelley** [comment] 2015-01-28 15:51
The problem is not unique to ``oce``.  I just tried ``mapdata`` and got similar. 

(**Aside.**  ``mapdata`` has a hires file with 2M points, compared with 0.5M points for ``coastlineWorldFine`` in the ``ocedata`` package, so that is potentially something worth looking into.)

![screen shot 2015-01-28 at 11 47 53 am](https://cloud.githubusercontent.com/assets/99469/5940843/c1b73bbc-a6e3-11e4-8afc-f64dba184299.png)

**Comment by dankelley** [comment] 2015-01-28 17:13
I looked into the ``mapdata`` hires dataset. (It took writing a C program to decode their format.) So, the file is 4X larger than we have now, but I don't see a lot of improvement. In the snapshot, the left side shows the ``mapdata`` result, and the right side shows with the existing ``ocedata``. There *are* some changes, but nothing dramatic, and I think nothing to suggest moving a new datafile that is 4X larger.

**Comment by richardsc** [comment] 2015-01-28 20:40
Interesting. Of course, `mapdata` depends on `maps`, which in turn depends on `mapproj`, so I guess it shouldn't be surprising that it has the same issues we did.

As for the higher res coastline, I agree that it's probably not worth including, though I'd like to what the improvement might look like at smaller scales (e.g. within a small bay). If there was a easily code-able function that could access the data, then someone could always decide whether to use `coastlineWorldFine` or the mapdata coastline.

**Comment by dankelley** [comment] 2015-01-28 22:57
I think the fact that hires lacks the NW arm indicates that it's not so terrific.  I think that the dataset used in ``ocedata`` is the result of a somewhat clever analysis of existing (much larger) files. I did this sort of analysis in the ``gri`` language, because gri outputs to postscript, and that has a limit of 1500 points in a polygon (amazing, I know) so Gri has to "boil" down any rendered element to get under that limit. It does that by looking at triplets of points, removing the middle point if the distance between it and the line connecting the other two is less than some criterion. It does this repeatedly, making the criterion tighter and tighter, until the resultant data are under 1500.  I made up up as an ad hoc solution but I think basically the same thing is used in other software nowadays.

I had the same idea about making an interface to ``mapdata``. It shouldn't be terribly hard, at least on unix-like machines.  (There is a trick for naming subdirectories [i.e. slash or backslash] on windows machine but I've never looked it up.)

**Comment by dankelley** [comment] 2015-05-26 22:10
I'm getting pretty certain that a solution will be found in the ``sp`` package. There is a function that seems to do this. I will investigate more over the next week.

PS. I've trimmed some comments above that were unrelated to the title of the issue and were more private communication between me and CR.

**Comment by dankelley** [comment] 2015-06-01 14:25
I wrote a new function that gets fairly close to a solution. It has some "opposite-edge shadowing", though, and I may work to remove that at some point. But the major problem of UHL may be about to go away. The test code only works on the branch named ``project_with_rgdal``, and I do not plan on merging that into ``develop`` for several days at the earliest. Below is the test code named ``640/09.R``. Notice that the new function ``coastlineCut()`` may be changed without notice ... in particular, I am contemplating naming the arg ``lon_0`` to match proj.4 convention.

After the code is a snap of the first page. If you build the whole PDF, you can page through and get a mini-movie of a spinning globe.
```r
library(oce)
data(coastlineWorld)
if (!interactive()) pdf("09.pdf", width=7, height=7, pointsize=8)
par(mfrow=c(2,1), mar=c(2, 2, 1, 1), mgp=c(2, 0.7, 0))
xlim <- ylim <- NULL # yields identical map scales on successive pages
for (lon0 in seq(-180, 180, 10)) {
    proj <- "robin"
    mod <- coastlineCut(coastlineWorld, lon0=lon0)
    lon <- mod[["longitude"]]
    lat <- mod[["latitude"]]
    plot(lon, lat, xlim=c(-180,180), ylim=c(-90,90), type='l')
    lines(c(-180, 180, 180, -180, -180), c(-90, -90, 90, 90, -90), col='gray')
    polygon(lon, lat, col='gray')
    proj <- sprintf("+proj=%s +lon_0=%.0f", proj, lon0)
    if (is.null(xlim)) {
        mapPlot(mod, fill='gray', proj=proj)
        xlim <- par('usr')[1:2]
        ylim <- par('usr')[3:4]
    } else {
        mapPlot(mod, fill='gray', proj=proj, xlim=xlim, ylim=ylim, xaxs="i", yaxs="i")
    }
    mtext("BUG: opposite-edge 'shadow'", line=0, col='magenta', font=2, adj=0)
    mtext(proj, side=3, line=0, adj=1)
}
if (!interactive()) dev.off()
```
![screen shot 2015-06-01 at 11 24 56 am](https://cloud.githubusercontent.com/assets/99469/7914979/e16fe110-0850-11e5-8743-0a3abd65285f.png)

**Comment by richardsc** [comment] 2015-06-01 14:32
Great, I'll try testing this later when I get a chance. Though, from the pick above it looks like we've replaced UHL with some UVL! Still, it's an improvement! :)

**Comment by dankelley** [comment] 2015-06-01 14:46
Actually the UVL would go away if ``mapPlot()`` traced the "edge" of the earth, which I actually think would make sense because longitude lines don't always get drawn there, depending on the rotation. But tracing is a little bit tricky. (It's easy to trace for some projections, harder in others, so the best is to write general code that essentially searches for spots that can do UHL.)

PS. I feel that I'll need to merge into ``develop`` before working on any other map-related issue. I've made lots of changes, including some yesterday that get around an uninvertable zone in ``wintri`` projections (something I had fixed within the modified PROJ.4 sources previously).

**Comment by richardsc** [comment] 2015-11-03 03:42
This issue is not gone, but I have found that `coastlineCut()` works for quite a few cases. Relatedly, while searching for something else I found this blog posting:

http://cameron.bracken.bz/finally-an-easy-way-to-fix-the-horizontal-lines-in-ggplot2-maps

and thought there might be some ideas in there. In particular, it seems that they use the PBSmapping package for do the polygon clipping.

**Comment by dankelley** [comment] 2017-06-28 13:04
Closing now, since this has been fixed for quite some time. Certainly, the initial test is fine now. It must be noted that `coastlineCut()` is the best way to shift the central longitude; using `+lon_0=...` in the `projection` argument will cause problems. Also, note that the issue with Antarctica still exists (issue #616) but the present issue (as posed) can be closed. DK+CR decision (finally).

**Closed by dankelley** 2017-06-28 13:04 UTC
Labels: graphics, mapping
