### ISSUE TITLE
plot.section() errors

### ISSUE THREAD

**Issue by mhalvers** [dankelley/oce#907] opened 2016-04-03 17:03 UTC
I have a time series of profiles at one station, and I'd like to make a time/depth plot.

the following call:
```r
section <- as.section(ctd)  # ctd is a list of ctd objects
section <- sectionGrid(section,p=seq(1,300,1),method="boxcar")
plot(section,which=c(1),ztype="image",zbreaks=seq(6,10,.2),ytype="pressure",xtype="time")
```
generates this error:
```
Error in xx[ix] <- x@data$station[[j]]@metadata$startTime : 
  replacement has length zero
```
If you look for startTime in the section object you find it is missing:
```r
for (k in 1:length(ctd)){
  print(section@data$station[[k]]@metadata$startTime)
}
```
However the ctd objects contain times in posixct:
```r
lapply(ctd,function(x) x[["startTime"]])
```
I'm using the development version of oce downloaded April 2 2016

**Comment by dankelley** [comment] 2016-04-03 17:12
It would help if you could send a private email containing your data, which will let me try to reproduce the error. Be assured that your data will be held private, and discarded after the problem has been solved. Normally it is best to email it to both developers (kelley.dan@gmail.com and clark.richards@gmail.com) because we often work together on bug fixes. Thanks!!

**Comment by dankelley** [comment] 2016-04-03 17:17
It would help if you could post a self-contained sample of R code that will yield the issue you've reported. That can save some guesswork in finding the bug. Ideally, please wrap the code in the github notation for R code, meaning to preface it with a line containing three back-tick characters followed by the letter R (i.e. ````R`), and then to add a line at the end containing three backticks.  An example is below.
```
```R
x <- 3.14
```
```

**Comment by dankelley** [comment] 2016-04-03 17:19
It would help if you could post a self-contained sample of R code that will yield the issue you've reported. That can save some guesswork in finding the bug. Ideally, please wrap the code in the github notation for R code, meaning to write a line containing three back-tick characters followed by the letter R, then write your code, and then write a line with three backticks.  An example is below.

    ```R
    x <- 3.14
    ```

**Comment by dankelley** [comment] 2016-04-03 17:53
Thanks for the data. I created a test file in https://github.com/dankelley/oce-issues/blob/master/907/907a.R, which reads as follows.
```r
library(oce)
if (1 == length(list.files(pattern="data_for_section_error.RData"))) {
    load("data_for_section_error.RData") # private data
    section <- as.section(ctd)  # ctd is a list of ctd objects
    section <- sectionGrid(section,p=seq(1,300,1),method="boxcar")
    plot(section,which=c(1),ztype="image",zbreaks=seq(6,10,.2),ytype="pressure",xtype="time")
} else {
    warning("907a.R requires private data to work")
}
```

**Comment by dankelley** [comment] 2016-04-03 18:14
Hi Mark. Perhaps you can retry with the updated `develop` branch. I think I fixed the issue. By the way, those are really interesting looking data. I love seeing profiles from spots other than my own, so I plotted up a few CTD profiles to look, and they are very interesting. I like watermasses and finestructure, so my eye always goes to profiles and TS plots in the beginning, and I noticed either an overturning signal or a time-lag-problem artifact in the TS.

If you think the issue has been addressed in `develop`, please close it. If not, please add further info. I think both Clark and I will be offline for the rest of the east-coast afternoon.

Dan.

**Comment by mhalvers** [comment] 2016-04-03 18:44
The plot.section(...,xtype='time') issue is solved. 

But I should point out that if startTime is specified as a string, as is specified by the as.ctd() help file, and is actually a time (e.g 07:43:00), then plot.section(...,xtype='time') throws and error:

```r
> plot(section,which=c(1),ztype="image",zbreaks=seq(6,10,.2),
+      ytype="pressure",xtype="time")
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In numberAsPOSIXct(xx) : NAs introduced by coercion
2: In min.default(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,  :
  no non-missing arguments to min; returning Inf
3: In max.default(c(NA_real_, NA_real_, NA_real_, NA_real_, NA_real_,  :
  no non-missing arguments to max; returning -Inf
4: In min(x) : no non-missing arguments to min; returning Inf
5: In max(x) : no non-missing arguments to max; returning -Inf
```

I suspect the easy fix here is with the documentation.  Asking for startTime to be a posixct object would  solve the problem.  Additionally, trying to produce section plots with multiple days of data, but only having times (without days) will produce problems.

**Comment by richardsc** [comment] 2016-04-04 00:05
> The plot.section(...,xtype='time') issue is solved.

Thanks Mark. If you're happy with the original issue, feel free to close this (we like to let the reporter close in case there's anything we forget or make worse in dealing with the problem).

I agree with you on the `startTime` documentation for `as.ctd()`. I'm going to post your notes above to a new issue #908.

**Closed** 2016-04-04 00:09 UTC
Labels: ctd, section
